unit dsp_data;

{$ifdef fpc}{$mode delphi}{$H+}{$endif}

interface
uses games_data;

const
  GAME_TOTAL_DSP=436;
  GAME_DATA_DSP:array[0..(GAME_TOTAL_DSP-1)] of tipo_games=(
(nombre:'Spectrum 48K';dir:'spectrum';exec:'Sinclair';ciclos:0;extra_param:'1982'),
(nombre:'Spectrum 128K';dir:'spec128';exec:'Sinclair';ciclos:1;extra_param:'1986'),
(nombre:'Spectrum +3';dir:'plus3';exec:'Amstrad';ciclos:2;extra_param:'1987'),
(nombre:'Spectrum +2A';dir:'plus3';exec:'Amstrad';ciclos:3;extra_param:'1987'),
(nombre:'Spectrum +2';dir:'plus2';exec:'Amstrad';ciclos:4;extra_param:'1986'),
(nombre:'Spectrum 16K';dir:'spectrum';exec:'Sinclair';ciclos:5;extra_param:'1982'),
(nombre:'Amstrad CPC 464';dir:'cpc464';exec:'Amstrad';ciclos:7;extra_param:'1984'),
(nombre:'Amstrad CPC 664';dir:'cpc664';exec:'Amstrad';ciclos:8;extra_param:'1984'),
(nombre:'Amstrad CPC 6128';dir:'cpc6128';exec:'Amstrad';ciclos:9;extra_param:'1985'),
(nombre:'Commodore 64';dir:'c64';exec:'Commodore';ciclos:3000;extra_param:'1982'),
(nombre:'Oric Atmos';dir:'orica';exec:'Tangerine';ciclos:3001;extra_param:'1984'),
(nombre:'Oric 1';dir:'oric1';exec:'Tangerine';ciclos:3002;extra_param:'1983'),
(nombre:'Pacman';dir:'pacman';exec:'Namco';ciclos:10;extra_param:'1980'),
(nombre:'Phoenix';dir:'phoenix';exec:'Amstar Electronics';ciclos:11;extra_param:'1980'),
(nombre:'Mysterious Stones';dir:'mystston';exec:'Technos';ciclos:12;extra_param:'1984'),
(nombre:'Bomb Jack';dir:'bombjack';exec:'Tehkan';ciclos:13;extra_param:'1984'),
(nombre:'Frogger';dir:'frogger';exec:'Konami';ciclos:14;extra_param:'1981'),
(nombre:'Donkey Kong';dir:'dkong';exec:'Nintendo';ciclos:15;extra_param:'1981'),
(nombre:'Black Tiger';dir:'blktiger';exec:'Capcom';ciclos:16;extra_param:'1986'),
(nombre:'Green Beret';dir:'gberet';exec:'Konami';ciclos:17;extra_param:'1985'),
(nombre:'Commando';dir:'commando';exec:'Capcom';ciclos:18;extra_param:'1985'),
(nombre:'Ghosts''n Goblins';dir:'gng';exec:'Capcom';ciclos:19;extra_param:'1985'),
(nombre:'Mikie';dir:'mikie';exec:'Konami';ciclos:20;extra_param:'1985'),
(nombre:'Shaolin''s Road';dir:'shaolins';exec:'Konami';ciclos:21;extra_param:'1985'),
(nombre:'Yie Ar Kung-Fu';dir:'yiear';exec:'Konami';ciclos:22;extra_param:'1985'),
(nombre:'Asteroids';dir:'asteroid';exec:'Atari';ciclos:23;extra_param:'1979'),
(nombre:'Son Son';dir:'sonson';exec:'Capcom';ciclos:24;extra_param:'1984'),
(nombre:'Star Force';dir:'starforc';exec:'Tehkan';ciclos:25;extra_param:'1984'),
(nombre:'Rygar';dir:'rygar';exec:'Tecmo';ciclos:26;extra_param:'1986'),
(nombre:'Pitfall II';dir:'pitfall2';exec:'Sega';ciclos:27;extra_param:'1984'),
(nombre:'Pooyan';dir:'pooyan';exec:'Konami';ciclos:28;extra_param:'1982'),
(nombre:'Jungler';dir:'jungler';exec:'Konami';ciclos:29;extra_param:'1981'),
(nombre:'City Connection';dir:'citycon';exec:'Jaleco';ciclos:30;extra_param:'1986'),
(nombre:'Burger Time';dir:'btime';exec:'Deco';ciclos:31;extra_param:'1982'),
(nombre:'Express Raider';dir:'exprraid';exec:'Deco';ciclos:32;extra_param:'1986'),
(nombre:'Super Basketball';dir:'sbasketb';exec:'Konami';ciclos:33;extra_param:'1984'),
(nombre:'Lady Bug';dir:'ladybug';exec:'Universal';ciclos:34;extra_param:'1981'),
(nombre:'Teddy Boy Blues';dir:'teddybb';exec:'Sega';ciclos:35;extra_param:'1985'),
(nombre:'Wonder Boy';dir:'wboy';exec:'Sega';ciclos:36;extra_param:'1986'),
(nombre:'Wonder Boy in Monster Land';dir:'wbml';exec:'Sega';ciclos:37;extra_param:'1987'),
(nombre:'Tehkan World Cup';dir:'tehkanwc';exec:'Tehkan';ciclos:38;extra_param:'1985'),
(nombre:'Popeye';dir:'popeye';exec:'Nintendo';ciclos:39;extra_param:'1982'),
(nombre:'Psychic 5';dir:'psychic5';exec:'Jaleco';ciclos:40;extra_param:'1987'),
(nombre:'Terra Cresta';dir:'terracre';exec:'Nichibutsu';ciclos:41;extra_param:'1985'),
(nombre:'Kung-Fu Master';dir:'kungfum';exec:'Irem';ciclos:42;extra_param:'1987'),
(nombre:'Shoot Out';dir:'shootout';exec:'Data East';ciclos:43;extra_param:'1985'),
(nombre:'Vigilante';dir:'vigilant';exec:'Irem';ciclos:44;extra_param:'1988'),
(nombre:'Jackal';dir:'jackal';exec:'Konami';ciclos:45;extra_param:'1986'),
(nombre:'Bubble Bobble';dir:'bublbobl';exec:'Taito';ciclos:46;extra_param:'1986'),
(nombre:'Galaxian';dir:'galaxian';exec:'Namco';ciclos:47;extra_param:'1979'),
(nombre:'Jump Bug';dir:'jumpbug';exec:'Rock-Ola';ciclos:48;extra_param:'1981'),
(nombre:'Moon Cresta';dir:'mooncrst';exec:'Nichibutsu';ciclos:49;extra_param:'1980'),
(nombre:'Rally X';dir:'rallyx';exec:'Namco';ciclos:50;extra_param:'1980'),
(nombre:'Prehistoric Isle in 1930';dir:'prehisle';exec:'SNK';ciclos:51;extra_param:'1989'),
(nombre:'Tiger Road';dir:'tigeroad';exec:'Capcom';ciclos:52;extra_param:'1987'),
(nombre:'F1 Dream';dir:'f1dream';exec:'Capcom';ciclos:53;extra_param:'1988'),
(nombre:'Snowbros';dir:'snowbros';exec:'Toaplan';ciclos:54;extra_param:'1990'),
(nombre:'Toki';dir:'toki';exec:'TAD';ciclos:55;extra_param:'1989'),
(nombre:'Contra';dir:'contra';exec:'Konami';ciclos:56;extra_param:'1987'),
(nombre:'Mappy';dir:'mappy';exec:'Namco';ciclos:57;extra_param:'1983'),
(nombre:'Rastan';dir:'rastan';exec:'Taito';ciclos:58;extra_param:'1987'),
(nombre:'Legendary Wings';dir:'lwings';exec:'Capcom';ciclos:59;extra_param:'1986'),
(nombre:'Section Z';dir:'sectionz';exec:'Capcom';ciclos:60;extra_param:'1985'),
(nombre:'Trojan';dir:'trojan';exec:'Capcom';ciclos:61;extra_param:'1986'),
(nombre:'Street Fighter';dir:'sf';exec:'Capcom';ciclos:62;extra_param:'1987'),
(nombre:'DigDug II';dir:'digdug2';exec:'Namco';ciclos:63;extra_param:'1985'),
(nombre:'Super Pacman';dir:'superpac';exec:'Namco';ciclos:64;extra_param:'1985'),
(nombre:'Galaga';dir:'galaga';exec:'Namco';ciclos:65;extra_param:'1981'),
(nombre:'Xain''d Sleena';dir:'xsleena';exec:'Technos';ciclos:66;extra_param:'1986'),
(nombre:'Hard Head';dir:'hardhead';exec:'Suna';ciclos:67;extra_param:'1988'),
(nombre:'Hard Head 2';dir:'hardhea2';exec:'Suna';ciclos:68;extra_param:'1989'),
(nombre:'Saboten Bombers';dir:'sabotenb';exec:'NMK';ciclos:69;extra_param:'1992'),
(nombre:'New Rally X';dir:'nrallyx';exec:'Namco';ciclos:70;extra_param:'1981'),
(nombre:'Bomb Jack Twin';dir:'bjtwin';exec:'NMK';ciclos:71;extra_param:'1993'),
(nombre:'Spelunker';dir:'spelunkr';exec:'Broderbound';ciclos:72;extra_param:'1985'),
(nombre:'Spelunker II';dir:'spelunk2';exec:'Broderbound';ciclos:73;extra_param:'1986'),
(nombre:'Lode Runner';dir:'ldrun';exec:'Irem';ciclos:74;extra_param:'1984'),
(nombre:'Lode Runner II';dir:'ldrun2';exec:'Irem';ciclos:75;extra_param:'1984'),
(nombre:'Knuckle Joe';dir:'kncljoe';exec:'Taito';ciclos:76;extra_param:'1985'),
(nombre:'Wardner';dir:'wardner';exec:'Taito';ciclos:77;extra_param:'1987'),
(nombre:'Big Karnak';dir:'bigkarnk';exec:'Gaelco';ciclos:78;extra_param:'1991'),
(nombre:'Exed-Exes';dir:'exedexes';exec:'Capcom';ciclos:79;extra_param:'1985'),
(nombre:'Gun.Smoke';dir:'gunsmoke';exec:'Capcom';ciclos:80;extra_param:'1985'),
(nombre:'1942';dir:'1942';exec:'Capcom';ciclos:81;extra_param:'1984'),
(nombre:'1943';dir:'1943';exec:'Capcom';ciclos:82;extra_param:'1987'),
(nombre:'1943 Kai';dir:'1943kai';exec:'Capcom';ciclos:83;extra_param:'1987'),
(nombre:'Jail Break';dir:'jailbrek';exec:'Konami';ciclos:84;extra_param:'1986'),
(nombre:'Circus Charlie';dir:'circusc';exec:'Konami';ciclos:85;extra_param:'1984'),
(nombre:'Iron Horse';dir:'ironhors';exec:'Konami';ciclos:86;extra_param:'1986'),
(nombre:'R-Type';dir:'rtype';exec:'Irem';ciclos:87;extra_param:'1987'),
(nombre:'MS. Pac-man';dir:'mspacman';exec:'Namco';ciclos:88;extra_param:'1981'),
(nombre:'Break Thru';dir:'brkthru';exec:'Data East';ciclos:89;extra_param:'1986'),
(nombre:'Darwin 4078';dir:'darwin';exec:'Data East';ciclos:90;extra_param:'1986'),
(nombre:'Super Real Darwin';dir:'srdarwin';exec:'Data East';ciclos:91;extra_param:'1987'),
(nombre:'Double Dragon';dir:'ddragon';exec:'Taito';ciclos:92;extra_param:'1987'),
(nombre:'Mr. Do!';dir:'mrdo';exec:'Universal';ciclos:93;extra_param:'1982'),
(nombre:'The Glob';dir:'theglob';exec:'Epos';ciclos:94;extra_param:'1983'),
(nombre:'Super Glob';dir:'suprglob';exec:'Epos';ciclos:95;extra_param:'1983'),
(nombre:'Double Dragon II - The Revenge';dir:'ddragon2';exec:'Technos';ciclos:96;extra_param:'1988'),
(nombre:'Silk Worm';dir:'silkworm';exec:'Tecmo';ciclos:97;extra_param:'1988'),
(nombre:'Tiger Heli';dir:'tigerh';exec:'Taito';ciclos:98;extra_param:'1985'),
(nombre:'Slap Fight';dir:'slapfigh';exec:'Taito';ciclos:99;extra_param:'1986'),
(nombre:'The Legend of Kage';dir:'lkage';exec:'Taito';ciclos:100;extra_param:'1984'),
(nombre:'Thunder Hoop';dir:'thoop';exec:'Gaelco';ciclos:101;extra_param:'1992'),
(nombre:'Cabal';dir:'cabal';exec:'TAD';ciclos:102;extra_param:'1988'),
(nombre:'Ghouls''n Ghosts';dir:'ghouls';exec:'Capcom';ciclos:103;extra_param:'1988'),
(nombre:'Final Fight';dir:'ffight';exec:'Capcom';ciclos:104;extra_param:'1989'),
(nombre:'The King of Dragons';dir:'kod';exec:'Capcom';ciclos:105;extra_param:'1991'),
(nombre:'Street Fighter II - The World Warrior';dir:'sf2';exec:'Capcom';ciclos:106;extra_param:'1991'),
(nombre:'Strider';dir:'strider';exec:'Capcom';ciclos:107;extra_param:'1989'),
(nombre:'Three Wonders';dir:'3wonders';exec:'Capcom';ciclos:108;extra_param:'1991'),
(nombre:'Captain Commando';dir:'captcomm';exec:'Capcom';ciclos:109;extra_param:'1991'),
(nombre:'Knights of the Round';dir:'knights';exec:'Capcom';ciclos:110;extra_param:'1991'),
(nombre:'Street Fighter II'': Champion Edition';dir:'sf2ce';exec:'Capcom';ciclos:111;extra_param:'1992'),
(nombre:'Cadillacs and Dinosaurs';dir:'dino';exec:'Capcom';ciclos:112;extra_param:'1992'),
(nombre:'The Punisher';dir:'punisher';exec:'Capcom';ciclos:113;extra_param:'1993'),
(nombre:'Shinobi';dir:'shinobi';exec:'Sega';ciclos:114;extra_param:'1987'),
(nombre:'Alex Kidd';dir:'alexkidd';exec:'Sega';ciclos:115;extra_param:'1986'),
(nombre:'Fantasy Zone';dir:'fantzone';exec:'Sega';ciclos:116;extra_param:'1986'),
(nombre:'Time Pilot ''84';dir:'tp84';exec:'Konami';ciclos:117;extra_param:'1984'),
(nombre:'Tutankham';dir:'tutankhm';exec:'Konami';ciclos:118;extra_param:'1982'),
(nombre:'Pang';dir:'pang';exec:'Capcom';ciclos:119;extra_param:'1989'),
(nombre:'Ninja Kid II';dir:'ninjakd2';exec:'UPL';ciclos:120;extra_param:'1987'),
(nombre:'Ark Area';dir:'arkarea';exec:'UPL';ciclos:121;extra_param:'1988'),
(nombre:'Mutant Night';dir:'mnight';exec:'UPL';ciclos:122;extra_param:'1987'),
(nombre:'Sky Kid';dir:'skykid';exec:'Namco';ciclos:123;extra_param:'1985'),
(nombre:'Rolling Thunder';dir:'rthunder';exec:'Namco';ciclos:124;extra_param:'1986'),
(nombre:'Hopping Mappy';dir:'hopmappy';exec:'Namco';ciclos:125;extra_param:'1986'),
(nombre:'Sky Kid Deluxe';dir:'skykiddx';exec:'Namco';ciclos:126;extra_param:'1986'),
(nombre:'Roc''n Rope';dir:'rocnrope';exec:'Konami';ciclos:127;extra_param:'1983'),
(nombre:'Repulse';dir:'repulse';exec:'Crux/Sega';ciclos:128;extra_param:'1985'),
(nombre:'The NewZealand Story';dir:'tnzs';exec:'Taito';ciclos:129;extra_param:'1988'),
(nombre:'Insector X';dir:'insectx';exec:'Taito';ciclos:130;extra_param:'1989'),
(nombre:'Pacland';dir:'pacland';exec:'Namco';ciclos:131;extra_param:'1984'),
(nombre:'Mario Bros.';dir:'mario';exec:'Nintendo';ciclos:132;extra_param:'1983'),
(nombre:'Solomon''s Key';dir:'solomon';exec:'Tecmo';ciclos:133;extra_param:'1986'),
(nombre:'Combat School';dir:'combatsc';exec:'Konami';ciclos:134;extra_param:'1988'),
(nombre:'Heavy Unit';dir:'hvyunit';exec:'Taito';ciclos:135;extra_param:'1988'),
(nombre:'P.O.W. - Prisoners of War';dir:'pow';exec:'SNK';ciclos:136;extra_param:'1988'),
(nombre:'Street Smart';dir:'streetsm';exec:'SNK';ciclos:137;extra_param:'1988'),
(nombre:'P47 - Phantom Fighter';dir:'p47';exec:'Jaleco';ciclos:138;extra_param:'1989'),
(nombre:'Rod-Land';dir:'rodland';exec:'Jaleco';ciclos:139;extra_param:'1990'),
(nombre:'Saint Dragon';dir:'stdragon';exec:'Jaleco';ciclos:140;extra_param:'1989'),
(nombre:'Time Pilot';dir:'timeplt';exec:'Konami';ciclos:141;extra_param:'1982'),
(nombre:'Pengo';dir:'pengo';exec:'Sega';ciclos:142;extra_param:'1982'),
(nombre:'Scramble';dir:'scramble';exec:'Konami';ciclos:143;extra_param:'1981'),
(nombre:'Super Cobra';dir:'scobra';exec:'Konami';ciclos:144;extra_param:'1981'),
(nombre:'Amidar';dir:'amidar';exec:'Konami';ciclos:145;extra_param:'1982'),
(nombre:'Twin Cobra';dir:'twincobr';exec:'Taito';ciclos:146;extra_param:'1987'),
(nombre:'Flying Shark';dir:'fshark';exec:'Taito';ciclos:147;extra_param:'1987'),
(nombre:'Jr. Pac-Man';dir:'jrpacman';exec:'Bally Midway';ciclos:148;extra_param:'1983'),
(nombre:'Ikari III - The Rescue';dir:'ikari3';exec:'SNK';ciclos:149;extra_param:'1989'),
(nombre:'Search and Rescue';dir:'searchar';exec:'SNK';ciclos:150;extra_param:'1989'),
(nombre:'Choplifter';dir:'choplift';exec:'Sega';ciclos:151;extra_param:'1985'),
(nombre:'Mister Viking';dir:'mrviking';exec:'Sega';ciclos:152;extra_param:'1983'),
(nombre:'Sega Ninja';dir:'seganinj';exec:'Sega';ciclos:153;extra_param:'1985'),
(nombre:'Up''n Down';dir:'upndown';exec:'Sega';ciclos:154;extra_param:'1983'),
(nombre:'Flicky';dir:'flicky';exec:'Sega';ciclos:155;extra_param:'1984'),
(nombre:'Robocop';dir:'robocop';exec:'Data East';ciclos:156;extra_param:'1988'),
(nombre:'Baddudes vs. DragonNinja';dir:'baddudes';exec:'Data East';ciclos:157;extra_param:'1988'),
(nombre:'Hippodrome';dir:'hippodrm';exec:'Data East';ciclos:158;extra_param:'1989'),
(nombre:'Tumble Pop';dir:'tumblep';exec:'Data East';ciclos:159;extra_param:'1991'),
(nombre:'Funky Jet';dir:'funkyjet';exec:'Mitchell';ciclos:160;extra_param:'1992'),
(nombre:'Super Burger Time';dir:'supbtime';exec:'Data East';ciclos:161;extra_param:'1990'),
(nombre:'Caveman Ninja';dir:'cninja';exec:'Data East';ciclos:162;extra_param:'1991'),
(nombre:'Robocop 2';dir:'robocop2';exec:'Data East';ciclos:163;extra_param:'1991'),
(nombre:'Diet Go Go';dir:'dietgo';exec:'Data East';ciclos:164;extra_param:'1992'),
(nombre:'Act-Fancer Cybernetick Hyper Weapon';dir:'actfancr';exec:'Data East';ciclos:165;extra_param:'1989'),
(nombre:'Arabian';dir:'arabian';exec:'Sun Electronics';ciclos:166;extra_param:'1983'),
(nombre:'Dig Dug';dir:'digdug';exec:'Namco';ciclos:167;extra_param:'1982'),
(nombre:'Donkey Kong Jr.';dir:'dkongjr';exec:'Nintendo';ciclos:168;extra_param:'1982'),
(nombre:'Donkey Kong 3';dir:'dkong3';exec:'Nintendo';ciclos:169;extra_param:'1983'),
(nombre:'Pirate Ship Higemaru';dir:'higemaru';exec:'Capcom';ciclos:170;extra_param:'1984'),
(nombre:'Bagman';dir:'bagman';exec:'Valadon Automation';ciclos:171;extra_param:'1982'),
(nombre:'Super Bagman';dir:'sbagman';exec:'Valadon Automation';ciclos:172;extra_param:'1984'),
(nombre:'Squash';dir:'squash';exec:'Gaelco';ciclos:173;extra_param:'1992'),
(nombre:'Biomechanical Toy';dir:'biomtoy';exec:'Gaelco';ciclos:174;extra_param:'1995'),
(nombre:'Congo Bongo';dir:'congo';exec:'Sega';ciclos:175;extra_param:'1983'),
(nombre:'Kangaroo';dir:'kangaroo';exec:'Sun Electronics';ciclos:176;extra_param:'1982'),
(nombre:'Bionic Commando';dir:'bionicc';exec:'Capcom';ciclos:177;extra_param:'1987'),
(nombre:'WWF Superstar';dir:'wwfsstar';exec:'Technos Japan';ciclos:178;extra_param:'1989'),
(nombre:'Rainbow Islands';dir:'rbisland';exec:'Taito';ciclos:179;extra_param:'1987'),
(nombre:'Rainbow Islands Extra';dir:'rbislande';exec:'Taito';ciclos:180;extra_param:'1987'),
(nombre:'Volfied';dir:'volfied';exec:'Taito';ciclos:181;extra_param:'1989'),
(nombre:'Operation Wolf';dir:'opwolf';exec:'Taito';ciclos:182;extra_param:'1987'),
(nombre:'Super Pang';dir:'spang';exec:'Capcom';ciclos:183;extra_param:'1990'),
(nombre:'Outrun';dir:'outrun';exec:'Sega';ciclos:184;extra_param:'1989'),
(nombre:'Elevator Action';dir:'elevator';exec:'Taito';ciclos:185;extra_param:'1983'),
(nombre:'Alien Syndrome';dir:'aliensyn';exec:'Sega';ciclos:186;extra_param:'1988'),
(nombre:'Wonder Boy III - Monster Lair';dir:'wb3';exec:'Sega';ciclos:187;extra_param:'1987'),
(nombre:'Zaxxon';dir:'zaxxon';exec:'Sega';ciclos:188;extra_param:'1982'),
(nombre:'Jungle King';dir:'junglek';exec:'Taito';ciclos:189;extra_param:'1982'),
(nombre:'Hammerin'' Harry';dir:'hharry';exec:'Irem';ciclos:190;extra_param:'1990'),
(nombre:'R-Type II';dir:'rtype2';exec:'Irem';ciclos:191;extra_param:'1989'),
(nombre:'The Tower of Druaga';dir:'todruaga';exec:'Namco';ciclos:192;extra_param:'1984'),
(nombre:'Motos';dir:'motos';exec:'Namco';ciclos:193;extra_param:'1985'),
(nombre:'Dragon Buster';dir:'drgnbstr';exec:'Namco';ciclos:194;extra_param:'1984'),
(nombre:'Vulgus';dir:'vulgus';exec:'Capcom';ciclos:195;extra_param:'1984'),
(nombre:'Double Dragon 3 - The Rosetta Stone';dir:'ddragon3';exec:'Technos';ciclos:196;extra_param:'1990'),
(nombre:'Block Out';dir:'blockout';exec:'Technos';ciclos:197;extra_param:'1990'),
(nombre:'Tetris (Sega)';dir:'tetris';exec:'Sega';ciclos:198;extra_param:'1988'),
(nombre:'Food Fight';dir:'foodf';exec:'Atari';ciclos:199;extra_param:'1982'),
(nombre:'Snap Jack';dir:'snapjack';exec:'Universal';ciclos:200;extra_param:'1982'),
(nombre:'Cosmic Avenger';dir:'cavenger';exec:'Universal';ciclos:201;extra_param:'1981'),
(nombre:'Pleiads';dir:'pleiads';exec:'Tehkan';ciclos:202;extra_param:'1981'),
(nombre:'Mr. Goemon';dir:'mrgoemon';exec:'Konami';ciclos:203;extra_param:'1986'),
(nombre:'Nemesis';dir:'nemesis';exec:'Konami';ciclos:204;extra_param:'1985'),
(nombre:'Twinbee';dir:'twinbee';exec:'Konami';ciclos:205;extra_param:'1985'),
(nombre:'Pirates';dir:'pirates';exec:'NIX';ciclos:206;extra_param:'1994'),
(nombre:'Genix Family';dir:'genix';exec:'NIX';ciclos:207;extra_param:'1994'),
(nombre:'Juno First';dir:'junofrst';exec:'Konami';ciclos:208;extra_param:'1983'),
(nombre:'Gyruss';dir:'gyruss';exec:'Konami';ciclos:209;extra_param:'1983'),
(nombre:'Boogie Wings';dir:'boogwing';exec:'Data East';ciclos:210;extra_param:'1992'),
(nombre:'Free Kick';dir:'freekick';exec:'Nihon System';ciclos:211;extra_param:'1987'),
(nombre:'Pinball Action';dir:'pbaction';exec:'Tehkan';ciclos:212;extra_param:'1985'),
(nombre:'Renegade';dir:'renegade';exec:'Technos Japan';ciclos:213;extra_param:'1986'),
(nombre:'Teenage Mutant Ninja Turtles';dir:'tmnt';exec:'Konami';ciclos:214;extra_param:'1989'),
(nombre:'Sunset Riders';dir:'ssriders';exec:'Konami';ciclos:215;extra_param:'1991'),
(nombre:'Gradius III';dir:'gradius3';exec:'Konami';ciclos:216;extra_param:'1991'),
(nombre:'Space Invaders';dir:'invaders';exec:'Taito';ciclos:217;extra_param:'1978'),
(nombre:'Centipede';dir:'centiped';exec:'Atari';ciclos:218;extra_param:'1980'),
(nombre:'Karnov';dir:'karnov';exec:'Data East';ciclos:219;extra_param:'1987'),
(nombre:'Chelnov';dir:'chelnov';exec:'Data East';ciclos:220;extra_param:'1987'),
(nombre:'Aliens';dir:'aliens';exec:'Konami';ciclos:221;extra_param:'1990'),
(nombre:'Super Contra';dir:'scontra';exec:'Konami';ciclos:222;extra_param:'1988'),
(nombre:'Gang Busters';dir:'gbusters';exec:'Konami';ciclos:223;extra_param:'1988'),
(nombre:'Thunder Cross';dir:'thunderx';exec:'Konami';ciclos:224;extra_param:'1988'),
(nombre:'The Simpsons';dir:'simpsons';exec:'Konami';ciclos:225;extra_param:'1991'),
(nombre:'Track & Field';dir:'trackfld';exec:'Konami';ciclos:226;extra_param:'1983'),
(nombre:'Hyper Sports';dir:'hyperspt';exec:'Konami';ciclos:227;extra_param:'1984'),
(nombre:'Megazone';dir:'megazone';exec:'Konami';ciclos:228;extra_param:'1983'),
(nombre:'Space Fire Bird';dir:'spacefb';exec:'Nintendo';ciclos:229;extra_param:'1980'),
(nombre:'Ajax';dir:'ajax';exec:'Konami';ciclos:230;extra_param:'1987'),
(nombre:'Xevious';dir:'xevious';exec:'Namco';ciclos:231;extra_param:'1982'),
(nombre:'The Combatribes';dir:'ctribe';exec:'Technos';ciclos:232;extra_param:'1990'),
(nombre:'Lunar Lander';dir:'llander';exec:'Atari';ciclos:233;extra_param:'1979'),
(nombre:'Crush Roller';dir:'crush';exec:'Alpha Denshi Co./Kural Samno Electric, Ltd.';ciclos:234;extra_param:'1981'),
(nombre:'Vendetta';dir:'vendetta';exec:'Konami';ciclos:235;extra_param:'1991'),
(nombre:'Gauntlet';dir:'gauntlet';exec:'Atari';ciclos:236;extra_param:'1985'),
(nombre:'Sauro';dir:'sauro';exec:'Tecfri';ciclos:237;extra_param:'1987'),
(nombre:'Crazy Climber';dir:'cclimber';exec:'Nichibutsu';ciclos:238;extra_param:'1980'),
(nombre:'Return of the Invaders';dir:'retofinv';exec:'Taito';ciclos:239;extra_param:'1985'),
(nombre:'Tetris (Atari)';dir:'atetris';exec:'Atari Games';ciclos:240;extra_param:'1988'),
(nombre:'Ikari Warriors';dir:'ikari';exec:'SNK';ciclos:241;extra_param:'1986'),
(nombre:'Athena';dir:'athena';exec:'SNK';ciclos:242;extra_param:'1986'),
(nombre:'T.N.K III';dir:'tnk3';exec:'SNK';ciclos:243;extra_param:'1986'),
(nombre:'Peter Pack Rat';dir:'peterpak';exec:'Atari';ciclos:244;extra_param:'1984'),
(nombre:'Gauntlet II';dir:'gaunt2';exec:'Atari';ciclos:245;extra_param:'1986'),
(nombre:'Defender';dir:'defender';exec:'Williams';ciclos:246;extra_param:'1980'),
(nombre:'Fire Ball';dir:'fball';exec:'FM Works';ciclos:247;extra_param:'1992'),
(nombre:'Mayday';dir:'mayday';exec:'Williams';ciclos:248;extra_param:'1980'),
(nombre:'Colony 7';dir:'colony7';exec:'Williams';ciclos:249;extra_param:'1981'),
(nombre:'Bosconian';dir:'bosco';exec:'Namco';ciclos:250;extra_param:'1981'),
(nombre:'HangOn Jr.';dir:'hangonjr';exec:'Sega';ciclos:251;extra_param:'1985'),
(nombre:'Slap Shooter';dir:'slapshtr';exec:'Sega';ciclos:252;extra_param:'1986'),
(nombre:'Fantasy Zone II: The Tears of Opa-Opa';dir:'fantzn2';exec:'Sega';ciclos:253;extra_param:'1988'),
(nombre:'Opa Opa';dir:'opaopa';exec:'Sega';ciclos:254;extra_param:'1987'),
(nombre:'Tetris (Sega System E)';dir:'tetrisse';exec:'Sega';ciclos:255;extra_param:'1988'),
(nombre:'Transformer';dir:'transfrm';exec:'Sega';ciclos:256;extra_param:'1986'),
(nombre:'Riddle of Pythagoras';dir:'ridleofp';exec:'Sega';ciclos:257;extra_param:'1986'),
(nombre:'Route 16';dir:'route16';exec:'Sun Electronics';ciclos:258;extra_param:'1981'),
(nombre:'Speak & Rescue';dir:'speakres';exec:'Sun Electronics';ciclos:259;extra_param:'1980'),
(nombre:'Galactic Warriors';dir:'gwarrior';exec:'Konami';ciclos:260;extra_param:'1985'),
(nombre:'Salamander';dir:'salamand';exec:'Konami';ciclos:261;extra_param:'1986'),
(nombre:'Bad Lands';dir:'badlands';exec:'Atari';ciclos:262;extra_param:'1989'),
(nombre:'Indiana Jones and the Temple of Doom';dir:'indytemp';exec:'Atari';ciclos:263;extra_param:'1985'),
(nombre:'Marble Madness';dir:'marble';exec:'Atari';ciclos:264;extra_param:'1984'),
(nombre:'Soldier Girl Amazon';dir:'amazon';exec:'Nichibutsu';ciclos:265;extra_param:'1986'),
(nombre:'Cosmo Police Galivan';dir:'galivan';exec:'Nichibutsu';ciclos:266;extra_param:'1985'),
(nombre:'Ufo Robo Dangar';dir:'dangar';exec:'Nichibutsu';ciclos:267;extra_param:'1986'),
(nombre:'Last Duel';dir:'lastduel';exec:'Capcom';ciclos:268;extra_param:'1988'),
(nombre:'Mad Gear';dir:'madgear';exec:'Capcom';ciclos:269;extra_param:'1989'),
(nombre:'Led Storm Rally 2011';dir:'leds2011';exec:'Capcom';ciclos:270;extra_param:'1989'),
(nombre:'Gigas';dir:'gigas';exec:'Sega';ciclos:271;extra_param:'1986'),
(nombre:'Gigas Mark II';dir:'gigasm2';exec:'Sega';ciclos:272;extra_param:'1986'),
(nombre:'Omega';dir:'omega';exec:'Nihon System';ciclos:273;extra_param:'1986'),
(nombre:'Perfect Billard';dir:'pbillrd';exec:'Nihon System';ciclos:274;extra_param:'1987'),
(nombre:'Armed F';dir:'armedf';exec:'Nichibutsu';ciclos:275;extra_param:'1988'),
(nombre:'Terra Force';dir:'terraf';exec:'Nichibutsu';ciclos:276;extra_param:'1987'),
(nombre:'Crazy Climber 2';dir:'cclimbr2';exec:'Nichibutsu';ciclos:277;extra_param:'1988'),
(nombre:'Legion - Spinner-87';dir:'legion';exec:'Nichibutsu';ciclos:278;extra_param:'1987'),
(nombre:'ASO - Armored Scrum Object';dir:'aso';exec:'SNK';ciclos:279;extra_param:'1985'),
(nombre:'Fire Trap';dir:'firetrap';exec:'Woodplace Inc.';ciclos:280;extra_param:'1986'),
(nombre:'3x3 Puzzle';dir:'3x3puzzl';exec:'Ace Enterprise';ciclos:281;extra_param:'1998'),
(nombre:'Casanova';dir:'casanova';exec:'Promat';ciclos:282;extra_param:'199?'),
(nombre:'1945k III';dir:'1945kiii';exec:'Oriental Soft';ciclos:283;extra_param:'2000'),
(nombre:'96 Flag Rally';dir:'flagrall';exec:'Promat';ciclos:284;extra_param:'2000'),
(nombre:'Blood Bros.';dir:'bloodbro';exec:'TAD Corporation';ciclos:285;extra_param:'1990'),
(nombre:'Sky Smasher';dir:'skysmash';exec:'Nihon System';ciclos:286;extra_param:'1990'),
(nombre:'Baraduke';dir:'baraduke';exec:'Namco';ciclos:287;extra_param:'1985'),
(nombre:'Metro-Cross';dir:'metrocrs';exec:'Namco';ciclos:288;extra_param:'1985'),
(nombre:'The Return of Ishtar';dir:'roishtar';exec:'Namco';ciclos:289;extra_param:'1986'),
(nombre:'Genpei ToumaDen';dir:'genpeitd';exec:'Namco';ciclos:290;extra_param:'1986'),
(nombre:'Wonder Momo';dir:'wndrmomo';exec:'Namco';ciclos:291;extra_param:'1987'),
(nombre:'Altered Beast';dir:'altbeast';exec:'Sega';ciclos:292;extra_param:'1988'),
(nombre:'Golden Axe';dir:'goldnaxe';exec:'Sega';ciclos:293;extra_param:'1989'),
(nombre:'Dynamite Dux';dir:'ddux1';exec:'Sega';ciclos:294;extra_param:'1988'),
(nombre:'E-Swat - Cyber Police';dir:'eswat';exec:'Sega';ciclos:295;extra_param:'1989'),
(nombre:'Passing Shot';dir:'passsht';exec:'Sega';ciclos:296;extra_param:'1988'),
(nombre:'Aurail';dir:'aurail';exec:'Sega';ciclos:297;extra_param:'1990'),
(nombre:'Hellfire';dir:'hellfire';exec:'Toaplan';ciclos:298;extra_param:'1989'),
(nombre:'Lock''n''Chase';dir:'lnc';exec:'Deco';ciclos:299;extra_param:'1981'),
(nombre:'Minky Monkey';dir:'mmonkey';exec:'Deco';ciclos:300;extra_param:'1982'),
(nombre:'Karate Champ';dir:'kchamp';exec:'Data East';ciclos:301;extra_param:'1984'),
(nombre:'Thundercade';dir:'tndrcade';exec:'Seta';ciclos:302;extra_param:'1987'),
(nombre:'Twin Eagle - Revenge Joe''s Brother';dir:'twineagl';exec:'Seta';ciclos:303;extra_param:'1988'),
(nombre:'Thunder & Lightning';dir:'thunderl';exec:'Seta';ciclos:304;extra_param:'1990'),
(nombre:'Ms Pac Man Twin';dir:'mspactwin';exec:'Susilu';ciclos:305;extra_param:'1992'),
(nombre:'Extermination';dir:'extrmatn';exec:'Taito';ciclos:306;extra_param:'1987'),
(nombre:'Atomic Robo-kid';dir:'robokid';exec:'UPL';ciclos:307;extra_param:'1988'),
(nombre:'Mr. Do''s Castle';dir:'docastle';exec:'Universal';ciclos:308;extra_param:'1983'),
(nombre:'Do! Run Run';dir:'dorunrun';exec:'Universal';ciclos:309;extra_param:'1984'),
(nombre:'Mr. Do''s Wild Ride';dir:'dowild';exec:'Universal';ciclos:310;extra_param:'1984'),
(nombre:'Jumping Jack';dir:'jjack';exec:'Universal';ciclos:311;extra_param:'1984'),
(nombre:'Kick Rider';dir:'kickridr';exec:'Universal';ciclos:312;extra_param:'1984'),
(nombre:'Indoor Soccer';dir:'idsoccer';exec:'Universal';ciclos:313;extra_param:'1985'),
(nombre:'Crystal Castles';dir:'ccastles';exec:'Atari';ciclos:314;extra_param:'1983'),
(nombre:'Flower';dir:'flower';exec:'Clarue';ciclos:315;extra_param:'1986'),
(nombre:'SlySpy';dir:'slyspy';exec:'Data East';ciclos:316;extra_param:'1989'),
(nombre:'Boulder Dash I-II';dir:'bouldash';exec:'Data East';ciclos:317;extra_param:'1990'),
(nombre:'Super Dodge Ball';dir:'spdodgeb';exec:'Technos';ciclos:318;extra_param:'1987'),
(nombre:'Senjyo';dir:'senjyo';exec:'Tehkan';ciclos:319;extra_param:'1983'),
(nombre:'Baluba-louk no Densetsu';dir:'baluba';exec:'Able Corp, Ltd.';ciclos:320;extra_param:'1986'),
(nombre:'Joust';dir:'joust';exec:'Williams';ciclos:321;extra_param:'1982'),
(nombre:'Robotron';dir:'robotron';exec:'Williams';ciclos:322;extra_param:'1982'),
(nombre:'Stargate';dir:'stargate';exec:'Williams';ciclos:323;extra_param:'1981'),
(nombre:'Tapper';dir:'tapper';exec:'Bally Midway';ciclos:324;extra_param:'1983'),
(nombre:'Arkanoid';dir:'arkanoid';exec:'Taito';ciclos:325;extra_param:'1986'),
(nombre:'Side Arms - Hyper Dyne';dir:'sidearms';exec:'Capcom';ciclos:326;extra_param:'1986'),
(nombre:'The Speed Rumbler';dir:'srumbler';exec:'Capcom';ciclos:327;extra_param:'1986'),
(nombre:'China Gate';dir:'chinagat';exec:'Technos Japan';ciclos:328;extra_param:'1988'),
(nombre:'Mag Max';dir:'magmax';exec:'Nichibutsu';ciclos:329;extra_param:'1985'),
(nombre:'S.R.D. Mission';dir:'srdmissn';exec:'Kyugo/Sega';ciclos:330;extra_param:'1986'),
(nombre:'Airwolf';dir:'airwolf';exec:'Kyugo';ciclos:331;extra_param:'1987'),
(nombre:'Ambush';dir:'ambush';exec:'Tecfri';ciclos:332;extra_param:'1983'),
(nombre:'Super Duck';dir:'supduck';exec:'Comad';ciclos:333;extra_param:'1992'),
(nombre:'Hang-On';dir:'hangon';exec:'Sega';ciclos:334;extra_param:'1985'),
(nombre:'Enduro Racer';dir:'enduror';exec:'Sega';ciclos:335;extra_param:'1986'),
(nombre:'Space Harrier';dir:'sharrier';exec:'Sega';ciclos:336;extra_param:'1985'),
(nombre:'64th Street - A detective story';dir:'64street';exec:'Jaleco';ciclos:337;extra_param:'1991'),
(nombre:'Shadow Warriors';dir:'shadoww';exec:'Tecmo';ciclos:338;extra_param:'1988'),
(nombre:'Wild Fang/Tecmo Knight';dir:'wildfang';exec:'Tecmo';ciclos:339;extra_param:'1989'),
(nombre:'Raiden';dir:'raiden';exec:'Seibu Kaihatsu';ciclos:340;extra_param:'1990'),
(nombre:'Twins';dir:'twins';exec:'Ecogames';ciclos:341;extra_param:'1993'),
(nombre:'Twins (Electronic Devices)';dir:'twinsed1';exec:'Ecogames';ciclos:342;extra_param:'1994'),
(nombre:'Hot Blocks - Tetrix II';dir:'hotblock';exec:'NIX?';ciclos:343;extra_param:'1993'),
(nombre:'Missile Command';dir:'missile';exec:'Atari';ciclos:344;extra_param:'1980'),
(nombre:'Super Missile Attack';dir:'suprmatk';exec:'Atari';ciclos:345;extra_param:'1981'),
(nombre:'Super Zaxxon';dir:'szaxxon';exec:'Sega';ciclos:346;extra_param:'1982'),
(nombre:'Future Spy';dir:'futspy';exec:'Sega';ciclos:347;extra_param:'1984'),
(nombre:'Millipede';dir:'milliped';exec:'Atari';ciclos:348;extra_param:'1982'),
(nombre:'Gaplus';dir:'gaplus';exec:'Namco';ciclos:349;extra_param:'1984'),
(nombre:'Super Xevious';dir:'sxevious';exec:'Namco';ciclos:350;extra_param:'1984'),
(nombre:'Grobda';dir:'grobda';exec:'Namco';ciclos:351;extra_param:'1984'),
(nombre:'Pac & Pal';dir:'pacnpal';exec:'Namco';ciclos:352;extra_param:'1983'),
(nombre:'Birdiy';dir:'birdiy';exec:'Mama Top';ciclos:353;extra_param:'1983'),
(nombre:'Wily Tower';dir:'wilytowr';exec:'Irem';ciclos:354;extra_param:'1984'),
(nombre:'Fighting Basketball';dir:'fghtbskt';exec:'Irem';ciclos:355;extra_param:'1984'),
(nombre:'Diverboy';dir:'diverboy';exec:'Gamart';ciclos:356;extra_param:'1992'),
(nombre:'Mug Smashers';dir:'mugsmash';exec:'Electronic Devices Italy';ciclos:357;extra_param:'1990'),
(nombre:'Steel Force';dir:'stlforce';exec:'Ecogames';ciclos:358;extra_param:'1994'),
(nombre:'Twin Brats';dir:'twinbrat';exec:'Ecogames';ciclos:359;extra_param:'1995'),
(nombre:'Mortal Race';dir:'mortalr';exec:'Ecogames';ciclos:360;extra_param:'1995'),
(nombre:'Bank Panic';dir:'bankp';exec:'Sanritsu/Sega';ciclos:361;extra_param:'1985'),
(nombre:'Combat Hawk';dir:'combh';exec:'Sanritsu/Sega';ciclos:362;extra_param:'1987'),
(nombre:'Ant Eater';dir:'anteater';exec:'Tago Electronics';ciclos:363;extra_param:'1982'),
(nombre:'Appoooh';dir:'appoooh';exec:'Sanritsu/Sega';ciclos:364;extra_param:'1984'),
(nombre:'Robo Wres 2001';dir:'robowres';exec:'Sanritsu/Sega';ciclos:365;extra_param:'1986'),
(nombre:'Armored Car';dir:'armorcar';exec:'Stern Electronics';ciclos:366;extra_param:'1981'),
(nombre:'88 Games';dir:'88games';exec:'Konami';ciclos:367;extra_param:'1988'),
(nombre:'Avengers';dir:'avengers';exec:'Capcom';ciclos:368;extra_param:'1987'),
(nombre:'The End';dir:'theend';exec:'Konami';ciclos:369;extra_param:'1980'),
(nombre:'Battle of Atlantis';dir:'atlantis';exec:'Comsoft';ciclos:370;extra_param:'1981'),
(nombre:'Blue Hawk';dir:'bluehawk';exec:'Dooyong';ciclos:371;extra_param:'1993'),
(nombre:'The Last Day';dir:'lastday';exec:'Dooyong';ciclos:372;extra_param:'1990'),
(nombre:'Gulf Storm';dir:'gulfstrm';exec:'Dooyong';ciclos:373;extra_param:'1991'),
(nombre:'Pollux';dir:'pollux';exec:'Dooyong';ciclos:374;extra_param:'1991'),
(nombre:'Flying Tiger';dir:'flytiger';exec:'Dooyong';ciclos:375;extra_param:'1992'),
(nombre:'Sky Skipper';dir:'skyskipr';exec:'Nintendo';ciclos:376;extra_param:'1981'),
(nombre:'Blue Print';dir:'blueprnt';exec:'Zilec Electronics/Bally Midway';ciclos:377;extra_param:'1982'),
(nombre:'Saturn';dir:'saturnzi';exec:'Zilec Electronics/Jaleco';ciclos:378;extra_param:'1983'),
(nombre:'Grasspin';dir:'grasspin';exec:'Zilec Electronics/Jaleco';ciclos:379;extra_param:'1983'),
(nombre:'BurglarX';dir:'burglarx';exec:'Unico';ciclos:380;extra_param:'1997'),
(nombre:'Zero Point';dir:'zeropnt';exec:'Unico';ciclos:381;extra_param:'1998'),
(nombre:'Calipso';dir:'calipso';exec:'Tago Electronics';ciclos:382;extra_param:'1982'),
(nombre:'Calorie Kun vs Moguranian';dir:'calorie';exec:'Sega';ciclos:383;extra_param:'1986'),
(nombre:'Gardia';dir:'gardia';exec:'Sega';ciclos:384;extra_param:'1986'),
(nombre:'Cavelon';dir:'cavelon';exec:'Jetsoft';ciclos:385;extra_param:'1983'),
(nombre:'Come Back Toto';dir:'toto';exec:'SoftClub';ciclos:386;extra_param:'1996'),
(nombre:'Hyper Pacman';dir:'hyperpac';exec:'SemiCom';ciclos:387;extra_param:'1995'),
(nombre:'KiKi KaiKai';dir:'kikikai';exec:'Taito';ciclos:388;extra_param:'1986'),
(nombre:'Kick and Run';dir:'kicknrun';exec:'Taito';ciclos:389;extra_param:'1986'),
(nombre:'Lasso';dir:'lasso';exec:'SNK';ciclos:390;extra_param:'1982'),
(nombre:'Chameleon';dir:'chameleo';exec:'Jaleco';ciclos:391;extra_param:'1983'),
(nombre:'Last Mission';dir:'lastmisn';exec:'Data East';ciclos:392;extra_param:'1986'),
(nombre:'Shackled';dir:'shackled';exec:'Data East';ciclos:393;extra_param:'1986'),
(nombre:'Gondomania';dir:'gondo';exec:'Data East';ciclos:394;extra_param:'1987'),
(nombre:'Garyo Retsuden';dir:'garyoret';exec:'Data East';ciclos:395;extra_param:'1987'),
(nombre:'Captain Silver';dir:'csilver';exec:'Data East';ciclos:396;extra_param:'1987'),
(nombre:'Cobra-Command';dir:'cobracom';exec:'Data East';ciclos:397;extra_param:'1988'),
(nombre:'The Real Ghostbusters';dir:'ghostb';exec:'Data East';ciclos:398;extra_param:'1987'),
(nombre:'Psycho-Nics Oscar';dir:'oscar';exec:'Data East';ciclos:399;extra_param:'1987'),
(nombre:'Road Fighter';dir:'roadf';exec:'Konami';ciclos:400;extra_param:'1984'),
(nombre:'Ponpoko';dir:'ponpoko';exec:'Sigma';ciclos:401;extra_param:'1982'),
(nombre:'Woodpecker';dir:'woodpeck';exec:'Amenip';ciclos:402;extra_param:'1981'),
(nombre:'Eyes';dir:'eyes';exec:'Techstar';ciclos:403;extra_param:'1982'),
(nombre:'Ali Baba and 40 Thieves';dir:'alibaba';exec:'Sega';ciclos:404;extra_param:'1982'),
(nombre:'Piranha';dir:'piranha';exec:'GL';ciclos:405;extra_param:'1981'),
(nombre:'Final Star Force';dir:'fstarfrc';exec:'Tecmo';ciclos:406;extra_param:'1992'),
(nombre:'Wyvern F-0';dir:'wyvernf0';exec:'Taito';ciclos:407;extra_param:'1985'),
(nombre:'Riot City';dir:'riotcity';exec:'Sega/Westone';ciclos:408;extra_param:'1991'),
(nombre:'SDI - Strategic Defense Initiative';dir:'sdib';exec:'Sega';ciclos:409;extra_param:'1987'),
(nombre:'Cotton';dir:'cotton';exec:'Sega';ciclos:410;extra_param:'1991'),
(nombre:'Discs of Tron';dir:'dotron';exec:'Bally Midway';ciclos:411;extra_param:'1983'),
(nombre:'Tron';dir:'tron';exec:'Bally Midway';ciclos:412;extra_param:'1981'),
(nombre:'Timber';dir:'timber';exec:'Bally Midway';ciclos:413;extra_param:'1984'),
(nombre:'Satan''s Hollow';dir:'shollow';exec:'Bally Midway';ciclos:414;extra_param:'1981'),
(nombre:'Domino Man';dir:'domino';exec:'Bally Midway';ciclos:415;extra_param:'1982'),
(nombre:'Wacko';dir:'wacko';exec:'Bally Midway';ciclos:416;extra_param:'1982'),
(nombre:'Nastar';dir:'nastar';exec:'Taito';ciclos:417;extra_param:'1988'),
(nombre:'Master of Weapon';dir:'masterw';exec:'Taito';ciclos:418;extra_param:'1989'),
(nombre:'NES';dir:'';exec:'Nintendo';ciclos:1000;extra_param:'198X'),
(nombre:'ColecoVision';dir:'coleco';exec:'Coleco';ciclos:1001;extra_param:'1980'),
(nombre:'GameBoy';dir:'gameboy';exec:'Nintendo';ciclos:1002;extra_param:'198X'),
(nombre:'GameBoy Color';dir:'gbcolor';exec:'Nintendo';ciclos:1002;extra_param:'198X'),
(nombre:'CHIP 8';dir:'';exec:'-';ciclos:1003;extra_param:'197X'),
(nombre:'Master System';dir:'sms';exec:'Sega';ciclos:1004;extra_param:'1986'),
(nombre:'SG-1000';dir:'';exec:'Sega';ciclos:1005;extra_param:'1985'),
(nombre:'GameGear';dir:'';exec:'Sega';ciclos:1006;extra_param:'1990'),
(nombre:'Super Cassette Vision';dir:'scv';exec:'Epoch';ciclos:1007;extra_param:'1984'),
(nombre:'Genesis/Megadrive';dir:'';exec:'Sega';ciclos:1008;extra_param:'1988'),
(nombre:'PV-1000';dir:'';exec:'Casio';ciclos:1009;extra_param:'1983'),
(nombre:'PV-2000';dir:'pv2000';exec:'Casio';ciclos:1010;extra_param:'1983'),
(nombre:'Donkey Kong Jr';dir:'gnw_dj101';exec:'Nintendo';ciclos:2000;extra_param:'1983'),
(nombre:'Donkey Kong II';dir:'gnw_jr55';exec:'Nintendo';ciclos:2001;extra_param:'1983'),
(nombre:'Mario Bros';dir:'gnw_mw56';exec:'Nintendo';ciclos:2002;extra_param:'1983')
);

implementation

end.
