unit games_info;

{$ifdef fpc}{$mode delphi}{$H+}{$endif}

interface
uses games_data;

type
  tipo_info=record
    year:string;
    company:string;
    manual:string;
    map:string;
    guia:string;
    image_name:string;
    idioma:integer;
    tipo:integer;
    mensaje:string;
  end;
const
  //Idiomas
  ESP=1;
  ING=2;
  ALE=3;
  FRA=4;
  ITA=5;
  //Tipo Juego
  AG=1;
  ARCADE=2;
  TRESD=4;
  SIMULA=8;
  SPORT=$10;
  PUZ=$20;
  RPG=$40;
  COCHES=$80;
  EXTRA=$200;
  //Mensajes
  GAME_INFO:array[0..(GAME_TOTAL-1)] of tipo_info=(
  (year:'1984';company:'Datasoft Inc.';manual:'brucelee_manual.pdf';image_name:'brucelee';tipo:ARCADE;mensaje:'Al empezar pulsa A para elegir "Composite monitor"[RET]Teclas remapeadas:[RET]Teclas de cursor --> Moverse[RET]CONTROL --> Disparo'),
  (year:'1993';company:'Interplay';manual:'lostvikings_manual.pdf';image_name:'vikings';tipo:ARCADE;mensaje:'Al empezar pulsa ENTER dos/tres veces'),
  (year:'1987';company:'Sierra';manual:'kq1_manual.pdf';map:'kq1\';guia:'kq1_wt_1.txt$kq1_wt_2.html';image_name:'kq1';tipo:AG),
  (manual:'kq2_manual.pdf';map:'kq2\';image_name:'kq2';tipo:AG),
  (manual:'kq3_manual.pdf';map:'kq3_map.gif';image_name:'kq3';tipo:AG),
  (manual:'indyfa_manual_es.pdf$indyfa_Libro de Pistas.pdf$indyfa_comic.pdf';image_name:'indyfa';idioma:ESP;tipo:AG),
  (manual:'indyfa_manual_en.pdf$indyfa_comic.pdf';image_name:'indyfa';idioma:ING;tipo:AG),
  (manual:'indyfa_comic.pdf';image_name:'indyfa';idioma:ALE;tipo:AG),
  (image_name:'3stooges';tipo:ARCADE),
  (image_name:'darkf';idioma:ESP;tipo:TRESD or ARCADE),
  (manual:'alitd1_manual_es.pdf$alitd1_newspaper_es.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:ESP;tipo:AG),
  (manual:'alitd1_manual_en.pdf$alitd1_Newspaper.pdf$alitd1_cluebook.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:ING;tipo:AG),
  (manual:'alitd1_manual.pdf$alitd1_Newspaper.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:ALE;tipo:AG),
  (manual:'alitd1_manual.pdf$alitd1_Newspaper.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:FRA;tipo:AG),
  (manual:'alitd2_manual.pdf';guia:'alitd2_wt.txt';image_name:'alitd2';idioma:ESP;tipo:AG),
  (manual:'amazings_manual.pdf';image_name:'spidey';tipo:ARCADE;mensaje:'Al empezar pulsa 1 para seleccionar VGA'),
  (manual:'outworld_manual.pdf$outworld_refcard.pdf$outworld_Instruction-Booklet.pdf';image_name:'world';tipo:ARCADE or PUZ;mensaje:'Al empezar pulsa 1 para continuar'),
  (image_name:'dn1';tipo:ARCADE),
  (image_name:'dn2';tipo:ARCADE),
  (image_name:'dn3';tipo:ARCADE),
  (image_name:'nukem2';tipo:ARCADE),
  (image_name:'doc';tipo:SIMULA;mensaje:'Al empezar pulsa cualquier tecla para seleccionar 16 colores'),
  (guia:'gobliiins_codes.txt';image_name:'gob';tipo:AG or PUZ;mensaje:'Tras elegir el idioma, pulsa S para validar y pulsa E para elegir sonido SoundBlaster'),
  (image_name:'gob2';idioma:ESP;tipo:AG or PUZ),
  (image_name:'gob2';idioma:ING;tipo:AG or PUZ),
  (image_name:'gob2';idioma:ITA;tipo:AG or PUZ),
  (image_name:'gob2';idioma:ALE;tipo:AG or PUZ),
  (manual:'gods_manual.pdf$gods_card.pdf';map:'gods\';image_name:'gods';tipo:ARCADE),
  (manual:'alleycat_manual.pdf';image_name:'alleycat';tipo:ARCADE),
  (year:'1990';company:'Opera Soft';manual:'rescategolfo_manual.pdf';image_name:'rescate';tipo:ARCADE;mensaje:'Al empezar pulsa F4 para seleccionar VGA[RET]Después pulsa F2 para sonido Adlib'),
  (year:'1987';company:'Sierra';manual:'lsl1_manual.pdf$lsl1_reference_card.pdf';map:'lsl1\';guia:'lsl1_wt.txt';image_name:'lsl1';tipo:AG),
  (image_name:'streetr';tipo:SIMULA or COCHES;mensaje:'Al empezar pulsa 3 para seleccionar VGA'),
  (image_name:'streetr2';tipo:SIMULA or COCHES;mensaje:'Al empezar pulsa 3 para seleccionar VGA[RET]Después pulsa 1 para seleccionar sonido Adlib'),
  (manual:'wrathd_manual_en.pdf$wrathd_manual_multi.pdf';image_name:'wrath';tipo:ARCADE;mensaje:'Al empezar pulsa 3 para seleccionar VGA[RET]Después pulsa 4 para seleccionar sonido Roland'),
  (manual:'speedball_manual.pdf';image_name:'speedb';tipo:SIMULA or SPORT;mensaje:'Cuando pregunte por la tarjeta gráfica, pulsa F2 para seleccionar "EGA 256Kb"'),
  (manual:'pop_manual.pdf$pop_manual_es.pdf';image_name:'prince';tipo:ARCADE),
  (image_name:'osb';tipo:PUZ),
  (image_name:'push';tipo:PUZ),
  (image_name:'rampart';tipo:SIMULA or ARCADE),
  (image_name:'rott';tipo:TRESD or ARCADE),
  (image_name:'riskyw';idioma:ING;tipo:ARCADE),
  (image_name:'warcraft';tipo:SIMULA;mensaje:'Pulsa ENTER para la proteccion y despues selecciona "Save settings and exit"'),
  (image_name:'lhx';tipo:SIMULA),
  (manual:'Loom_manual_es.pdf$Loom_Libro de Pistas.pdf$Loom_El Libro de los Patrones.pdf';guia:'loom.txt';image_name:'loom';idioma:ESP;tipo:AG),
  (manual:'Loom_manual_en.pdf$Loom_Book-of-Patterns.pdf$Loom_Hint book.pdf$Loom_Quick Reference Card.pdf';guia:'loom.txt';image_name:'loom';idioma:ING;tipo:AG),
  (guia:'loom.txt';image_name:'loom';idioma:ALE;tipo:AG),
  (manual:'Loom_manuel_fr.pdf$Loom_Carte de référence.pdf$Loom_Cahier de Trames.pdf$Loom_Livre des astuces.pdf';guia:'loom.txt';image_name:'loom';idioma:FRA;tipo:AG),
  (image_name:'monkey';idioma:ESP;tipo:AG),
  (image_name:'monkey';idioma:ING;tipo:AG),
  (manual:'kq4_manual.pdf';image_name:'kq4';tipo:AG),
  (manual:'lsl6_manual_es.pdf$lsl6_hintbook.pdf$lsl6_RC.pdf';image_name:'lsl6';idioma:ESP;tipo:AG),
  (image_name:'monkey_ega';idioma:ESP;tipo:EXTRA),
  (manual:'polidiaz_manual_1.pdf$polidiaz_manual_2.pdf';image_name:'polidiaz';tipo:SPORT;mensaje:'Al empezar pulsa F4 para seleccionar VGA[RET]Después pulsa F2 para sonido Adlib'),
  (manual:'kq1_manual.pdf';map:'kq1\';guia:'kq1_wt_1.txt$kq1_wt_2.html';image_name:'kq1_cga';tipo:EXTRA),
  (image_name:'archon';tipo:SIMULA),
  (image_name:'archonu';tipo:SIMULA),
  (image_name:'doom';tipo:TRESD or ARCADE),
  (image_name:'doc_cga';tipo:EXTRA),
  (image_name:'doom2';tipo:TRESD or ARCADE),
  (image_name:'heretic';tipo:TRESD or ARCADE),
  (image_name:'raptor';tipo:ARCADE),
  (image_name:'immortal';tipo:RPG),
  (manual:'cruise_manual.pdf';map:'cruise.jpg';image_name:'cruise';idioma:ESP;tipo:AG),
  (image_name:'commando';tipo:ARCADE),
  (manual:'Caveman_manual.pdf';image_name:'caveman';tipo:ARCADE),
{65}  (manual:'uridium_manual.pdf';image_name:'uridium';tipo:ARCADE;mensaje:'Teclas remapeadas:[RET]Teclas de cursor --> Moverse[RET]CONTROL --> Disparo'),
  (manual:'conquest_manual.pdf$conquests_hint book.pdf';map:'conquests of Camelot.jpg';image_name:'camelot';tipo:AG),
  (manual:'dott_manual_es.pdf$dott_Libro de Pistas.pdf$dott_Tarjeta Referencia.pdf';image_name:'dott';idioma:ESP;tipo:AG),
  (manual:'kq5_manual_es.pdf$kq5_Hint Book.pdf';map:'kq5\';image_name:'kq5';idioma:ESP;tipo:AG),
  (image_name:'kq6';idioma:ESP;tipo:AG),
  (manual:'mi2_manual_es.pdf$mi2_Tarjeta de Referencia.pdf';image_name:'monkey2';idioma:ESP;tipo:AG),
  (image_name:'robocop';tipo:ARCADE),
  (image_name:'robocop3';tipo:ARCADE),
  (manual:'kyrandia_manual_es.pdf$kyrandia_Libro de Pistas.pdf';image_name:'kyran';idioma:ESP;tipo:AG),
  (manual:'kyrandia2_manual.pdf';image_name:'hof';idioma:ESP;tipo:AG),
  (manual:'sq1_manual.pdf$sq1_Reference Card.pdf';image_name:'sq1';tipo:AG),
  (manual:'sq1_manual_r_es.pdf$sq1_Hintbook.pdf';image_name:'sq1_vga';idioma:ESP;tipo:AG),
  (manual:'sq1_Hintbook.pdf';image_name:'sq1_ega';idioma:ING;tipo:AG),
  (image_name:'sq2';tipo:AG),
  (image_name:'sq3';tipo:AG),
  (image_name:'vikingc';tipo:ARCADE),
  (manual:'pop2_manual.pdf$pop2_manual_es.pdf';image_name:'prince2';tipo:ARCADE),
  (image_name:'paratrooper';tipo:ARCADE),
{83}  (manual:'lsl2_manual.pdf$lsl2_HintBook.pdf';image_name:'lsl2';tipo:AG;mensaje:'En la protección, el número de teléfono siempre es 7448'),
  (manual:'lsl3_Manual.pdf$lsl3_Postcard.pdf$lsl3_HintBook.pdf';image_name:'lsl3';tipo:AG),
  (image_name:'doh';tipo:ARCADE),
  (manual:'bchess_manual_en.pdf$bchess_manual_fr.pdf';image_name:'bchess_ega';tipo:EXTRA),
  (manual:'bchess_manual_en.pdf$bchess_manual_fr.pdf';image_name:'bchess';tipo:SIMULA or SPORT),
  (image_name:'bchess2';tipo:SIMULA or SPORT),
  (image_name:'bc4000';tipo:SIMULA or SPORT),
  (image_name:'bc4000_low';tipo:EXTRA),
  (manual:'ikariwarriors_manual.pdf$ikariwarriors_manual_alt.pdf';image_name:'ikariw';tipo:ARCADE;mensaje:'Al empezar, pulsa ENTER'),
  (manual:'alitd3_manual.pdf$alitd3_The Mystery Examiner.pdf';image_name:'alitd3';idioma:ESP;tipo:AG),
  (manual:'gob3_manual.pdf$gob3_hint Book.pdf';image_name:'gob3';idioma:ESP;tipo:AG or PUZ),
  (manual:'bargon_manual.pdf';image_name:'bargon';idioma:ESP;tipo:AG;mensaje:'Solo puedes seleccionar el idioma ESPAÑOL! Pulsa D[RET]Despues pulsa S para validar y E para sonido SoundBlaster'),
{95}  (image_name:'bargon';idioma:ING;tipo:AG;mensaje:'You can only select the ENGLISH language! Press C[RET]Then press Y to validate and E for SoundBlaster sound'),
  (image_name:'rastan';tipo:ARCADE),
  (image_name:'karnov';tipo:ARCADE;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (image_name:'goody';tipo:ARCADE),
  (image_name:'tapper';tipo:ARCADE),
  (manual:'living2_manual.pdf';image_name:'lvs2';tipo:ARCADE;mensaje:'Al empezar pulsa F4 para seleccionar VGA'),
  (image_name:'vroad';tipo:ARCADE),
  (manual:'Julius_Erving_and_Larry_Bird_Go_One_on_One_Manual.pdf';image_name:'1on1';tipo:ARCADE),
  (manual:'solnegro_manual.pdf';image_name:'solnegro';tipo:ARCADE;mensaje:'Al empezar pulsa F4 para seleccionar VGA'),
  (manual:'solnegro_manual.pdf';image_name:'solnegro_cga';tipo:EXTRA),
  (image_name:'freddyh';tipo:ARCADE),
  (manual:'fhsm_manual.pdf';image_name:'fhsm';tipo:ARCADE),
  (manual:'lastmission_manual.pdf';image_name:'lmission';tipo:ARCADE),
  (image_name:'im2';tipo:ARCADE),
{109}  (manual:'kq2_manual.pdf';map:'kq2\';image_name:'kq2_b';tipo:EXTRA;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (manual:'kq5_manual_es.pdf$kq5_Hint Book.pdf';map:'kq5\';image_name:'kq5_ega';idioma:ESP;tipo:EXTRA),
  (image_name:'thexder';tipo:ARCADE),
  (image_name:'thexder2';tipo:ARCADE),
{113}  (image_name:'testdrive';tipo:COCHES or SIMULA;mensaje:'Al empezar pulsa 2 para seleccionar EGA'),
  (year:'1987';company:'Opera Soft';manual:'livingstonesupongo_manual.pdf';image_name:'living';tipo:ARCADE),
  (image_name:'ccomic';tipo:ARCADE),
  (image_name:'ccomic2';tipo:ARCADE),
  (image_name:'corsarios';tipo:ARCADE;mensaje:'Al empezar pulsa F3 para seleccionar EGA'),
  (manual:'prehistorik_manual.pdf';image_name:'prehist';tipo:ARCADE),
  (manual:'prehistorik2_manual.pdf';image_name:'prehist2';tipo:ARCADE),
  (image_name:'titusfox';tipo:ARCADE),
  (image_name:'ikari3';tipo:ARCADE),
  (manual:'babyjo_manual.pdf$babyjo_manual_es.pdf';image_name:'babyjo';tipo:ARCADE),
  (image_name:'narcop';tipo:ARCADE),
  (manual:'Emmanuelle_manual_es.pdf';image_name:'emmanuelle';idioma:ESP;tipo:AG),
  (manual:'emmanuelle_claves.pdf';image_name:'emmanuelle';idioma:ING;tipo:AG),
  (manual:'turrican2_manual.pdf';image_name:'turrican2';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (image_name:'ckeen1';tipo:ARCADE),
  (image_name:'ckeen2';tipo:ARCADE),
  (image_name:'ckeen3';tipo:ARCADE),
  (image_name:'ckeen4';tipo:ARCADE),
  (image_name:'ckeen5';tipo:ARCADE),
  (image_name:'ckeen6';tipo:ARCADE),
  (image_name:'kdreams';tipo:ARCADE),
  (manual:'coolcroc_twins_manual.pdf';image_name:'coolcroc';tipo:ARCADE),
  (manual:'coolworld_manual.pdf$coolworld_rc.pdf';image_name:'coolwrld';tipo:ARCADE),
  (manual:'flashback_manual.pdf$flashback_manual_alt.pdf';image_name:'flashback';tipo:ARCADE),
  (manual:'jazzjackrabbit_manual.pdf$jazzjackrabbit_manual_alt.pdf';image_name:'jazzjack';tipo:ARCADE),
  (image_name:'jazzhh';tipo:ARCADE),
  (manual:'la_abadia_del_crimen_manual.pdf';map:'AbadiaDelCrimen.jpg';image_name:'abadia';tipo:ARCADE or PUZ),
  (manual:'aaargh_manual.pdf';image_name:'aaargh';tipo:ARCADE),
  (manual:'budokan_manual.pdf';image_name:'budokan';tipo:SPORT),
  (manual:'bubblebobble_manual.pdf';image_name:'bubble';tipo:ARCADE),
  (manual:'blackthorne_manual.pdf';image_name:'bthorne';tipo:ARCADE),
  (manual:'radwarrior_manual.pdf';image_name:'radwar';tipo:ARCADE),
{145}  (manual:'gng_manual.pdf$gng_RF.pdf';image_name:'gng';tipo:ARCADE;mensaje:'Joystick remapeado a teclado:[RET]A --> Arriba[RET]Z --> Abajo[RET]O --> Izquierda[RET]P --> Derecha[RET]ESPACIO --> Disparo'),
  (image_name:'abreed';tipo:ARCADE),
  (image_name:'ta';tipo:ARCADE),
  (image_name:'abuse';tipo:ARCADE),
  (image_name:'alf';tipo:ARCADE),
  (image_name:'alkatraz';tipo:ARCADE),
  (manual:'kq4_manual.pdf';image_name:'kq4_agi';tipo:EXTRA),
  (manual:'ecoquest_manual.pdf$ecoquest_hintbook.pdf$ecoquest_econoticias.pdf';image_name:'ecoq';idioma:ESP;tipo:AG),
  (manual:'ecoquest2_manual.pdf$ecoquest2_hintbook.pdf$ecoquest2_econews.pdf';image_name:'ecoq2';idioma:ESP;tipo:AG),
{154}  (manual:'goldenaxe_manual.pdf';image_name:'goldaxe';tipo:ARCADE;mensaje:'Al empezar pulsa 4 para seleccionar VGA'),
  (manual:'megaphoenix_manual.pdf';image_name:'mphoenix';tipo:ARCADE),
  (manual:'satan_manual.pdf';image_name:'satan';tipo:ARCADE;mensaje:'Al empezar pulsa 3/4 para seleccionar EGA'),
  (manual:'afterwar_manual.pdf$afterwar_manual_es.pdf';image_name:'afterwar';tipo:ARCADE),
  (manual:'quake_manual.pdf';image_name:'quake';tipo:TRESD),
  (manual:'wolfenstein3d_manual.pdf$wolfenstein3d_HB.pdf';image_name:'wolf3d';tipo:TRESD),
  (manual:'spearofdestiny_manual.pdf$spearofdestiny_HB.pdf';image_name:'spear';tipo:TRESD),
  (manual:'castlewolfenstein_manual.pdf$castlewolfenstein_RC.pdf';image_name:'cw';tipo:ARCADE),
  (manual:'dkong_manual.pdf';image_name:'dkong';tipo:ARCADE),
  (manual:'ddragon_manual.pdf';image_name:'ddragon';tipo:ARCADE;mensaje:'Al empezar pulsa 2 para seleccionar EGA'),
{164}  (manual:'ddragon2_manual.pdf$ddragon2_manual_alt.pdf';image_name:'ddragon2';tipo:ARCADE;mensaje:'Al empezar pulsa 4 para seleccionar VGA'),
  (manual:'dukenukem3D_manual.pdf';image_name:'duke3d';tipo:ARCADE),
  (manual:'lemmings_manual.pdf';image_name:'lemmings';tipo:PUZ),
  (manual:'lemmings2_manual.pdf$lemmings2_story.pdf';image_name:'lemmings2';tipo:PUZ),
  (manual:'mortalkombat_manual.pdf$mortalkombat_comic.pdf';image_name:'mkombat';tipo:ARCADE),
  (manual:'mortalkombat2_manual.pdf$mortalkombat2_comic.pdf';image_name:'mkombat2';tipo:ARCADE),
  (manual:'sf_manual.pdf';image_name:'sf';tipo:ARCADE;mensaje:'Joystick remapeado a teclado:[RET]Teclas de cursor --> Movimiento[RET]Control --> Patada[RET]Alt --> Puño'),
  (manual:'sf2_manual.pdf';image_name:'sf2';tipo:ARCADE),
  (manual:'slugger_manual.pdf';image_name:'slugger';tipo:SPORT),
  (manual:'blackcauldron_manual.pdf$blackcauldron_HB.pdf$blackcauldron_RC.pdf';map:'blackcauldron.jpg';image_name:'bcauld';tipo:AG),
  (manual:'zona0_manual.pdf';image_name:'zona0';tipo:ARCADE;mensaje:'Al empezar pulsa 3 para seleccionar VGA'),
  (manual:'jumpman_manual.pdf';image_name:'jumpman';tipo:ARCADE;mensaje:'Al empezar pulsa C para elegir "Composite monitor"'),
  (image_name:'vct';tipo:ARCADE),
  (image_name:'riskyw';idioma:ESP;tipo:ARCADE),
  (manual:'simant_manual.pdf$simant_startguide.pdf';image_name:'simant';idioma:ESP;tipo:ARCADE),
  (image_name:'ark_cga';tipo:ARCADE),
  (manual:'arkanoid_manual.pdf';image_name:'arkanoid';tipo:ARCADE),
  (manual:'epicpinball_manual.pdf';image_name:'epicpin';tipo:ARCADE),
  (manual:'jill_manual.pdf';image_name:'jill';tipo:ARCADE),
  (image_name:'dd3';tipo:ARCADE;mensaje:'Al empezar pulsa M para seleccionar Roland'),
  (manual:'qg1_manual.pdf$qg1_manual_tech.pdf$qg1_RF.pdf';image_name:'qg1';tipo:RPG),
  (manual:'qg2_manual.pdf$qg2_manual_tech.pdf$qg2_HB.pdf';map:'qg2_map.pdf';image_name:'qg2';tipo:RPG),
  (manual:'qg3_manual.pdf$qg3_tech_manual.pdf$qg3_RF.pdf$qg3_HB.pdf';image_name:'qg3';tipo:RPG),
  (manual:'qg4_manual.pdf$qg4_RF.pdf$qg4_guide.pdf$qg4_HB.pdf';image_name:'qg4';tipo:RPG),
  (manual:'loderunner_manual.pdf';image_name:'loderunn';tipo:ARCADE),
  (manual:'montezumasrevenge_manual.pdf';image_name:'montezum';tipo:ARCADE),
  (manual:'poleposition_manual.pdf';image_name:'polepos';tipo:ARCADE),
  (manual:'chipschallenge_manual.pdf';image_name:'chipsc';tipo:PUZ;mensaje:'Al empezar pulsa 4 (VGA) y A (Roland), despues ENTER'),
  (manual:'mule_manual.pdf';image_name:'mule';tipo:SIMULA),
  (manual:'crazycars_manual.pdf';image_name:'ccars';tipo:COCHES),
  (manual:'luigispaghetti_manual.pdf';image_name:'luigispa';tipo:ARCADE),
  (image_name:'luigi2';tipo:ARCADE),
  (manual:'blackcauldron_manual.pdf$blackcauldron_HB.pdf$blackcauldron_RC.pdf';map:'blackcauldron.jpg';image_name:'bcauld';tipo:AG;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (manual:'MK3_manual.pdf$MK3_guide.pdf';image_name:'mk3';tipo:ARCADE),
  (manual:'Dune2 manual.pdf';image_name:'dune2';tipo:SIMULA),
  (manual:'Indy3_manual.pdf$Indy3_Diario del Grial.pdf$Indy3_Libro de Pistas.pdf';image_name:'indy3';tipo:AG),
  (manual:'Heimdall_manual.pdf';map:'Heimdall_maps.pdf';image_name:'heim';tipo:ARCADE),
  (manual:'tyrian_manual.pdf';image_name:'tyrian';tipo:ARCADE),
  (manual:'eprm_manual.pdf';image_name:'escape';tipo:ARCADE;mensaje:'Pulsa 5 para VGA y luego enter[RET]Teclas de P1 remapeadas[RET]Teclas de cursor --> Moverse[RET]CONTROL --> Disparo'),
  (manual:'simcity_manual.pdf';image_name:'simcity';tipo:SIMULA),
  (manual:'sc2000_manual.pdf$sc2000_RF.pdf';image_name:'sc2000';tipo:SIMULA),
  (manual:'wingcommander_manual.pdf';image_name:'wingcomm';tipo:SIMULA),
  (manual:'wingcommander_manual.pdf';image_name:'wingcomm';tipo:SIMULA),
  (manual:'lotus3_manual.pdf$lotus3_RF.pdf';image_name:'lotus3';tipo:COCHES),
  (manual:'swordsamurai_manual.pdf$swordsamurai_RF.pdf';map:'swordsamurai_map.pdf';image_name:'swordsam';tipo:SIMULA;mensaje:'Tras el joystick selecciona 1 para VGA y después 5 para Roland'),
  (manual:'igor_manual.pdf';image_name:'igor';tipo:AG),
  (year:'1992';company:'Titus France SA';manual:'lac_manual.pdf';image_name:'lac';tipo:COCHES),
  (manual:'populous_manual.pdf$populous_RF.pdf';image_name:'populous';tipo:SIMULA),
  (manual:'supaplex_manual.pdf';image_name:'supaplex';tipo:ARCADE),
  (manual:'crazycars2_manual_ES.pdf$F40_manual.pdf';image_name:'cc2';tipo:COCHES),
  (manual:'crazycars2_manual_ES.pdf$F40_manual.pdf';image_name:'f40ega';tipo:COCHES),
  (manual:'crazycars2_manual_ES.pdf$F40_manual.pdf';image_name:'f40cga';tipo:COCHES),
  (manual:'lotus3_manual.pdf$lotus3_RF.pdf';image_name:'cc3';tipo:COCHES),
  (manual:'lsl1\';image_name:'lsl1_vga';idioma:ING;tipo:AG),
  (manual:'lsl1\';image_name:'lsl1_vga';idioma:ESP;tipo:AG),
  (image_name:'f29';tipo:SIMULA),
  (manual:'baddudes_manual.pdf';image_name:'baddudes';tipo:ARCADE),
  (manual:'karateka_manual.pdf';image_name:'karateka';tipo:ARCADE),
  (manual:'gauntlet_manual.pdf';image_name:'gaunt';tipo:ARCADE),
  (manual:'gauntlet2_manual.pdf';image_name:'gaunt2';tipo:ARCADE),
  (manual:'aladdin_manual.pdf$aladdin_RF.pdf';image_name:'aladdin';tipo:ARCADE),
  (manual:'madmix_manual.pdf';image_name:'madmix';tipo:ARCADE),
  (manual:'madmix2_manual.pdf';image_name:'madmix2';tipo:ARCADE),
  (image_name:'titanic';tipo:ARCADE),
  (manual:'lorna_manual.pdf';image_name:'lorna';tipo:ARCADE),
  (image_name:'rockroll';tipo:ARCADE;mensaje:'Pulsa 2 para seleccionar VGA'),
  (manual:'desperado2_manual.pdf';image_name:'desp2';tipo:ARCADE),
  (manual:'veil_manual.pdf$veil_hints.pdf$veil_RF.pdf';image_name:'veil';tipo:RPG),
  (manual:'magicboy_manual.pdf$magicboy_RF.pdf';image_name:'magicboy';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (manual:'shinobi_manual.pdf';image_name:'shinobi';tipo:ARCADE;mensaje:'Pulsa ENTER para seleccionar EGA'),
  (manual:'dynablaster_manual.pdf$dynablaster_RF.pdf';image_name:'dyna';tipo:ARCADE),
  (manual:'darklands_manual.pdf$darklands_cluebook.pdf$darklands_RF.pdf';map:'darklands_map.pdf';image_name:'darkland';tipo:RPG),
  (image_name:'descent';tipo:ARCADE),
  (image_name:'hhmack';tipo:ARCADE),
  (manual:'ancient_manual.pdf$ancient_RF.pdf';image_name:'warega';tipo:ARCADE),
  (manual:'ancient_manual.pdf$ancient_RF.pdf';image_name:'warcga';tipo:ARCADE),
  (manual:'serenia_manual.pdf';image_name:'serenia';tipo:AG),
  (image_name:'lodecham';tipo:ARCADE),
  (manual:'aliencarnage_manual.pdf';image_name:'aliencar';tipo:ARCADE),
  (manual:'wackywheels_manual.pdf';image_name:'wackyw';tipo:ARCADE),
  (image_name:'wing2';tipo:SIMULA),
  (image_name:'wing2so1';tipo:SIMULA),
  (image_name:'wing2so2';tipo:SIMULA),
  (manual:'pitfall2_manual.pdf';image_name:'pitfall2';tipo:ARCADE),
  (manual:'nebulus_manual.pdf';image_name:'nebulus';tipo:ARCADE),
  (manual:'metalmutant_manual.pdf';image_name:'metal';idioma:ESP;tipo:ARCADE;mensaje:'Pulsa F2 para VGA'),
  (manual:'metalmutant_manual.pdf';image_name:'metal';idioma:ING;tipo:ARCADE;mensaje:'Press F2 for VGA'),
  (manual:'metalmutant_manual.pdf';image_name:'metal';idioma:FRA;tipo:ARCADE;mensaje:'Appuyez sur F2 pour VGA'),
  (manual:'metalgear_manual.pdf';map:'metalgear_map.pdf';image_name:'metalge';tipo:ARCADE;mensaje:'Pulsa ENTER tres veces para empezar'),
  (manual:'macadam_manual.pdf';image_name:'macadam';tipo:ARCADE),
  (manual:'moonwalker_manual.pdf';image_name:'moonwalk';tipo:ARCADE),
  (manual:'netherworld_manual.pdf';image_name:'netherw';tipo:ARCADE),
  (manual:'montyp_manual.pdf';image_name:'montyp';tipo:ARCADE),
  (manual:'neverending2_manual.pdf';image_name:'story2';tipo:ARCADE;mensaje:'Pulsa 3 para seleccionar VGA'),
  (image_name:'nicky2';tipo:ARCADE;mensaje:'Pulsa 1 para empezar'),
  (manual:'nickyboom_manual.pdf';image_name:'nicky';tipo:ARCADE;mensaje:'Pulsa 1 para empezar'),
  (manual:'ninjagaiden_RF.pdf';image_name:'ninjag';tipo:ARCADE;mensaje:'Selecciona graficos EGA y luego ENTER'),
  (image_name:'ninjag2';tipo:ARCADE),
  (manual:'paperboy_manual.pdf';image_name:'paperboy';tipo:ARCADE),
  (manual:'paperboy2_manual.pdf';image_name:'paperboy2';tipo:ARCADE),
  (manual:'renegade_manual.pdf';image_name:'renegade';tipo:ARCADE;mensaje:'Pulsa ENTER dos veces para empezar'),
  (image_name:'ram';tipo:ARCADE),
  (manual:'platoon_manual.pdf';image_name:'platoon';tipo:ARCADE),
  (manual:'obliterator_manual.pdf';image_name:'oblit';tipo:ARCADE;mensaje:'Pulsa 2 y despues N'),
  (manual:'operationwolf_manual.pdf';image_name:'opwolf';tipo:ARCADE),
  (manual:'p47_manual.pdf';image_name:'p47';tipo:ARCADE),
  (manual:'n&s_manual.pdf';image_name:'nands';tipo:SIMULA;mensaje:'Pulsa F1 para empezar'),
  (image_name:'lasth';tipo:ARCADE;mensaje:'Pulsa 1 para empezar'),
  (manual:'lethalweapon_manual.pdf$lethalweapon_RF.pdf';image_name:'lethalw';tipo:ARCADE),
  (manual:'lionking_manual.pdf';image_name:'lionking';tipo:ARCADE),
  (manual:'speedball2_manual.pdf$speedball2_RF.pdf$speedball2_programme.pdf';image_name:'sball2';tipo:ARCADE),
  (manual:'tioacid_manual.pdf';image_name:'toiacid';tipo:ARCADE),
  (image_name:'ajax';tipo:ARCADE),
  (manual:'aliensyndrome_manual.pdf$aliensyndrome_RF.pdf';image_name:'aliensyn';tipo:ARCADE),
  (image_name:'scuba';tipo:ARCADE),
  (manual:'bttf2_manual.pdf';image_name:'bttf2';tipo:ARCADE),
  (manual:'bttf3_manual.pdf$bttf3_manual_es.pdf';image_name:'bttf3';tipo:ARCADE),
  (manual:'artura_RF.pdf';map:'artura_map.pdf';image_name:'artura';tipo:ARCADE),
  (manual:'bioniccommando_manual.pdf';image_name:'bionicc';tipo:ARCADE;mensaje:'Joystick remapeado a teclado:[RET]A --> Arriba[RET]Z --> Abajo[RET]O --> Izquierda[RET]P --> Derecha[RET]ESPACIO --> Disparo'),
  (manual:'bloodmoney_manual.pdf';image_name:'bloodm';tipo:ARCADE),
  (manual:'ulises_manual.pdf';image_name:'ulises';tipo:ARCADE;mensaje:'Pulsa F3 paraseleccionar EGA'),
  (manual:'magicpockets_manual.pdf$magicpockets_story.pdf';image_name:'magicp';tipo:ARCADE),
  (manual:'gameover.pdf';map:'gameover.pdf';image_name:'gameover';tipo:ARCADE),
  (image_name:'armymoves';tipo:ARCADE),
  (manual:'arcticmoves_manual.pdf';image_name:'arcticmoves';tipo:ARCADE),
  (manual:'batmancc_manual.pdf';image_name:'batmancc';tipo:ARCADE),
  (manual:'batmancc_manual.pdf';image_name:'batmancc';tipo:ARCADE),
  (image_name:'batmanm';tipo:ARCADE),
  (image_name:'gameover2';tipo:ARCADE),
  (image_name:'phantis';tipo:ARCADE),
  (manual:'bluesbrothers_manual.pdf$bluesbrothers_ref.pdf';image_name:'bluesbro';tipo:ARCADE),
  (image_name:'bluesjuk';tipo:ARCADE),
  (manual:'afterburnerII_manual.pdf';image_name:'afterb2';tipo:ARCADE;mensaje:'Pulsa 4 para seleccionar Tandy'),
  (manual:'alteredbeast_manual.pdf';image_name:'altbeast';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (manual:'qg1_manual.pdf$qg1_manual_tech.pdf$qg1_RF.pdf';image_name:'qg1_vga';tipo:RPG),
  (manual:'Mundodisco_manual (ES).pdf$Discworld_manual (EN).pdf$Discworld_HB.pdf';image_name:'discw';tipo:ARCADE),
  (manual:'ManiacMansion_ Manual_ES.pdf$ManiacMansion_Claves.pdf$ManiacMansion_Libro _Pistas.pdf';image_name:'maniac';idioma:ESP;tipo:AG),
  (manual:'ManiacMansion_Manual_EN.pdf$ManiacMansion_Claves.pdf$ManiacMansion_Hintbook.pdf';image_name:'maniac';idioma:ING;tipo:AG),
  (manual:'ManiacMansion_old_RF.pdf';image_name:'maniac_old';idioma:ING;tipo:AG)
  );

implementation

end.
