unit games_data;
{$ifdef fpc}{$mode delphi}{$H+}{$endif}

interface
uses main;

type
   tipo_games=record
    nombre:string;
    dir:string;
    exec:string;
    loadfix:boolean;
    params:string;
    exec_pre:string;
    exec_post:string;
    segundo_disco:string;
    tercer_disco:string;
    cuarto_disco:string;
    ciclos:integer;
    grafica:string;
    extra_param:string;
    mapper:string;
    gus:boolean;
    scumm:boolean;
    cdrom:string;
    memoria:integer;
    setup:string;
    refs:array[0..NREFS] of integer;
    motor:byte;
  end;
const
  GAME_TOTAL=727;
  GAME_DATA:array[0..(GAME_TOTAL-1)] of tipo_games=(
  (nombre:'Bruce Lee';dir:'brucelee';exec:'brucelee.img';ciclos:300;grafica:'cga_composite';extra_param:'-set joysticktype=2axis';mapper:'brucelee.map'),
  (nombre:'Lost Vikings, the';dir:'lostv';exec:'vikings.exe';setup:'setup.exe'),
  (nombre:'King''s Quest - Quest for the Crown';dir:'kq1';exec:'sierra.com';ciclos:1000;grafica:'tandy';scumm:true;refs:(7,8,9)),
  (nombre:'King''s Quest II - Romancing the Throne';dir:'kq2';exec:'kq2.com';ciclos:1000;grafica:'tandy';scumm:true;refs:(18,0,0)),
  (nombre:'King''s Quest III - To Heir is Human';dir:'kq3';exec:'sierra.com';ciclos:1000;grafica:'tandy';scumm:true),
  (nombre:'Indiana Jones and the Fate of Atlantis (ES)';dir:'ijfa_es';exec:'atlantis.exe';scumm:true),
  (nombre:'Indiana Jones and the Fate of Atlantis (EN)';dir:'ijfa_en';exec:'atlantis.exe';scumm:true),
  (nombre:'Indiana Jones and the Fate of Atlantis (DE)';dir:'ijfa_de';exec:'atlantis.exe';scumm:true),
  (nombre:'Three Stooges, the';dir:'3stooges';exec:'stooges.exe';grafica:'tandy'),
  (nombre:'Dark Forces (ES)';dir:'darkf_es';exec:'dark.exe';ciclos:1;gus:true;cdrom:'CD\darkforces.iso';memoria:30;setup:'setup.exe'),
  (nombre:'Alone in the Dark (ES)';dir:'alitd_es';exec:'tatou.com'),
  (nombre:'Alone in the Dark (EN)';dir:'alitd_en';exec:'tatou.com'),
  (nombre:'Alone in the Dark (DE)';dir:'alitd_de';exec:'tatou.com'),
  (nombre:'Alone in the Dark (FR)';dir:'alitd_fr';exec:'tatou.com'),
  (nombre:'Alone in the Dark 2 (ES)';dir:'ALID2_ES';exec:'aitd2.exe';exec_pre:'crack.com'),
  (nombre:'Amazing Spiderman, the';dir:'amazings';exec:'spidey.exe'),
  (nombre:'Out of this World';dir:'outworld';exec:'world.exe';setup:'setup.exe'),
  (nombre:'Duke Nukum - Episode One';dir:'duke1';exec:'dn1.exe'),
  (nombre:'Duke Nukum - Episode Two';dir:'duke2';exec:'dn2.exe'),
  (nombre:'Duke Nukum - Episode Three';dir:'duke3';exec:'dn3.exe'),
  (nombre:'Duke Nukem II';dir:'dn2';exec:'nukem2.exe'),
  (nombre:'Defender of the Crown';dir:'doc';exec:'doc.img';grafica:'tandy';refs:(16,0,0)),
  (nombre:'Gobliiins';dir:'goblins';exec:'goblins.exe';ciclos:3000;scumm:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (ES)';dir:'gob2_es';exec:'LOADER.EXE';scumm:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (EN)';dir:'gob2_en';exec:'LOADER.EXE';scumm:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (IT)';dir:'gob2_it';exec:'LOADER.EXE';scumm:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (DE)';dir:'gob2_de';exec:'LOADER.EXE';scumm:true),
  (nombre:'Gods';dir:'gods';exec:'gods.exe';setup:'install.exe'),
  (nombre:'Alley Cat';dir:'alleycat';exec:'alleycat.img';ciclos:450),
  (nombre:'Rescate en el Golfo';dir:'rgolfo';exec:'rgolfo.img'),
  (nombre:'Leisure Suit Larry in the Land of the Lounge Lizards';dir:'lsl1';exec:'sierra.com';grafica:'tandy';scumm:true),
  (nombre:'Street Rod';dir:'streetr';exec:'sr.exe'),
  (nombre:'Street Rod II';dir:'streetr2';exec:'sr.exe'),
  (nombre:'Wrath of the Demon';dir:'wrathd';exec:'wrath.exe'),
  (nombre:'Speed Ball';dir:'spball';exec:'ega.exe';ciclos:1000),
  (nombre:'Prince of Persia';dir:'pop';exec:'prince.exe'),
  (nombre:'One Step Beyond';dir:'osb';exec:'onestep.exe'),
  (nombre:'Push Over';dir:'pushover';exec:'push.exe'),
  (nombre:'Rampart';dir:'rampart';exec:'rampart.exe'),
  (nombre:'Rise of the Triad';dir:'rise';exec:'rott.exe';ciclos:1;gus:true;memoria:30;setup:'setup.exe'),
  (nombre:'Risky Woods (EN)';dir:'risky_en';exec:'risky.exe'),
  (nombre:'WarCraft - Orcs & Humans';dir:'warc';exec:'war.exe';setup:'setup.exe'),
  (nombre:'LHX - Attack Chopper';dir:'lhx';exec:'lhx.exe';params:'vga adlibsound high';ciclos:3000),
  (nombre:'Loom (ES)';dir:'loom_es';exec:'loom.exe';params:'r';scumm:true),
  (nombre:'Loom (EN)';dir:'loom_en';exec:'loom.exe';params:'r';scumm:true),
  (nombre:'Loom (DE)';dir:'loom_de';exec:'loom.exe';params:'r';scumm:true),
  (nombre:'Loom (FR)';dir:'loom_fr';exec:'loom.exe';params:'r';scumm:true),
  (nombre:'Secret of Monkey Island, the (ES)';dir:'mi_v_es';exec:'monkey.exe';params:'r';scumm:true;refs:(11,0,0)),
  (nombre:'Secret of Monkey Island, the (EN)';dir:'mi_v_en';exec:'monkey.exe';params:'r';scumm:true),
  (nombre:'King''s Quest IV - The Perils of Rosella';dir:'kq4';exec:'sierra.exe';scumm:true;setup:'install.exe';refs:(19,0,0)),
  (nombre:'Leisure Suit Larry 6 - Shape Up (ES)';dir:'lsl6_es';exec:'sierra.exe';exec_pre:'LH ULTRAMID -C -M100';ciclos:1;gus:true;scumm:true;setup:'install.exe'),
  (nombre:'Poli Diaz - El Potro de Vallecas';dir:'polidiaz';exec:'polidiaz.img'),
  (nombre:'Archon - The Light and the Dark';dir:'archon';exec:'archon.img';ciclos:450;grafica:'cga_composite'),
  (nombre:'Archon Ultra';dir:'aultra';exec:'archon.exe'),
  (nombre:'Doom - Evil Unleashed';dir:'doom';exec:'doom.exe';exec_pre:'mkdir C:\DOOMDATA[RET]copy default.cfg c:\doomdata';exec_post:'del c:\doomdata /q[RET]rd c:\doomdata';ciclos:1;gus:true;memoria:30;setup:'setup.exe'),
  (nombre:'Doom II - Hell on Earth';dir:'doom2';exec:'doom2.exe';ciclos:1;gus:true;memoria:30;setup:'setup.exe'),
  (nombre:'Heretic, Shadow of the Serpent Riders';dir:'heretic';exec:'heretic.exe';ciclos:1;gus:true;memoria:30;setup:'setup.exe'),
  (nombre:'Raptor - Call of the Shadows';dir:'raptor';exec:'rap.exe';ciclos:1;gus:true;memoria:30;setup:'setup.exe'),
  (nombre:'Immortal, the';dir:'immortal';exec:'immortal.exe';params:'roland'),
  (nombre:'Cruise for a Corpse (ES)';dir:'cruise';exec:'delphine.exe';ciclos:10000;scumm:true;setup:'install.exe'),
  (nombre:'Commando';dir:'commando';exec:'commando.img';ciclos:300;grafica:'cga_composite';mapper:'commando.map'),
  (nombre:'Joe & Mac - Caveman Ninja';dir:'caveman';exec:'caveman.exe';ciclos:20000),
  (nombre:'Uridium';dir:'uridium';exec:'uridium.exe';ciclos:3000;extra_param:'-set joysticktype=2axis';mapper:'uridium.map'),
  (nombre:'Conquests of Camelot - King Arthur the Search for the Grail';dir:'camelot';exec:'sierra.com';scumm:true;setup:'install.exe'),
  (nombre:'Day of the Tentacle (ES)';dir:'dott_es';exec:'tentacle.exe';scumm:true),
  (nombre:'King''s Quest V: Absence Makes the Heart go Yonder (ES)';dir:'kq5_es';exec:'sierra.exe';scumm:true;setup:'install.exe';refs:(17,0,0)),
  (nombre:'King''s Quest VI: Heir Today Gone Tomorrow (ES)';dir:'kq6_es';exec:'sierra.exe';scumm:true;setup:'install.exe'),
  (nombre:'Monkey Island 2 - LeChuck''s Revenge (ES)';dir:'mi2_es';exec:'monkey2.exe';params:'r s';scumm:true),
  (nombre:'Robocop';dir:'robocop';exec:'robocop.exe';grafica:'tandy'),
  (nombre:'Robocop 3';dir:'robo3';exec:'start.exe';params:'start SOUND=R DID=.';ciclos:3000;setup:'setsound.exe'),
  (nombre:'Legend of Kyrandia, the (ES)';dir:'KYRAN_ES';exec:'main.exe';scumm:true;setup:'setup.exe'),
  (nombre:'Legend of Kyrandia, the - The Hand of Fate (ES)';dir:'kyra2_es';exec:'hof.exe';scumm:true;setup:'setup.exe'),
  (nombre:'Space Quest Chapter I - The Sarien Encounter';dir:'sq1';exec:'sierra.com';grafica:'tandy';scumm:true),
  (nombre:'Space Quest Chapter I - The Sarien Encounter (ES Remake)';dir:'sq1_es';exec:'scidhuv.exe';scumm:true;setup:'install.exe'),
  (nombre:'Space Quest Chapter I - The Sarien Encounter (EN Remake)';dir:'sq1_en';exec:'sciduv.exe';scumm:true;setup:'install.exe'),
  (nombre:'Space Quest Chapter II - Vohaul''s Revenge';dir:'sq2';exec:'sierra.com';grafica:'tandy';scumm:true),
  (nombre:'Space Quest Chapter III - The Pirates of Pestulon';dir:'sq3';exec:'sierra.com';scumm:true;setup:'install.exe'),
  (nombre:'Prophecy I - The Viking Child';dir:'vikingc';exec:'vc.exe';ciclos:3000;setup:'install.exe'),
  (nombre:'Prince of Persia II - The Shadow and the Flame';dir:'pop2';exec:'prince.exe';setup:'setup.exe'),
  (nombre:'Paratrooper';dir:'PARATR';exec:'paratr.img';ciclos:450),
  (nombre:'Leisure Suit Larry Looking for Love (in Several Wrong Places)';dir:'lsl2';exec:'sierra.exe';scumm:true;setup:'install.exe'),
  (nombre:'Leisure Suit Larry 3 - Passionate Patti in Pursuit of the Pulsating Pectorals!';dir:'lsl3';exec:'sierra.com';scumm:true;setup:'install.exe'),
  (nombre:'Arkanoid II - The Revenge of Doh';dir:'ARKAN2';exec:'doh.exe';extra_param:'-set a20=off'),
  (nombre:'Battle Chess';dir:'bchess_v';exec:'chess.exe';refs:(4,0,0)),
  (nombre:'Battle Chess II - Chinese Chess';dir:'bchess2';exec:'chess2.exe';setup:'setup.exe'),
  (nombre:'Battle Chess 4000';dir:'bc4k_h';exec:'bc4000.exe';extra_param:'-set core=normal';setup:'setup.exe';refs:(5,0,0)),
  (nombre:'Ikari Warriors';dir:'ikariw';exec:'iw_1.img';segundo_disco:'iw_2.img';ciclos:1000),
  (nombre:'Alone in the Dark 3 (ES)';dir:'ALID3_ES';exec:'aitd3.exe';exec_post:'del c:\fastseek.lut';ciclos:1;cdrom:'CD\aitd3.cue';memoria:30),
  (nombre:'Goblins 3 (ES)';dir:'gob3_es';exec:'gob3.exe';scumm:true;setup:'setup.exe'),
  (nombre:'Bargon Attack (ES)';dir:'batt_es';exec:'loader.exe';scumm:true),
  (nombre:'Bargon Attack (EN)';dir:'batt_en';exec:'loader.exe';scumm:true),
  (nombre:'Rastan';dir:'rastan';exec:'rastan.exe'),
  (nombre:'Karnov';dir:'karnov';exec:'karnov_1.img';segundo_disco:'karnov_2.img';ciclos:1000),
  (nombre:'Goody';dir:'goody';exec:'goody.img';ciclos:300),
  (nombre:'Tapper';dir:'tapper';exec:'tapper.img';ciclos:300;grafica:'cga_composite'),
  (nombre:'Livingstone II';dir:'living2';exec:'lvs2.img'),
  (nombre:'Victory Road';dir:'victoryr';exec:'victoryr.img';ciclos:1000;grafica:'tandy'),
  (nombre:'Julius Erving and Larry Bird Go One on One';dir:'1on1';exec:'1on1.img';ciclos:300;grafica:'pcjr'),
  (nombre:'Sol Negro';dir:'solnegro';exec:'sol.exe';refs:(12,0,0)),
  (nombre:'Freddy Hardest';dir:'freddyh';exec:'freddyh.img';ciclos:1000),
  (nombre:'Freddy Hardest in South Manhattan';dir:'fh_sm';exec:'fh_sm.img';ciclos:750),
  (nombre:'Last Mission, the';dir:'lastmiss';exec:'lastmiss.img';ciclos:300),
  (nombre:'Impossible Mission II';dir:'imiss2';exec:'im2_mcga.exe';ciclos:1000),
  (nombre:'Thexder';dir:'thexder';exec:'thexder.com';grafica:'tandy'),
  (nombre:'Thexder II - Fire Hawk';dir:'thexder2';exec:'sierra.exe';setup:'install.exe'),
  (nombre:'Test Drive';dir:'testdrv';exec:'tdh.exe';loadfix:true;refs:(22,0,0)),
  (nombre:'Livingstone Supongo';dir:'living';exec:'Living.img';ciclos:300),
  (nombre:'Adventures of Captain Comic, the';dir:'ccomic';exec:'comic.exe'),
  (nombre:'Captain Comic II: Fractured Reality';dir:'ccomic2';exec:'fr.exe'),
  (nombre:'Corsarios';dir:'corsario';exec:'corsario.exe'),
  (nombre:'Prehistorik';dir:'prehis1';exec:'historik.exe'),
  (nombre:'Prehistorik 2';dir:'prehis2';exec:'pre2.exe'),
  (nombre:'Titus the Fox - to Marrakech and Back';dir:'titusfox';exec:'fox.exe'),
  (nombre:'Ikari III - The Rescue';dir:'ikariw3';exec:'ikari3.exe'),
  (nombre:'Baby Jo in Going Home';dir:'babyjo';exec:'baby.exe';params:'3';ciclos:3000;refs:(6,0,0)),
  (nombre:'Narco Police';dir:'narcop';exec:'narcop.img'),
  (nombre:'Emmanuelle (ES)';dir:'emma_es';exec:'loader.com';ciclos:3000),
  (nombre:'Emmanuelle (EN)';dir:'emma_en';exec:'emma.com';ciclos:3000),
  (nombre:'Turrican II';dir:'TURRICA2';exec:'t2.exe';exec_pre:'set t2dir=.';gus:true),
  (nombre:'Commander Keen Episode One: Marooned on Mars';dir:'ckeen1';exec:'keen1.exe'),
  (nombre:'Commander Keen Episode Two: The Earth Explodes';dir:'ckeen2';exec:'keen2.exe'),
  (nombre:'Commander Keen Episode Three: Keen Must Die!';dir:'ckeen3';exec:'keen3.exe'),
  (nombre:'Commander Keen Episode IV: Secret of the Oracle';dir:'ckeen4';exec:'keen4e.exe'),
  (nombre:'Commander Keen Episode V: the Armagedon Machine';dir:'ckeen5';exec:'keen5e.exe'),
  (nombre:'Commander Keen in Aliens Ate my Baby Sitter!';dir:'ckeen6';exec:'keen6c.exe'),
  (nombre:'Commander Keen in Keen Dreams';dir:'ckeendrm';exec:'kdreams.exe'),
  (nombre:'Cool Croc Twins';dir:'coolcroc';exec:'start.com';params:'1'),
  (nombre:'Cool World';dir:'coolwrld';exec:'cool.exe'),
  (nombre:'Flash Back';dir:'flashb';exec:'fb.exe';setup:'install.exe'),
  (nombre:'Jazz Jackrabbit';dir:'jazzjack';exec:'jazz.exe';gus:true;setup:'setup.exe'),
  (nombre:'Jazz Jackrabbit Holiday Hare';dir:'jazzhh';exec:'jazz.exe';gus:true;setup:'setup.exe'),
  (nombre:'Abadia del Crimen, la';dir:'abadia';exec:'abadia.img';ciclos:750),
  (nombre:'Aaargh';dir:'aaargh';exec:'aargh.exe';ciclos:1000;grafica:'tandy'),
  (nombre:'Budokan - The Martial Spirit';dir:'budokan';exec:'budo.com';params:'vga mt32 shadowns'),
  (nombre:'Bubble Bobble';dir:'bubble';exec:'bubble.exe';ciclos:3000),
  (nombre:'Blackthorne';dir:'bthorne';exec:'bthorne.exe';exec_pre:'ultramid -f -q[RET]ultramid -c -q';exec_post:'ultramid -f -q';gus:true;memoria:30;setup:'setup.exe'),
  (nombre:'Rad-Warrior';dir:'radwar';exec:'radwar.exe';ciclos:750),
  (nombre:'Ghost''n Goblins';dir:'gng';exec:'gag.exe';ciclos:1000;extra_param:'-set joysticktype=2axis';mapper:'gng.map'),
  (nombre:'Alien Breed';dir:'abreed';exec:'alien.exe';ciclos:6000;setup:'config.exe'),
  (nombre:'Alien Breed - Tower Assault';dir:'abreedta';exec:'ta.exe';ciclos:6000;gus:true;setup:'install.exe'),
  (nombre:'Abuse';dir:'abuse';exec:'abuse.exe';ciclos:1;setup:'setup.exe'),
  (nombre:'Alf - The first adventure';dir:'alf';exec:'alf.exe';ciclos:300),
  (nombre:'Alkatraz';dir:'alkatraz';exec:'alkatraz.exe'),
  (nombre:'EcoQuest 1 - The Search for Cetus (ES)';dir:'ecoq_es';exec:'scidhuv.exe';scumm:true;setup:'install.exe'),
  (nombre:'EcoQuest 2 - El Secreto Perdido de la Selva Amazonica';dir:'ecoq2_es';exec:'sierra.exe';scumm:true;setup:'install.exe'),
  (nombre:'Golden Axe';dir:'goldaxe';exec:'goldaxe.exe'),
  (nombre:'Megaphoenix';dir:'mphoenix';exec:'dinamic.exe'),
  (nombre:'Satan';dir:'satan';exec:'satan.img'),
  (nombre:'After the War';dir:'afterw';exec:'dinamic.com';ciclos:3300),
  (nombre:'Quake';dir:'quake';exec:'quake.exe';ciclos:1;cdrom:'CD\quake.cue';memoria:30),
  (nombre:'Wolfenstein 3-D';dir:'wolf3d';exec:'wolf3d.exe';ciclos:1),
  (nombre:'Wolfenstein 3-D: Spear of Destiny';dir:'w3dspear';exec:'spear.exe';ciclos:1),
  (nombre:'Castle Wolfenstein';dir:'castlew';exec:'cw.exe';ciclos:300;grafica:'cga_composite'),
  (nombre:'Donkey Kong';dir:'donkeyk';exec:'donkeyk.img';ciclos:450),
  (nombre:'Double Dragon';dir:'dd1';exec:'ddmain.exe';exec_pre:'dual.exe[RET]show.exe';ciclos:750),
  (nombre:'Double Dragon II - The Revenge';dir:'dd2';exec:'dragon.exe'),
  (nombre:'Duke Nukem 3D';dir:'duke3d';exec:'duke3d.exe';ciclos:1;gus:true;memoria:30;setup:'setup.exe'),
  (nombre:'Lemmings';dir:'lemmings';exec:'lemvga.com';params:'/v /pc'),
  (nombre:'Lemmings 2 - The Tribes';dir:'lemm2';exec:'l2-fix.com';extra_param:'-set xms=false';setup:'install.exe'),
  (nombre:'Mortal Kombat';dir:'mkombat';exec:'mk.exe';ciclos:1;setup:'setup.exe'),
  (nombre:'Mortal Kombat II';dir:'mkombat2';exec:'mk2.exe';exec_pre:'ultramid.exe -q -c -m100';ciclos:1;gus:true),
  (nombre:'Street Fighter';dir:'sf';exec:'sf.exe';ciclos:1000;extra_param:'-set joysticktype=2axis';mapper:'sf.map'),
  (nombre:'Street Fighter II';dir:'sf2';exec:'sf2.exe'),
  (nombre:'Slugger, the';dir:'slugger';exec:'slugger.img';ciclos:1000),
  (nombre:'Black Cauldron, the';dir:'bcauld';exec:'bc.com';ciclos:1000;grafica:'tandy';scumm:true;refs:(20,0,0)),
  (nombre:'Zona 0';dir:'zona0';exec:'zona0.com'),
  (nombre:'Jumpman';dir:'jumpman';exec:'jumpman.img';ciclos:450;grafica:'cga_composite'),
  (nombre:'Viaje al Centro de la Tierra';dir:'vct';exec:'viaje_d1.img';exec_pre:'imgmount a viaje_d*.img -t floppy[RET]a:[RET]menu.com'),
  (nombre:'Risky Woods (ES)';dir:'risky_es';exec:'risky.exe'),
  (nombre:'SimAnt';dir:'simant';exec:'simant.exe';setup:'install.exe'),
  (nombre:'Arkanoid (CGA)';dir:'arka_cga';exec:'arkanoid.exe';ciclos:750),
  (nombre:'Arkanoid';dir:'arkanoid';exec:'arkanoid.exe';grafica:'tandy'),
  (nombre:'Epic Pinball';dir:'epicpin';exec:'pinball.exe';gus:true;setup:'setup.exe'),
  (nombre:'Jill of the Jungle';dir:'jill';exec:'jill.bat'),
  (nombre:'Double Dragon 3 - The Rosetta Stone';dir:'dd3';exec:'dd3.exe'),
  (nombre:'Quest for Glory I - So you want to be a Hero';dir:'qg1';exec:'sierra.com';scumm:true;setup:'install.exe'),
  (nombre:'Quest for Glory II - Trial by Fire';dir:'qg2';exec:'sierra.com';scumm:true;setup:'install.exe'),
  (nombre:'Quest for Glory III - Wages of War';dir:'qg3';exec:'sierra.exe';scumm:true;setup:'install.exe'),
  (nombre:'Quest for Glory IV - Shadows of Darkness';dir:'qg4';exec:'sierra.exe';scumm:true;setup:'install.exe'),
  (nombre:'Lode Runner';dir:'loderunn';exec:'loderunn.img';ciclos:300;grafica:'cga_composite'),
  (nombre:'Montezuma''s Revenge';dir:'montezum';exec:'montezum.img';ciclos:300;grafica:'pcjr'),
  (nombre:'Pole Position';dir:'polepos';exec:'drive.com';exec_pre:'mount a: [GAME_DIR]';ciclos:450),
  (nombre:'Chips''s Challenge';dir:'chipsc';exec:'chips.exe';ciclos:1500),
  (nombre:'M.U.L.E.';dir:'mule';exec:'mule.img';ciclos:300;grafica:'cga_composite'),
  (nombre:'Crazy Cars';dir:'ccars';exec:'crazycar.exe';ciclos:450;grafica:'cga'),
  (nombre:'Luigi & Spaghetti';dir:'luigispa';exec:'topo.bat'),
  (nombre:'Luigi en Circusland';dir:'luigi2';exec:'luigi2sb.bat'),
  (nombre:'Mortal Kombat 3';dir:'mk3';exec:'mk3.exe';ciclos:1;gus:true;cdrom:'CD\mk3.cue';memoria:30;setup:'setsound.exe'),
  (nombre:'Dune II - La Batalla por Arrakis';dir:'dune2_es';exec:'dune2.exe';ciclos:1),
  (nombre:'Indiana Jones y la Última Cruzada';dir:'indy3_es';exec:'indy3.exe';params:'a v';ciclos:3000;scumm:true),
  (nombre:'Heimdall';dir:'heimdall';exec:'heimdall.exe';ciclos:3000;setup:'setup.exe'),
  (nombre:'Tyrian';dir:'tyrian';exec:'tyrian.exe';ciclos:1;memoria:30;setup:'setup.exe'),
  (nombre:'Escape from the Planet of the Robot Monsters';dir:'escape';exec:'escape.exe';mapper:'escape.map'),
  (nombre:'SimCity';dir:'simcity';exec:'simcity.exe';setup:'settings.exe'),
  (nombre:'SimCity 2000';dir:'sc2000';exec:'sc2000.exe';setup:'install.exe'),
  (nombre:'Wing Commander + Secret Missions';dir:'wingcomm';exec:'wc.exe';ciclos:4500;setup:'install.exe';refs:(2,0,0)),
  (nombre:'Wing Commander Secret Missions 2';dir:'wingcomm';exec:'sm2.exe';ciclos:4500;setup:'install.exe';refs:(2,0,0)),
  (nombre:'Lotus - The Ultimate Challenge';dir:'lotus3';exec:'lotus.exe'),
  (nombre:'Sword of the Samurai';dir:'swordsam';exec:'samurai.com';extra_param:'-set a20=off'),
  (nombre:'Igor: Objetivo Uikokahonia';dir:'igor';exec:'igor.exe';extra_param:'-set "file access tries"=0'),
  (nombre:'Lamborghini - American Challenge';dir:'lac';exec:'lac.exe';ciclos:9600),
  (nombre:'Populous';dir:'populous';exec:'pop.bat'),
  (nombre:'Supaplex';dir:'supaplex';exec:'supaplex.exe'),
  (nombre:'Crazy Cars 2';dir:'ccars2';exec:'cc2ega.exe';ciclos:1500),
  (nombre:'F40 Pursuit Simulator';dir:'f40psega';exec:'f40ptl.exe';ciclos:1500;refs:(15,0,0)),
  (nombre:'Crazy Cars III';dir:'ccars3';exec:'cc3.com'),
  (nombre:'Leisure Suit Larry 1 in the Land of the Lounge Lizards (EN Remake)';dir:'lsl1_en';exec:'scidhuv.exe';ciclos:6000;scumm:true;setup:'install.exe'),
  (nombre:'Leisure Suit Larry 1 in the Land of the Lounge Lizards (ES Remake)';dir:'lsl1_es';exec:'scidhuv.exe';ciclos:6000;scumm:true;setup:'install.exe'),
  (nombre:'F29 Retaliator';dir:'f29retal';exec:'retal.exe';ciclos:1),
  (nombre:'Bad Dudes';dir:'baddudes';exec:'disk01.img';segundo_disco:'disk02.img';ciclos:1000),
  (nombre:'Karateka';dir:'karateka';exec:'karateka.exe';ciclos:450),
  (nombre:'Gauntlet';dir:'gauntlet';exec:'gauntlet.exe';ciclos:1000;grafica:'tandy'),
  (nombre:'Gauntlet II';dir:'gaunt2';exec:'gauntlet.exe';ciclos:1000),
  (nombre:'Aladdin';dir:'aladdin';exec:'aladdin.exe';setup:'SETSND.EXE'),
  (nombre:'MadMix Game';dir:'madmix';exec:'madmix.exe';ciclos:450),
  (nombre:'MadMix 2 en el Castillo de los Fantasmas';dir:'madmix2';exec:'madmix.exe';ciclos:750),
  (nombre:'Titanic';dir:'titanic';exec:'titvga.exe';ciclos:3000;setup:'setup.exe'),
  (nombre:'Lorna';dir:'lorna';exec:'lornaega.com'),
  (nombre:'Rock''n Roller';dir:'rockroll';exec:'rock.exe';exec_pre:'sbfmdrv.com';ciclos:3000),
  (nombre:'Desperado 2';dir:'desp2';exec:'topo.exe'),
  (nombre:'Veil of Darkness';dir:'veildark';exec:'veil.com';setup:'setup.com'),
  (nombre:'Magic Boy';dir:'magicboy';exec:'magicboy.exe'),
  (nombre:'Shinobi';dir:'shinobi';exec:'sh.exe'),
  (nombre:'Dyna Blaster';dir:'dyna';exec:'dyna.exe'),
  (nombre:'Darklands';dir:'darkland';exec:'darkland.exe';setup:'install.exe'),
  (nombre:'Descent';dir:'descent';exec:'descent.bat';params:'-Volume 100';ciclos:1;gus:true;memoria:63;setup:'setup.exe'),
  (nombre:'Hard Hat Mack';dir:'hhmack';exec:'hhmack.img';ciclos:375),
  (nombre:'Ancient Art of War, the';dir:'war_ega';exec:'waret.exe';ciclos:450;refs:(3,0,0)),
  (nombre:'Adventure in Serenia';dir:'serenia';exec:'serenia.img';ciclos:300;grafica:'cga_composite'),
  (nombre:'Championship Lode Runner';dir:'lodecham';exec:'lodecham.img';ciclos:300;grafica:'cga_composite'),
  (nombre:'Alien Carnage';dir:'aliencar';exec:'carnage.exe'),
  (nombre:'Wacky Weels';dir:'wackyw';exec:'ww.exe';ciclos:1;gus:true;setup:'setup.exe'),
  (nombre:'Wing Commander II';dir:'wing2';exec:'wc2.exe';ciclos:4500;setup:'install.exe'),
  (nombre:'Wing Commander II: Special Operations I';dir:'wing2';exec:'so1.exe';ciclos:4500),
  (nombre:'Wing Commander II: Special Operations II';dir:'wing2';exec:'so2.exe';ciclos:4500),
  (nombre:'Pitfall II Lost Caverns (PcJr)';dir:'pitfall2';exec:'pitfall2.jrc';ciclos:300;grafica:'pcjr'),
  (nombre:'Nebulus';dir:'nebulus';exec:'nebega.exe';ciclos:1000),
  (nombre:'Metal Mutant (ES)';dir:'metal_es';exec:'metal.exe'),
  (nombre:'Metal Mutant (EN)';dir:'metal_en';exec:'metal.exe'),
  (nombre:'Metal Mutant (FR)';dir:'metal_fr';exec:'metal.exe'),
  (nombre:'Metal Gear';dir:'metalge';exec:'play.exe';ciclos:3000),
  (nombre:'Macadam Bumper';dir:'macadam';exec:'macadam.exe';exec_pre:'mount d [GAME_DIR][RET]d:';ciclos:750;setup:'install.exe'),
  (nombre:'Moon Walker';dir:'moonwalk';exec:'mw.exe';params:'e';extra_param:'-set a20=off'),
  (nombre:'Nether World';dir:'netherw';exec:'gamee.exe';exec_pre:'screene.com'),
  (nombre:'Monty Python''s Flying Circus';dir:'montyp';exec:'pega.exe'),
  (nombre:'Neverending Story II, the';dir:'never2';exec:'storyii.exe'),
  (nombre:'Nicky II';dir:'nicky2';exec:'n2crk.com';ciclos:2000),
  (nombre:'Nicky Boom';dir:'nicky';exec:'nicky.exe'),
  (nombre:'Ninja Gaiden';dir:'ninjag';exec:'ninja.exe';ciclos:750),
  (nombre:'Ninja Gaiden II - The Dark Sword of Chaos';dir:'ninjag2';exec:'ninja.exe';setup:'njconfig.exe'),
  (nombre:'Paperboy';dir:'paperboy';exec:'papercg2.exe'),
  (nombre:'Paperboy 2';dir:'paperb2';exec:'game.exe';setup:'setup.exe'),
  (nombre:'Renegade';dir:'renegade';exec:'renegade.com';exec_pre:'mount a [GAME_DIR][RET]a:';extra_param:'-set a20=off'),
  (nombre:'R.A.M';dir:'ram';exec:'ram_ega.exe'),
  (nombre:'Platoon';dir:'platoon';exec:'platoon.exe';ciclos:1000),
  (nombre:'Obliterator';dir:'oblitera';exec:'oblit.exe';ciclos:1000;extra_param:'-set a20=off'),
  (nombre:'Operation Wolf';dir:'opwolf';exec:'wolf.exe'),
  (nombre:'P-47 the Freedom Fighter';dir:'p47';exec:'p47.com';ciclos:3000),
  (nombre:'North & South';dir:'nands';exec:'tatou.com';ciclos:3000),
  (nombre:'Last Action Hero';dir:'lasthero';exec:'loader.exe';ciclos:1;setup:'setsound.exe'),
  (nombre:'Lethal Weapon';dir:'lethal';exec:'fixmusic.com'),
  (nombre:'Lion King, the';dir:'lionking';exec:'lionking.exe';gus:true;setup:'install.exe'),
  (nombre:'Speed Ball 2 - Brutal Deluxe';dir:'spball2';exec:'sb2.exe';setup:'setup.com'),
  (nombre:'Toi Acid Game';dir:'toiacid';exec:'toi.exe';ciclos:750),
  (nombre:'Ajax';dir:'ajax';exec:'tdy.exe'),
  (nombre:'Alien Syndrome';dir:'aliensyn';exec:'alien.exe';ciclos:1500),
  (nombre:'ScubaVenture (PcJr)';dir:'scuba';exec:'scubavnt.jrc';ciclos:300;grafica:'pcjr'),
  (nombre:'Back to the Future II';dir:'bttf2';exec:'bttf2.exe'),
  (nombre:'Back to the Future III';dir:'bttf3';exec:'chain.com';params:'v r 5';exec_pre:'mount a: [GAME_DIR][RET]a:[RET]cd future';ciclos:4500),
  (nombre:'Artura';dir:'artura';exec:'artura.exe';ciclos:3000),
  (nombre:'Bionic Comando';dir:'bionicc';exec:'bion.exe';ciclos:1000;extra_param:'-set joysticktype=2axis';mapper:'gng.map'),
  (nombre:'Blood Money';dir:'bloodm';exec:'bm.exe';extra_param:'-set a20=off'),
  (nombre:'Ulises';dir:'ulises';exec:'ulises.exe';ciclos:3000),
  (nombre:'Magic Pockets';dir:'magicp';exec:'pocket_k.exe';setup:'setup.exe'),
  (nombre:'GameOver';dir:'gameover';exec:'gameover.img';ciclos:750),
  (nombre:'Army Moves';dir:'amoves';exec:'amoves.img';ciclos:300),
  (nombre:'Arctic Moves';dir:'arcticm';exec:'arctic.exe';exec_pre:'amfix.com'),
  (nombre:'Batman the Caped Crusader - Joker';dir:'batmancc';exec:'joker.exe';ciclos:3000),
  (nombre:'Batman the Caped Crusader - Penguin';dir:'batmancc';exec:'penguin.exe';ciclos:3000),
  (nombre:'Batman: The Movie';dir:'batmanm';exec:'batman.exe';ciclos:3000),
  (nombre:'GameOver II';dir:'gameovr2';exec:'goverii.bat';ciclos:300),
  (nombre:'Phantis';dir:'phantis';exec:'phantis.exe';ciclos:300),
  (nombre:'Blues Brothers, the';dir:'bluesbro';exec:'vga.exe'),
  (nombre:'Blues Brothers, the: Jukebox Adventure';dir:'bluesjuk';exec:'blues.exe';params:'sb'),
  (nombre:'After Burner II';dir:'AFTERB2';exec:'AB.EXE';grafica:'tandy'),
  (nombre:'Altered Beast';dir:'ABEAST';exec:'BEASTY.EXE'),
  (nombre:'Quest for Glory I - So you want to be a Hero (Remake)';dir:'QG1_VGA';exec:'SCIDHUV.EXE';scumm:true;setup:'install.exe'),
  (nombre:'Discworld/Mundodisco (MULT)';dir:'DISCW';exec:'disc.bat';gus:true;scumm:true;setup:'call config.bat'),
  (nombre:'Maniac Mansion (ES)';dir:'MANIACES';exec:'maniac.exe';params:'p';grafica:'tandy';scumm:true),
  (nombre:'Maniac Mansion (EN)';dir:'MANIACEN';exec:'maniac.exe';params:'p';grafica:'tandy';scumm:true;refs:(24,0,0)),
  (nombre:'Arthur''s Teacher Trouble';dir:'ARTHURTT';motor:MSCUMM),
  (nombre:'Ultimate Doom, the - Thy Flesh Consumed';dir:'ULTDOOM';exec:'doom.exe';ciclos:1;gus:true;memoria:32;setup:'setup.exe'),
  (nombre:'Tortoise and the Hare, the';dir:'TORTOISE';motor:MSCUMM),
  (nombre:'Cannon Fodder';dir:'CANNONF';exec:'can.exe';setup:'install.exe'),
  (nombre:'Cannon Fodder 2 (ES)';dir:'CANNONF2';exec:'cannon.exe';exec_pre:'cd exe[RET]copy cf2_es.exe ..\cannon.exe[RET]cd ..[RET]loadfix -1';setup:'install.exe'),
  (nombre:'Cannon Fodder 2 (EN)';dir:'CANNONF2';exec:'cannon.exe';exec_pre:'loadfix -1';setup:'install.exe'),
  (nombre:'Cannon Fodder 2 (FR)';dir:'CANNONF2';exec:'cannon.exe';exec_pre:'cd exe[RET]copy cf2_fr.exe ..\cannon.exe[RET]cd ..[RET]loadfix -1';setup:'install.exe'),
  (nombre:'Cannon Fodder 2 (IT)';dir:'CANNONF2';exec:'cannon.exe';exec_pre:'cd exe[RET]copy cf2_it.exe ..\cannon.exe[RET]cd ..[RET]loadfix -1';setup:'install.exe'),
  (nombre:'Bram Stoker''s Dracula';dir:'BDRACULA';exec:'dracula.bat'),
  (nombre:'Elvira Mistress of the Dark';dir:'ELVIRA';exec:'elvira.bat';setup:'setup.exe'),
  (nombre:'Elvira II The Jaws of Cerberus (ES)';dir:'CERBE_ES';exec:'cerberus.bat';setup:'setup.exe'),
  (nombre:'Elvira II The Jaws of Cerberus (EN)';dir:'CERBE_EN';exec:'cerberus.bat';setup:'setup.exe'),
  (nombre:'Rampage';dir:'RAMPAGE';exec:'rampage.exe';ciclos:1500),
  (nombre:'Xenon';dir:'XENON';exec:'xenon.exe';ciclos:1500),
  (nombre:'Xenon 2 - Megablast';dir:'XENON2';exec:'xenon2.exe'),
  (nombre:'Space Ace';dir:'SPACEACE';exec:'spaceace.exe'),
  (nombre:'Space Ace: II Borf''s Revenge';dir:'SPACEA2';exec:'sa2.exe'),
  (nombre:'StarQuake';dir:'STARQUAK';exec:'quake.exe';ciclos:750;grafica:'cga'),
  (nombre:'Sirwood';dir:'SIRWOOD';exec:'sirwood.exe';extra_param:'-set a20=off'),
  (nombre:'Mutan Zone';dir:'MUTANZ';exec:'mutan.img';ciclos:450;grafica:'cga'),
  (nombre:'Police Quest II: The Vengeance';dir:'PQ2';exec:'sierra.com';scumm:true),
  (nombre:'Police Quest in Pursuit of the Death Angel';dir:'PQ1';exec:'sierra.com';grafica:'tandy';scumm:true),
  (nombre:'Police Quest in Pursuit of the Death Angel (Remake)';dir:'PQ1_VGA';exec:'SCIDHUV.exe';scumm:true),
  (nombre:'Police Quest III: The Kindred (ES)';dir:'PQ3_ES';exec:'sierra.exe';scumm:true;setup:'install.exe'),
  (nombre:'Police Quest III: The Kindred (EN)';dir:'PQ3_EN_V';exec:'sierra.bat';scumm:true;setup:'install.exe';refs:(21,0,0)),
  (nombre:'Buck Rogers Planet of Zoom';dir:'BUCKROG';exec:'BUCKROG.IMG';ciclos:300;grafica:'pcjr'),
  (nombre:'Congo Bongo';dir:'CONGO';exec:'CONGO.IMG';ciclos:450;grafica:'cga'),
  (nombre:'Digdug';dir:'DIGDUG';exec:'DIGDUG.IMG';ciclos:450),
  (nombre:'Man Hunter: New York';dir:'MH';exec:'sierra.com';scumm:true),
  (nombre:'Man Hunter: San Francisco';dir:'MH2';exec:'sierra.com';scumm:true),
  (nombre:'Dark Side';dir:'DARKSIDE';exec:'darkside.exe';ciclos:1500;extra_param:'-set a20=off'),
  (nombre:'Zool';dir:'ZOOL';exec:'start.exe'),
  (nombre:'Zaxxon';dir:'ZAXXON';exec:'zaxxon.img';ciclos:300;grafica:'cga_composite'),
  (nombre:'Zany Golf';dir:'ZANYGOLF';exec:'tzany.com';params:'m';ciclos:1500;grafica:'tandy'),
  (nombre:'Zool 2';dir:'ZOOL2';exec:'zool2.exe'),
  (nombre:'Test Drive II: The Duel';dir:'TESTDRV2';exec:'td2ega.exe'),
  (nombre:'Test Drive III: The Passion';dir:'TESTDRV3';exec:'tdiii.exe';ciclos:6000;setup:'setup.exe'),
  (nombre:'Knight Games';dir:'KGAMES';exec:'kg.exe'),
  (nombre:'Chichen Itza';dir:'CHICHEN';exec:'ad.com'),
  (nombre:'Cyberbig';dir:'CYBERBIG';exec:'ega.exe';ciclos:750),
  (nombre:'Train, the: Escape to Normady';dir:'ESCTRAIN';exec:'train.exe';ciclos:1500),
  (nombre:'Choy Lee Fut Kung Fu Warrior';dir:'CHOY';exec:'disco.exe';ciclos:450;grafica:'cga'),
  (nombre:'Strider';dir:'STRIDER';exec:'strider.com';ciclos:1500),
  (nombre:'Fallen Angel';dir:'FALLENA';exec:'angel.exe';loadfix:true;ciclos:750;grafica:'cga'),
  (nombre:'Aspar GP Master (ES)';dir:'ASPARGP';exec:'dinamic.bat';ciclos:1500;refs:(10,0,0)),
  (nombre:'Aspar GP Master (EN)';dir:'ASPAREN';exec:'dinamic.bat';ciclos:1500),
  (nombre:'Might and Magic Book One: Secret of the Inner Sanctum';dir:'MANDM1';exec:'mm.exe';ciclos:450),
  (nombre:'Jaws';dir:'JAWS';exec:'jaws.exe';loadfix:true;ciclos:3000),
  (nombre:'Hi-Res Adventure #0: Mission Asteroid';dir:'HIRES_0_APPLE';exec:'Hi-Res Adventure 0 - Mission Asteroid.woz';motor:MAPPLE2),
  (nombre:'Pirates!';dir:'PIRATES_APPLE';exec:'pirates.dsk';motor:MAPPLE2),
  (nombre:'Popeye';dir:'POPEYE_APPLE';exec:'popeye.do';motor:MAPPLE2),
  (nombre:'King''s Quest - Quest for the Crown';dir:'KQ_APPLE';exec:'KQ_1A.nib';segundo_disco:'KQ_1B.nib';motor:MAPPLE2),
  (nombre:'Battle Chess';dir:'BCHESS_APPLE';exec:'BattleChess_A.dsk';segundo_disco:'BattleChess_B.dsk';motor:MAPPLE2),
  (nombre:'Bruce Lee';dir:'BRUCELEE_APPLE';exec:'Bruce Lee.woz';motor:MAPPLE2),
  (nombre:'King''s Quest II - Romancing the Throne';dir:'KQ2_APPLE';exec:'KQ2_1A.dsk';segundo_disco:'KQ2_1B.dsk';motor:MAPPLE2),
  (nombre:'King''s Quest III - To Heir is Human';dir:'KQ3_APPLE';exec:'KQ3_1A.dsk';segundo_disco:'KQ3_1B.dsk';motor:MAPPLE2),
  (nombre:'Super Zaxxon';dir:'SZAXXON_APPLE';exec:'Super Zaxxon.dsk';motor:MAPPLE2),
  (nombre:'Choplifter';dir:'CHOPLIFTER_APPLE';exec:'Choplifter.dsk';motor:MAPPLE2),
  (nombre:'Castle Wolfenstein';dir:'CWOLF_APPLE';exec:'Castle Wolfenstein.woz';motor:MAPPLE2),
  (nombre:'Donkey Kong';dir:'DKONG_APPLE';exec:'DonkeyKong.dsk';motor:MAPPLE2),
  (nombre:'Gremlins';dir:'GREMLINS_APPLE';exec:'Gremlins.woz';motor:MAPPLE2),
  (nombre:'Leisure Suit Larry in the Land of the Lounge Lizards';dir:'LARRY_APPLE';exec:'Larry1_1A.woz';segundo_disco:'Larry1_1B.woz';motor:MAPPLE2),
  (nombre:'Lode Runner';dir:'LODERUN_APPLE';exec:'Lode_Runner.do';motor:MAPPLE2),
  (nombre:'Maniac Mansion';dir:'MMANSION_APPLE';exec:'Maniac Mansion_1A.dsk';segundo_disco:'Maniac Mansion_1B.dsk';motor:MAPPLE2),
  (nombre:'Prince of Persia';dir:'POP_APPLE';exec:'Prince of Persia_A.woz';segundo_disco:'Prince of Persia_B.woz';motor:MAPPLE2),
  (nombre:'Zorro';dir:'ZORRO_APPLE';exec:'zorro.woz';motor:MAPPLE2),
  (nombre:'Alley Cat';dir:'ACAT_A8';exec:'Alley Cat.atr';motor:MATARI8),
  (nombre:'Bruce Lee';dir:'BRUCELEE_A8';exec:'Bruce Lee.atr';motor:MATARI8),
  (nombre:'Prince of Persia';dir:'POP_A8';exec:'Prince of Persia.atr';motor:MATARI8),
  (nombre:'Zorro';dir:'ZORRO_A8';exec:'Zorro.atr';motor:MATARI8),
  (nombre:'Archon - The Light and the Dark';dir:'ARCHON_APPLE';exec:'Archon.woz';motor:MAPPLE2),
  (nombre:'Archon II Adept';dir:'ARCHON2_APPLE';exec:'Archon II - Adept.dsk';motor:MAPPLE2),
  (nombre:'Arkanoid';dir:'ARKANOID_APPLE';exec:'Arkanoid.woz';motor:MAPPLE2),
  (nombre:'Aztec';dir:'AZTEC_APPLE';exec:'Aztec.dsk';motor:MAPPLE2),
  (nombre:'Bolo';dir:'BOLO_APPLE';exec:'Bolo.woz';motor:MAPPLE2),
  (nombre:'Cannonball Blitz';dir:'CANNONB_APPLE';exec:'Cannonball Blitz.dsk';motor:MAPPLE2),
  (nombre:'Captain Goodnight and the Islands of Fear';dir:'CAPTAINGN_APPLE';exec:'Captain Goodnight and the Islands of Fear_A.woz';segundo_disco:'Captain Goodnight and the Islands of Fear_B.woz';motor:MAPPLE2),
  (nombre:'Commando';dir:'COMMANDO_APPLE';exec:'Commando.dsk';motor:MAPPLE2),
  (nombre:'Conan';dir:'CONAN_APPLE';exec:'Conan_A.dsk';segundo_disco:'Conan_B.dsk';motor:MAPPLE2),
  (nombre:'Crossfire';dir:'CROSSFIRE_APPLE';exec:'Crossfire.woz';motor:MAPPLE2),
  (nombre:'Diamond Mine';dir:'DIAMONDMINE_APPLE';exec:'Diamond Mine.woz';motor:MAPPLE2),
  (nombre:'Digdug';dir:'DIGDUG_APPLE';exec:'Dig Dug.woz';motor:MAPPLE2),
  (nombre:'Dino Eggs';dir:'DINOEGGS_APPLE';exec:'Dino Eggs.woz';motor:MAPPLE2),
  (nombre:'Drol';dir:'DROL_APPLE';exec:'Drol.woz';motor:MAPPLE2),
  (nombre:'Dung Beetles';dir:'DUNGBEET_APPLE';exec:'Dung Beetles.woz';motor:MAPPLE2),
  (nombre:'Falcons';dir:'FALCONS_APPLE';exec:'Falcons.woz';motor:MAPPLE2),
  (nombre:'Games, the - Winter Edition';dir:'GAMESWE_APPLE';exec:'The Games - Winter Edition_A1.dsk';segundo_disco:'The Games - Winter Edition_A2.dsk';motor:MAPPLE2),
  (nombre:'Gemstone Warrior';dir:'GEMSTONE_APPLE';exec:'Gemstone Warrior.dsk';motor:MAPPLE2),
  (nombre:'Gemstone Healer';dir:'GEMSTONEH_APPLE';exec:'Gemstone Healer_A.woz';segundo_disco:'Gemstone Healer_B.woz';motor:MAPPLE2),
  (nombre:'Goonies, the';dir:'GOONIES_APPLE';exec:'The Goonies.woz';motor:MAPPLE2),
  (nombre:'Gumball';dir:'GUMBALL_APPLE';exec:'Gumball.woz';motor:MAPPLE2),
  (nombre:'Hard Hat Mack';dir:'HATMACK_APPLE';exec:'Hard Hat Mack.dsk';motor:MAPPLE2),
  (nombre:'Ikari Warriors';dir:'IKARI_APPLE';exec:'Ikari Warriors_A.woz';segundo_disco:'Ikari Warriors_B.woz';motor:MAPPLE2),
  (nombre:'Ikari Warriors II: Victory Road';dir:'IKARI2_APPLE';exec:'Victory Road_A.woz';segundo_disco:'Victory Road_B.woz';motor:MAPPLE2),
  (nombre:'I.O. Silver';dir:'IOSILVER_APPLE';exec:'I.O. Silver.woz';motor:MAPPLE2),
  (nombre:'Karateka';dir:'KARATEKA_APPLE';exec:'Karateka_A.woz';segundo_disco:'Karateka_B.woz';motor:MAPPLE2),
  (nombre:'Mario Bros.';dir:'MARIOBROS_APPLE';exec:'Mario_Bros.do';motor:MAPPLE2),
  (nombre:'Miner 2049er';dir:'MINER_APPLE';exec:'Miner 2049er.woz';motor:MAPPLE2),
  (nombre:'Miner II';dir:'MINER2_APPLE';exec:'Miner II.woz';motor:MAPPLE2),
  (nombre:'Moon Patrol';dir:'MOONPATROL_APPLE';exec:'Moon Patrol.woz';motor:MAPPLE2),
  (nombre:'Montezuma''s Revenge';dir:'MREVENGE_APPLE';exec:'Montezuma''s Revenge.woz';motor:MAPPLE2),
  (nombre:'Mr. Robot and His Robot Factory';dir:'MRROBOT_APPLE';exec:'Mr. Robot and His Robot Factory.dsk';motor:MAPPLE2),
  (nombre:'Ms. Pacman';dir:'MSPACMAN_APPLE';exec:'Ms. Pacman.do';motor:MAPPLE2),
  (nombre:'Oregon Trail, the';dir:'OREGON_APPLE';exec:'The Oregon Trail_A.dsk';segundo_disco:'The Oregon Trail_B.dsk';motor:MAPPLE2),
  (nombre:'Paperboy';dir:'PAPERBOY_APPLE';exec:'Paperboy.dsk';motor:MAPPLE2),
  (nombre:'Pitfall II: Lost Caverns';dir:'PITFALL2_APPLE';exec:'Pitfall II.dsk';motor:MAPPLE2),
  (nombre:'Rampage';dir:'RAMPAGE_A8';exec:'Rampage.atr';motor:MATARI8),
  (nombre:'Renegade';dir:'RENEGADE_APPLE';exec:'Renegade_A.woz';segundo_disco:'Renegade_B.woz';motor:MAPPLE2),
  (nombre:'Robotron 2084';dir:'ROBOTRON_APPLE';exec:'Robotron 2084.dsk';motor:MAPPLE2),
  (nombre:'Rocky Horror Show, the';dir:'ROCKYH_APPLE';exec:'The Rocky Horror Show.dsk';motor:MAPPLE2),
  (nombre:'Rescue Raiders';dir:'RRAIDERS_APPLE';exec:'Rescue Raiders.woz';motor:MAPPLE2),
  (nombre:'Sabotage';dir:'SABOTAGE_APPLE';exec:'Sabotage.woz';motor:MAPPLE2),
  (nombre:'Short Circuit';dir:'SHORTC_APPLE';exec:'Short Circuit.dsk';motor:MAPPLE2),
  (nombre:'Skyfox';dir:'SKYFOX_APPLE';exec:'Skyfox.woz';motor:MAPPLE2),
  (nombre:'Spy Hunter';dir:'SPYHUNTER_APPLE';exec:'Spy Hunter.dsk';motor:MAPPLE2),
  (nombre:'Space Quest Chapter I - The Sarien Encounter';dir:'SQ1_APPLE';exec:'Space Quest I_1A.dsk';segundo_disco:'Space Quest I_1B.dsk';motor:MAPPLE2),
  (nombre:'Space Quest Chapter II - Vohaul''s Revenge';dir:'SQ2_APPLE';exec:'Space Quest II_1A.dsk';segundo_disco:'Space Quest II_1B.dsk';motor:MAPPLE2),
  (nombre:'Star Blazer';dir:'STARBLAZ_APPLE';exec:'Star Blazer.dsk';motor:MAPPLE2),
  (nombre:'Swashbuckler';dir:'SWASHB_APPLE';exec:'Swashbuckler.dsk';motor:MAPPLE2),
  (nombre:'Trolls and Tribulations';dir:'TROLLST_APPLE';exec:'Trolls and Tribulations.dsk';motor:MAPPLE2),
  (nombre:'Wavy Navy';dir:'WAVYNAVY_APPLE';exec:'Wavy Navy.woz';motor:MAPPLE2),
  (nombre:'Winter Games';dir:'WGAMES_APPLE';exec:'Winter Games_A.dsk';segundo_disco:'Winter Games_B.dsk';motor:MAPPLE2),
  (nombre:'Wings of Fury';dir:'WINGSFURY_APPLE';exec:'Wings of Fury_A.woz';segundo_disco:'Wings of Fury_B.woz';motor:MAPPLE2),
  (nombre:'Wizardry - Proving Grounds of the Mad Overlord';dir:'WIZARDRY_APPLE';exec:'Wizardry - Proving Grounds of the Mad Overlord_boot disk.woz';segundo_disco:'Wizardry - Proving Grounds of the Mad Overlord_scenario master disk.woz';motor:MAPPLE2),
  (nombre:'Xevious';dir:'XEVIOUS_APPLE';exec:'Xevious.dsk';motor:MAPPLE2),
  (nombre:'King''s Quest IV - The Perils of Rosella';dir:'KQ4_APPLE';exec:'King''s Quest IV_1A.woz';segundo_disco:'King''s Quest IV_1B.woz';motor:MAPPLE2),
  (nombre:'Dog Daze Deluxe';dir:'DOGDAZE_A8';exec:'Dog Daze Deluxe.atx';motor:MATARI8),
  (nombre:'Archon - The Light and the Dark';dir:'ARCHON_A8';exec:'Archon.atx';motor:MATARI8),
  (nombre:'Chessmaster 2000, the';dir:'CM2000_A8';exec:'Chessmaster 2000.atx';motor:MATARI8),
  (nombre:'Goonies, the';dir:'GOONIES_A8';exec:'Goonies.atx';motor:MATARI8),
  (nombre:'Chessmaster 2000, the';dir:'CM2000_APPLE';exec:'The Chessmaster 2000_A.woz';segundo_disco:'The Chessmaster 2000_B.woz';motor:MAPPLE2),
  (nombre:'Alf - The first adventure';dir:'ALF_APPLE';exec:'Alf.woz';extra_param:'e';motor:MAPPLE2),
  (nombre:'Bad Dudes';dir:'BADDUD_APPLE';exec:'Bad Dudes_A.woz';segundo_disco:'Bad Dudes_B.woz';motor:MAPPLE2),
  (nombre:'Batman - The Caped Crusader';dir:'BATMANCC_APPLE';exec:'Batman_A.woz';segundo_disco:'Batman_B.woz';motor:MAPPLE2),
  (nombre:'Black Cauldron, the';dir:'BLACKC_APPLE';exec:'The Black Cauldron_1A.woz';segundo_disco:'The Black Cauldron_1B.woz';motor:MAPPLE2),
  (nombre:'Legend of Blacksilver, the';dir:'BLACKSILVER_APPLE';exec:'The Legend of Blacksilver_1.woz';segundo_disco:'The Legend of Blacksilver_2.woz';motor:MAPPLE2),
  (nombre:'Buck Rogers - Planet of Zoom';dir:'BUCKR_APPLE';exec:'Buck Rogers - Planet of Zoom.woz';motor:MAPPLE2),
  (nombre:'Congo Bongo';dir:'CONGO_APPLE';exec:'Congo Bongo.woz';motor:MAPPLE2),
  (nombre:'Impossible Mission';dir:'IM_APPLE';exec:'Impossible Mission.woz';motor:MAPPLE2),
  (nombre:'Impossible Mission II';dir:'IM2_APPLE';exec:'Impossible Mission II_A.woz';segundo_disco:'Impossible Mission II_B.woz';motor:MAPPLE2),
  (nombre:'Indiana Jones and the Temple of Doom';dir:'INDYDOOM_APPLE';exec:'Indiana Jones and the Temple of Doom_A.woz';segundo_disco:'Indiana Jones and the Temple of Doom_B.woz';motor:MAPPLE2),
  (nombre:'Mixed-Up Mother Goose';dir:'MIXEDM_APPLE';exec:'Mixed-Up Mother Goose_1A.woz';segundo_disco:'Mixed-Up Mother Goose_1B.woz';motor:MAPPLE2),
  (nombre:'Mr. Do';dir:'MRDO_APPLE';exec:'Mr. Do.dsk';motor:MAPPLE2),
  (nombre:'Neverending Story, the';dir:'NEVERE_APPLE';exec:'The Neverending Story.woz';motor:MAPPLE2),
  (nombre:'Test Drive';dir:'TESTDRIVE_APPLE';exec:'Test Drive_A.woz';segundo_disco:'Test Drive_B.woz';motor:MAPPLE2),
  (nombre:'Thexder';dir:'THEXDER_APPLE';exec:'Thexder.woz';motor:MAPPLE2),
  (nombre:'Beyond Castle Wolfenstein';dir:'BEYONDCW_APPLE';exec:'Beyond Castle Wolfenstein.woz';motor:MAPPLE2),
  (nombre:'Hi-Res Adventure #1: Mystery House';dir:'HIRES_1_APPLE';exec:'Mystery House.dsk';motor:MAPPLE2),
  (nombre:'Stellar 7';dir:'STELLAR7_APPLE';exec:'Stellar 7.woz';motor:MAPPLE2),
  (nombre:'Sundog Frozen Legacy';dir:'SUNDOG_APPLE';exec:'Sundog Frozen Legacy_Play.woz';segundo_disco:'Sundog Frozen Legacy_Utility.woz';motor:MAPPLE2),
  (nombre:'Autoduel';dir:'AUTODUEL_APPLE';exec:'Autoduel_A.woz';segundo_disco:'Autoduel_B.woz';motor:MAPPLE2),
  (nombre:'Top Fuel Eliminator';dir:'ELIMINATOR_APPLE';exec:'Top Fuel Eliminator.woz';motor:MAPPLE2),
  (nombre:'Aquatron';dir:'AQUATRON_APPLE';exec:'Aquatron.woz';motor:MAPPLE2),
  (nombre:'Olympic Decathlon';dir:'ODECATHLON_APPLE';exec:'Olympic Decathlon.woz';motor:MAPPLE2),
  (nombre:'Repton';dir:'REPTON_APPLE';exec:'Repton.woz';motor:MAPPLE2),
  (nombre:'Snack Attack';dir:'SNACKATK_APPLE';exec:'Snack Attack.woz';motor:MAPPLE2),
  (nombre:'Tubeway II';dir:'TUBEWAY2_APPLE';exec:'Tubeway II.woz';motor:MAPPLE2),
  (nombre:'Zenith';dir:'ZENITH_APPLE';exec:'Zenith.woz';motor:MAPPLE2),
  (nombre:'Gauntlet';dir:'GAUNTLET_APPLE';exec:'Gauntlet_A.woz';segundo_disco:'Gauntlet_B.woz';motor:MAPPLE2),
  (nombre:'Donkey Kong Jr.';dir:'DKONGJR_A8';exec:'Donkey Kong Junior.rom';motor:MATARI8),
  (nombre:'Donkey Kong';dir:'DKONG_A8';exec:'Donkey Kong.rom';motor:MATARI8),
  (nombre:'Jumpman Junior';dir:'JUMPMJR_A8';exec:'Jumpman Junior.rom';motor:MATARI8),
  (nombre:'Jungle Hunt';dir:'JUNGLEH_A8';exec:'Jungle Hunt.rom';motor:MATARI8),
  (nombre:'Karateka';dir:'KARATEKA_A8';exec:'Karateka.atx';motor:MATARI8),
  (nombre:'Jumpman';dir:'JUMPMAN_A8';exec:'Jumpman.atx';motor:MATARI8),
  (nombre:'Lode Runner';dir:'LODERUN_A8';exec:'Lode Runner.atx';motor:MATARI8),
  (nombre:'Hard Hat Mack';dir:'HARDHAT_A8';exec:'Hard Hat Mack.atx';motor:MATARI8),
  (nombre:'Gauntlet';dir:'GAUNTLET_A8';exec:'Gauntlet_A.atx';motor:MATARI8),
  (nombre:'Arkanoid';dir:'ARKANOID_A8';exec:'Arkanoid.atr';motor:MATARI8),
  (nombre:'Infiltrator';dir:'INFILTRATOR_A8';exec:'Infiltrator_A.atx';motor:MATARI8),
  (nombre:'Joust';dir:'JOUST_A8';exec:'Joust.rom';motor:MATARI8),
  (nombre:'Pac-man';dir:'PACMAN_A8';exec:'Pac-Man.rom';motor:MATARI8),
  (nombre:'Mr. Robot and His Robot Factory';dir:'MRROBOT_A8';exec:'Mr. Robot and His Robot Factory.atx';motor:MATARI8),
  (nombre:'Pole Position';dir:'POLEPOS_A8';exec:'Pole Position.atx';motor:MATARI8),
  (nombre:'Miner 2049er';dir:'MINER2049_A8';exec:'Miner 2049er.rom';motor:MATARI8),
  (nombre:'MegaMania';dir:'MEGAMANIA_A8';exec:'MegaMania.rom';motor:MATARI8),
  (nombre:'Zak McKracken and the alien mindbenders';dir:'ZAK_EGA';exec:'zak.exe';params:'PREFS';scumm:true;refs:(23,0,0)),
  (nombre:'Storm Lord';dir:'STORMLRD';exec:'stormlrd.com';ciclos:3000),
  (nombre:'Klax';dir:'KLAX';exec:'klax.exe'),
  (nombre:'International Karate';dir:'IKARATE_A8';exec:'International Karate.atr';motor:MATARI8),
  (nombre:'World Karate Championship';dir:'WKARATE_A8';exec:'World Karate Championship.atx';motor:MATARI8),
  (nombre:'Pang';dir:'PANG_A8';exec:'pang.xex';motor:MATARI8),
  (nombre:'Tyrian 2000';dir:'tyrian2k';exec:'tyrian2k.exe';ciclos:1;memoria:30;setup:'setup.exe'),
  (nombre:'Crystal Caves: Vol 1 - Troubles with twibbles';dir:'ccaves';exec:'cc1.exe';ciclos:3000),
  (nombre:'Crystal Caves: Vol 2 - Slugging it out';dir:'ccaves';exec:'cc2.exe';ciclos:3000),
  (nombre:'Crystal Caves: Vol 3 - Mylo versus the supernova';dir:'ccaves';exec:'cc3.exe';ciclos:3000),
  (nombre:'Tristan - Solid state pinball';dir:'tristan';exec:'tristan.exe';setup:'setup.exe'),
  (nombre:'Dangerous Dave';dir:'ddave';exec:'dave.exe'),
  (nombre:'Dangerous Dave in the Haunted Mansion';dir:'ddavehm';exec:'dave2.exe'),
  (nombre:'Dangerous Dave''s Risky Rescue';dir:'ddaverr';exec:'dave.exe'),
  (nombre:'Dangerous Dave Goes Nutz!';dir:'ddavegn';exec:'dave.exe'),
  (nombre:'Dangerous Dave Goes Nutz!';dir:'DDAVEGN_APPLE';exec:'Dangerous Dave Goes Nutz!.dsk';extra_param:'e';motor:MAPPLE2),
  (nombre:'Dangerous Dave in the Deserted Pirate''s Hideout!';dir:'DDAVEPH_APPLE';exec:'Dangerous_Dave_in_the_Deserted_Pirates_Hideout.dsk';motor:MAPPLE2),
  (nombre:'Dangerous Dave in Trophy Trouble';dir:'DDAVETT_APPLE';exec:'Dangerous Dave in Trophy Trouble.dsk';extra_param:'e';motor:MAPPLE2),
  (nombre:'Dangeruos Dave Returns';dir:'DDAVERET_APPLE';exec:'Dangeruos Dave Returns.dsk';extra_param:'e';motor:MAPPLE2),
  (nombre:'Shamus';dir:'SHAMUS';exec:'shamus.img';ciclos:300;grafica:'cga_composite'),
  (nombre:'Shamus';dir:'SHAMUS_APPLE';exec:'shamus.dsk';extra_param:'e';motor:MAPPLE2),
  (nombre:'Shamus';dir:'SHAMUS_A8';exec:'Shamus.atx';extra_param:'osb';motor:MATARI8),
  (nombre:'Shamus Case II';dir:'SHAMUS2_A8';exec:'Shamus Case II.atr';motor:MATARI8),
  (nombre:'Mine Shaft';dir:'MINESHAF';exec:'mineshaf.exe';ciclos:300;grafica:'cga_composite';refs:(13,0,0)),
  (nombre:'Druid';dir:'DRUID_A8';exec:'Druid.atr';motor:MATARI8),
  (nombre:'Head Over Heels';dir:'HOH_A8';exec:'Head over Heels.cas';motor:MATARI8),
  (nombre:'Tapper';dir:'TAPPER_A8';exec:'Tapper.atr';motor:MATARI8),
  (nombre:'F-15 Strike Eagle';dir:'F15';exec:'F-15.img';ciclos:1500;refs:(14,0,0)),
  (nombre:'F-15 Strike Eagle';dir:'F15_A8';exec:'F15.atr';motor:MATARI8),
  (nombre:'F-15 Strike Eagle';dir:'F15_APPLE';exec:'f15.woz';motor:MAPPLE2),
  (nombre:'Outrun';dir:'OUTRUN';exec:'outtdy.exe';ciclos:1500;grafica:'tandy'),
  (nombre:'BlockOut';dir:'BLOCKOUT';exec:'bl.exe';ciclos:1500),
  (nombre:'F-15 Strike Eagle II';dir:'F15SE2';exec:'f15v3.com';loadfix:true;ciclos:6000),
  (nombre:'Mach 3';dir:'MACH3';exec:'mach3.exe';ciclos:450),
  (nombre:'Cycles, the';dir:'CYCLES';exec:'gpega.exe';params:'n ADLIB';ciclos:1500),
  (nombre:'Rick Dangerous';dir:'RICK';exec:'tan.com';ciclos:1000;grafica:'tandy'),
  (nombre:'Rick Dangerous II';dir:'RICK2';exec:'rick2.exe';exec_pre:'sb-sound.com'),
  (nombre:'Colorado (EN/DE)';dir:'COLORADO';exec:'colorado.exe'),
  (nombre:'Colorado (ES)';dir:'COLOR_ES';exec:'colorado.exe'),
  (nombre:'Hocus Pocus';dir:'HOCUSP';exec:'__hpgrvs.exe';exec_pre:'ultramid -q';exec_post:'ultramid -q -f';ciclos:1;gus:true;setup:'setup.exe'),
  (nombre:'Terminator 2 - Judgment Day';dir:'T2';exec:'term.exe';ciclos:3000),
  (nombre:'Terminator 2 - Judgment Day - Chess Wars';dir:'T2CHESS';exec:'t2.exe';setup:'install.exe'),
  (nombre:'Ivan Stewart''s Ironman Super Off Road';dir:'IRONMAN';exec:'game.exe';params:'/vga'),
  (nombre:'Simpsons, the';dir:'SIMPSONS';exec:'simpsons.bat'),
  (nombre:'Pharaoh''s Revenge';dir:'PHARAOHR_APPLE';exec:'Pharaoh''s Revenge side B (boot).woz';segundo_disco:'Pharaoh''s Revenge side A.woz';motor:MAPPLE2),
  (nombre:'Simpsons, the: Bart vs. the Space Mutants';dir:'SBARTVS';exec:'simpsons.bat'),
  (nombre:'Simpsons, the: Bart Simpson''s House of Weirdness';dir:'BARTHW';exec:'s.bat';setup:'setup.exe'),
  (nombre:'Kings of the Beach - Professional Beach Volleyball';dir:'KINGB';exec:'vball.exe';ciclos:3000;grafica:'tandy'),
  (nombre:'Turbo Outrun';dir:'TOUTRUN';exec:'trout.com'),
  (nombre:'Marble Madness';dir:'MARBLEM';exec:'disk1.img';segundo_disco:'disk2.img';ciclos:450),
  (nombre:'Pinball Dreams Deluxe';dir:'PINBALLD';exec:'PINBALLD';exec_pre:'xcopy [GAME_INT]\deluxe\*.* c:\deluxe\ /Y[RET]d:[RET]cd deluxe[RET]ddpcmain[RET]cd \[RET]del c:\deluxe /Q[RET]rmdir c:\deluxe';ciclos:1;cdrom:'CD\pinballd.cue'),
  (nombre:'Dark Forces (EN)';dir:'darkf';exec:'dark.exe';ciclos:1;gus:true;cdrom:'CD\darkf.iso';memoria:30;setup:'setup.exe'),
  (nombre:'Skweek (FR)';dir:'SKWEEK';exec:'skweek.exe'),
  (nombre:'Fowl Play';dir:'FOWLPLAY';exec:'fowlplay.exe';ciclos:450),
  (nombre:'Panza Kick Boxing';dir:'PANZA';exec:'kick.exe'),
  (nombre:'Ishar: Legend of the fortress';dir:'ISHAR';exec:'start.exe';ciclos:6000),
  (nombre:'MadTV';dir:'MADTV';exec:'mtv.exe';ciclos:6000),
  (nombre:'Leisure Suit Larry 6 - Shape Up (EN)';dir:'lsl6_en';exec:'sierra.exe';exec_pre:'LH ULTRAMID -C -M100';ciclos:1;gus:true;scumm:true;setup:'install.exe'),
  (nombre:'Leisure Suit Larry 5 - Passionate Patti Does a Little Undercover Work (ES)';dir:'lsl5_es';exec:'SCIDHUV.EXE';ciclos:1;scumm:true;setup:'install.exe'),
  (nombre:'Leisure Suit Larry 5 - Passionate Patti Does a Little Undercover Work (EN)';dir:'lsl5_en';exec:'SCIDHUV.EXE';ciclos:1;scumm:true;setup:'install.exe'),
  (nombre:'Ghost''n Goblins';dir:'GNG_AMIGA';exec:'Ghosts''n Goblins.ipf';motor:MAMIGA),
  (nombre:'Savage';dir:'SAVAGE_AMIGA';exec:'Savage_1.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Ghouls ''n Ghosts';dir:'GNG2_AMIGA';exec:'Ghouls ''n Ghosts_A.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'After the War';dir:'AFTERWAR_AMIGA';exec:'After the War.ipf';loadfix:true;motor:MAMIGA),
  (nombre:'Nebulus';dir:'NEBULUS_AMIGA';exec:'Nebulus.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Rainbow Islands';dir:'RISLANDS_AMIGA';exec:'RainbowIslands.ipf';motor:MAMIGA),
  (nombre:'Speed Ball 2 - Brutal Deluxe';dir:'SBALL2_AMIGA';exec:'Speedball2.ipf';motor:MAMIGA),
  (nombre:'Sentinel, the';dir:'SENTINEL_AMIGA';exec:'The Sentinel.ipf';motor:MAMIGA),
  (nombre:'Space Quest Chapter I - The Sarien Encounter';dir:'SQ_AMIGA';exec:'Space Quest.adf';exec_pre:'kbd1';motor:MAMIGA),
  (nombre:'Leisure Suit Larry in the Land of the Lounge Lizards';dir:'LARRY1_AMIGA';exec:'Leisure Suit Larry.adf';exec_pre:'kbd1';motor:MAMIGA),
  (nombre:'Beach Volley';dir:'BEACHV_AMIGA';exec:'BeachVolley.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Banshee';dir:'BANSHEE_AMIGA';exec:'banshee.vhd';params:'32,1,2,512,6,,uae0';segundo_disco:'Banshee_Disk1.ipf';ciclos:200;grafica:'aga';motor:MAMIGA),
  (nombre:'Space Quest III - The Pirates of Pestulon';dir:'SQ3_AMIGA';exec:'sq3.vhd';params:'32,1,2,512,0';exec_pre:'kbd1';grafica:'aga';motor:MAMIGA),
  (nombre:'Hammer Boy';dir:'HAMMERBOY_AMIGA';exec:'HammerBoy.ipf';loadfix:true;motor:MAMIGA),
  (nombre:'Grand Prix Master';dir:'ASPAR_AMIGA';exec:'GrandPrixMaster.ipf';loadfix:true;motor:MAMIGA),
  (nombre:'Lotus Esprit Turbo Challenge';dir:'LOTUS_AMIGA';exec:'LotusEspritTurboChallenge.ipf';motor:MAMIGA),
  (nombre:'Lotus Turbo Challenge 2';dir:'LOTUS2_AMIGA';exec:'LotusTurboChallenge2.adf';motor:MAMIGA),
  (nombre:'Lotus III: The Ultimate Challenge';dir:'LOTUS3_AMIGA';exec:'LotusIII_Disk1.adf';motor:MAMIGA),
  (nombre:'Turrican';dir:'TURRICAN_AMIGA';exec:'Turrican.ipf';motor:MAMIGA),
  (nombre:'Turrican II';dir:'TURRICAN2_AMIGA';exec:'Turrican2.ipf';motor:MAMIGA),
  (nombre:'Turrican 3';dir:'TURRICAN3_AMIGA';exec:'Turrican3.ipf';motor:MAMIGA),
  (nombre:'Hunter';dir:'HUNTER_AMIGA';exec:'Hunter.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Pang';dir:'PANG_AMIGA';exec:'Pang.ipf';motor:MAMIGA),
  (nombre:'Blood Money';dir:'BLOODM_AMIGA';exec:'BloodMoney_Disk1.ipf';motor:MAMIGA),
  (nombre:'Bubble Bobble';dir:'BUBBLEB_AMIGA';exec:'BubbleBobble.ipf';motor:MAMIGA),
  (nombre:'Cabal';dir:'CABAL_AMIGA';exec:'Cabal.ipf';motor:MAMIGA),
  (nombre:'Deflektor';dir:'DEFLEKTOR_AMIGA';exec:'Deflektor.ipf';motor:MAMIGA),
  (nombre:'Dungeon Master';dir:'DMASTER_AMIGA';exec:'DungeonMaster.ipf';exec_pre:'kbd1';grafica:'aga';motor:MAMIGA),
  (nombre:'Defender of the Crown';dir:'DOC_AMIGA';exec:'DefenderOfTheCrown_Disk1.ipf';segundo_disco:'DefenderOfTheCrown_Disk2.ipf';motor:MAMIGA),
  (nombre:'Three Stooges, the';dir:'THREES_AMIGA';exec:'ThreeStooges_Disk1.ipf';segundo_disco:'ThreeStooges_Disk2.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Batman the Movie';dir:'BATMANM_AMIGA';exec:'BatmanTheMovie.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Chaos Engine, the';dir:'CHAOSENGINE_AMIGA';exec:'ChaosEngine_Disk1.ipf';segundo_disco:'ChaosEngine_Disk2.ipf';grafica:'aga';motor:MAMIGA),
  (nombre:'Chaos Engine 2, the';dir:'CHAOSE2_AMIGA';exec:'ChaosEngine2_Disk1.ipf';segundo_disco:'ChaosEngine2_Disk2.ipf';ciclos:200;grafica:'aga';motor:MAMIGA),
  (nombre:'Chuck Rock';dir:'CHUCKROCK_AMIGA';exec:'ChuckRock_Disk1.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Chuck Rock 2, Son of Chuck';dir:'CHUCKROCK2_AMIGA';exec:'ChuckRock2_Disk1.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Dogs of War';dir:'DOGSWAR_AMIGA';exec:'DogsOfWar.ipf';motor:MAMIGA),
  (nombre:'Grand Monster Slam';dir:'GMONSTERS_AMIGA';exec:'GrandMonsterSlam.ipf';motor:MAMIGA),
  (nombre:'Great Giana Sisters, the';dir:'GREATGIANA_AMIGA';exec:'GreatGianaSisters.ipf';motor:MAMIGA),
  (nombre:'Hostages';dir:'HOSTAGES_AMIGA';exec:'Hostages.ipf';motor:MAMIGA),
  (nombre:'Hybris';dir:'HYBRIS_AMIGA';exec:'Hybris.ipf';motor:MAMIGA),
  (nombre:'IK+';dir:'IKPLUS_AMIGA';exec:'IK+.ipf';motor:MAMIGA),
  (nombre:'Mach 3';dir:'MACH3_AMIGA';exec:'Mach3.ipf';motor:MAMIGA),
  (nombre:'Menace';dir:'MENACE_AMIGA';exec:'Menace.ipf';motor:MAMIGA),
  (nombre:'Navy Moves';dir:'NAVYMOVES_AMIGA';exec:'NavyMoves.ipf';loadfix:true;motor:MAMIGA),
  (nombre:'Prehistorik';dir:'PREHISTORIK_AMIGA';exec:'Prehistorik.ipf';motor:MAMIGA),
  (nombre:'Renegade';dir:'RENEGADE_AMIGA';exec:'Renegade.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Rick Dangerous';dir:'RICKD_AMIGA';exec:'RickDangerous.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Secret of Monkey Island, the (ES)';dir:'MONKEY_ES_AMIGA';exec:'monkey.vhd';params:'32,1,2,512,0';motor:MAMIGA),
  (nombre:'Rick Dangerous II';dir:'RICKD2_AMIGA';exec:'RickDangerous2.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Shufflepuck Cafe';dir:'SHUFFLEP_AMIGA';exec:'ShufflepuckCafe.ipf';motor:MAMIGA),
  (nombre:'Silkworm';dir:'SILKWORM_AMIGA';exec:'Silkworm.ipf';motor:MAMIGA),
  (nombre:'Battle Chess';dir:'BCHESS_AMIGA';exec:'bchess.vhd';params:'32,1,2,512,0';motor:MAMIGA),
  (nombre:'Budokan - The Martial Spirit';dir:'BUDOKAN_AMIGA';exec:'Budokan_disk1.adf';segundo_disco:'Budokan_disk2.adf';motor:MAMIGA),
  (nombre:'Grand Prix Circuit';dir:'GPCIRCUIT_AMIGA';exec:'GrandPrixCircuit.ipf';motor:MAMIGA),
  (nombre:'Hudson Hawk';dir:'HUDSONH_AMIGA';exec:'HudsonHawk.ipf';motor:MAMIGA),
  (nombre:'Jaguar XJ220';dir:'JAGUAR_AMIGA';exec:'Jaguar XJ220_disk1.adf';segundo_disco:'Jaguar XJ220_disk2.adf';motor:MAMIGA),
  (nombre:'James Pond - Underwater Agent';dir:'JPOND_AMIGA';exec:'JamesPond-UnderwaterAgent.ipf';motor:MAMIGA),
  (nombre:'James Pond II - Codename RoboCod';dir:'JPOND2_AMIGA';exec:'JamesPondII-CodenameRoboCod.ipf';motor:MAMIGA),
  (nombre:'Ninja Remix';dir:'NINJAREMIX_AMIGA';exec:'NinjaRemix_DiskA.ipf';motor:MAMIGA),
  (nombre:'Pinball Dreams';dir:'PDREAMS_AMIGA';exec:'PinballDreams_Disk1.ipf';exec_pre:'kbd1';segundo_disco:'PinballDreams_Disk2.ipf';motor:MAMIGA),
  (nombre:'Rodland';dir:'RODLAND_AMIGA';exec:'Rodland.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'R-Type';dir:'RTYPE_AMIGA';exec:'R-Type.ipf';motor:MAMIGA),
  (nombre:'R-Type II';dir:'RTYPE2_AMIGA';exec:'R-Type2.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Risky Woods';dir:'RWOODS_AMIGA';exec:'Risky Woods_disk1.adf';segundo_disco:'Risky Woods_disk2.adf';motor:MAMIGA),
  (nombre:'Syndicate';dir:'SYNDICATE_AMIGA';exec:'syndicate.vhd';params:'32,1,2,512,0';grafica:'aga';motor:MAMIGA),
  (nombre:'Toki';dir:'TOKI_AMIGA';exec:'Toki.ipf';motor:MAMIGA),
  (nombre:'Corsarios';dir:'CORSARIOS_AMIGA';exec:'Corsarios.adf';motor:MAMIGA),
  (nombre:'Lemmings 2 - The tribes';dir:'LEMM2_AMIGA';exec:'Lemmings2_Disk1.ipf';segundo_disco:'Lemmings2_Disk2.ipf';motor:MAMIGA),
  (nombre:'Lemmings';dir:'LEMMINGS_AMIGA';exec:'Lemmings_Disk1.ipf';segundo_disco:'Lemmings_Disk2.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Livingstone II';dir:'LIVIN2_AMIGA';exec:'Livingstone 2.adf';motor:MAMIGA),
  (nombre:'Satan';dir:'SATAN_AMIGA';exec:'Satan.adf';motor:MAMIGA),
  (nombre:'Stormlord';dir:'STORMLORD_AMIGA';exec:'Stormlord.ipf';motor:MAMIGA),
  (nombre:'Thunder Cats';dir:'THUNDERC_AMIGA';exec:'ThunderCats.ipf';motor:MAMIGA),
  (nombre:'Viaje al Centro de la Tierra';dir:'VCT_AMIGA';exec:'Viaje al Centro de la Tierra.adf';motor:MAMIGA),
  (nombre:'King''s Quest - Quest for the Crown';dir:'KQ_AMIGA';exec:'KingsQuest.adf';exec_pre:'kbd1';motor:MAMIGA),
  (nombre:'King''s Quest II - Romancing the Throne';dir:'KQ2_AMIGA';exec:'KingsQuestII.adf';exec_pre:'kbd1';motor:MAMIGA),
  (nombre:'King''s Quest III - To Heir is Human';dir:'KQ3_AMIGA';exec:'KingsQuestIII.adf';exec_pre:'kbd1';motor:MAMIGA),
  (nombre:'King''s Quest IV - The Perils of Rosella';dir:'KQ4_AMIGA';exec:'kq4.vhd';params:'32,1,2,512,0';exec_pre:'kbd1';grafica:'aga';motor:MAMIGA),
  (nombre:'Narco Police';dir:'NPOLICE_AMIGA';exec:'Narco Police.adf';motor:MAMIGA),
  (nombre:'Smash T.V.';dir:'SMASHTV_AMIGA';exec:'SmashTV.ipf';motor:MAMIGA),
  (nombre:'SnowBros.';dir:'SNOWBROS_AMIGA';exec:'SnowBros.ipf';motor:MAMIGA),
  (nombre:'Spy Who Loved Me, the';dir:'SPYLOVED_AMIGA';exec:'SpyWhoLovedMe.ipf';motor:MAMIGA),
  (nombre:'Sensible Soccer';dir:'SSOCCER_AMIGA';exec:'SensibleSoccer_Disc1.ipf';segundo_disco:'SensibleSoccer_Disc2.ipf';ciclos:200;motor:MAMIGA),
  (nombre:'Zynaps';dir:'ZYNAPS_AMIGA';exec:'Zynaps.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Space Quest Chapter II - Vohaul''s Revenge';dir:'SQ2_AMIGA';exec:'Space Quest II.adf';exec_pre:'kbd1';motor:MAMIGA),
  (nombre:'A.M.C. - Astro Marine Corps';dir:'AMC_AMIGA';exec:'AMC_disk1.adf';motor:MAMIGA),
  (nombre:'Angel Nieto Pole 500';dir:'ANIETO_AMIGA';exec:'Angel Nieto Pole 500.adf';motor:MAMIGA),
  (nombre:'Chichen Itza';dir:'CHICHEN_AMIGA';exec:'Chichen Itza.ipf';motor:MAMIGA),
  (nombre:'Diosa de Cozumel, la';dir:'COZUMEL_AMIGA';exec:'Diosa de Cozumel.ipf';motor:MAMIGA),
  (nombre:'Templos Sagrados, los';dir:'TEMPLOS_AMIGA';exec:'Templos Sagrados.ipf';motor:MAMIGA),
  (nombre:'Wonderboy in Monsterland';dir:'WBOY_AMIGA';exec:'Wonderboy in Monsterland.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Eye of the Beholder (EN)';dir:'EOB_EN';exec:'start1.exe'),
  (nombre:'Eye of the Beholder (ES)';dir:'EOB_ES';exec:'start1.exe'),
  (nombre:'Eye of the Beholder II - Legend of the Dark Moon (EN)';dir:'EOB2_EN';exec:'start.exe';ciclos:6000;setup:'setup.exe'),
  (nombre:'Eye of the Beholder II - Legend of the Dark Moon (ES)';dir:'EOB2_ES';exec:'start.exe';ciclos:6000;setup:'setup.exe'),
  (nombre:'Eye of the Beholder III - Assault on Myth Drannor (EN)';dir:'EOB3_EN';exec:'aesop.exe';params:'eye start';ciclos:12000;setup:'sound.exe'),
  (nombre:'Eye of the Beholder III - Assault on Myth Drannor (ES)';dir:'EOB3_ES';exec:'aesop.exe';params:'eye start';ciclos:12000;setup:'setup.exe'),
  (nombre:'Deliverance';dir:'DELIVERANCE_AMIGA';exec:'Deliverance_Disk1.ipf';segundo_disco:'Deliverance_Disk2.ipf';motor:MAMIGA),
  (nombre:'Eye of the Beholder';dir:'EOB_AMIGA';exec:'eob.vhd';params:'32,1,2,512,0';exec_pre:'kbd1';grafica:'aga';motor:MAMIGA),
  (nombre:'Eye of the Beholder II - Legend of the Dark Moon';dir:'EOB2_AMIGA';exec:'eob2.vhd';params:'32,1,2,512,0';exec_pre:'kbd1';grafica:'aga';motor:MAMIGA),
  (nombre:'Rise of the Robots';dir:'RISEROBOT_AMIGA';exec:'riserobot.vhd';params:'32,1,2,512,0';grafica:'aga';motor:MAMIGA),
  (nombre:'Rambo III';dir:'RAMBO3_AMIGA';exec:'RamboIII.ipf';motor:MAMIGA),
  (nombre:'Red Heat';dir:'REDHEAT_AMIGA';exec:'RedHeat.ipf';motor:MAMIGA),
  (nombre:'RoboCop';dir:'ROBOCOP_AMIGA';exec:'RoboCop.ipf';motor:MAMIGA),
  (nombre:'RoboCop 2';dir:'ROBOCOP2_AMIGA';exec:'RoboCop2_Disk1.ipf';segundo_disco:'RoboCop2_Disk2.ipf';motor:MAMIGA),
  (nombre:'RoboCop 3';dir:'ROBOCOP3_AMIGA';exec:'robocop3.vhd';params:'32,1,2,512,0';grafica:'aga';motor:MAMIGA),
  (nombre:'Sly Spy Secret Agent';dir:'SLYSPY_AMIGA';exec:'SlySpySecretAgent_Disk1.ipf';segundo_disco:'SlySpySecretAgent_Disk2.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Bionic Commando';dir:'BIONICC_AMIGA';exec:'Bionic Commando.ipf';motor:MAMIGA),
  (nombre:'Renegade III';dir:'RENEGADE3_AMIGA';exec:'Renegade3.adf';motor:MAMIGA),
  (nombre:'Bubble Bobble';dir:'BUBBLEB_ST';exec:'Bubble Bobble.stx';motor:MATARIST),
  (nombre:'Leisure Suit Larry in the Land of the Lounge Lizards';dir:'LARRY_ST';exec:'larry1.stx';loadfix:true;params:'larry1';exec_post:'c:\sierra.prg';motor:MATARIST),
  (nombre:'Altered Beast';dir:'ABEAST_ST';exec:'Altered Beast_disk1.stx';motor:MATARIST),
  (nombre:'Defender of the Crown';dir:'DOC_ST';exec:'Defender of the Crown.st';grafica:'st';motor:MATARIST),
  (nombre:'Gauntlet II';dir:'GAUNT2_ST';exec:'Gauntlet II_disk1.stx';motor:MATARIST),
  (nombre:'Rick Dangerous';dir:'RICKD_ST';exec:'Rick Dangerous.stx';motor:MATARIST),
  (nombre:'Rick Dangerous II';dir:'RICKD2_ST';exec:'Rick Dangerous II.stx';motor:MATARIST),
  (nombre:'Xenon II - Megablast';dir:'XENON2_ST';exec:'Xenon II - Megablast_Disk1.stx';motor:MATARIST),
  (nombre:'Lorna';dir:'LORNA_ST';exec:'Lorna_Disk1.stx';motor:MATARIST),
  (nombre:'Robocop';dir:'ROBOCOP_ST';exec:'Robocop.stx';motor:MATARIST),
  (nombre:'Super Street Fighter II Turbo';dir:'SF2T';exec:'SSF2T.BAT';ciclos:1;setup:'setup.exe'),
  (nombre:'Summer Challenge';dir:'SUMMERCH';exec:'summer.com'),
  (nombre:'Games: Winter Challenge, the';dir:'WINTERCH';exec:'winter.com'),
  (nombre:'Syndicate (Plus)';dir:'SYND';exec:'synd.exe';ciclos:1;memoria:4;setup:'del synd.inf'),
  (nombre:'Out Run';dir:'OUTRUN_AMIGA';exec:'OutRun.ipf';motor:MAMIGA),
  (nombre:'Out Run Europa';dir:'OUTRUNEU_AMIGA';exec:'OutRunEuropa_Disk1.ipf';motor:MAMIGA),
  (nombre:'Turbo Outrun';dir:'TOUTRUN_AMIGA';exec:'TurboOutrun_Disk1.ipf';motor:MAMIGA),
  (nombre:'Out Run';dir:'OUTRUN_ST';exec:'OutRun.STX';motor:MATARIST),
  (nombre:'Out Run Europa';dir:'OUTRUNEU_ST';exec:'Out Run Europa disk1.STX';motor:MATARIST),
  (nombre:'Turbo Outrun';dir:'TOUTRUN_ST';exec:'Turbo Out Run.ipf';motor:MATARIST),
  (nombre:'Satan';dir:'SATAN_ST';exec:'satan disk1.stx';motor:MATARIST),
  (nombre:'Livingstone II';dir:'LIVIN2_ST';exec:'Livingstone II.stx';motor:MATARIST),
  (nombre:'Zero-5';dir:'ZERO5_ST';exec:'ZERO_5\zero_5\ZERO5.PRG';params:'ZERO_5';exec_post:'c:\zero_5\ZERO5.PRG';motor:MATARIST),
  (nombre:'3D Breakthru';dir:'3DBREAK_ST';exec:'3D Breakthru.ST';exec_post:'a:\SBREAK.TOS';motor:MATARIST),
  (nombre:'10th Frame';dir:'10FRAME_ST';exec:'10frame\BOWLING.PRG';params:'10frame';exec_post:'C:\BOWLING.PRG';grafica:'st';motor:MATARIST),
  (nombre:'IK+';dir:'IKPLUS_ST';exec:'ik_plus.stx';grafica:'st';motor:MATARIST),
  (nombre:'Karateka';dir:'KARATEKA_ST';exec:'Karateka.stx';loadfix:true;exec_post:'a:\KARATEKA.PRG';motor:MATARIST),
  (nombre:'Road Runner';dir:'ROADRUNN_ST';exec:'Road Runner.stx';motor:MATARIST),
  (nombre:'Solomon''s Key';dir:'SOLOMON_ST';exec:'Solomon''s Key.STX';motor:MATARIST),
  (nombre:'Mega Phoenix';dir:'MPHOENIX_ST';exec:'Mega Phoenix.stx';motor:MATARIST),
  (nombre:'Harrier Strike Mission';dir:'HSTRIKE_ST';exec:'Harrier Strike Mission.st';exec_post:'a:\HARRIER.PRG';motor:MATARIST),
  (nombre:'Macadam Bumper';dir:'MACADAM_ST';exec:'Macadam Bumper.stx';exec_post:'a:\MACADAM.PRG';motor:MATARIST),
  (nombre:'Afterburner';dir:'AFTERB_ST';exec:'Afterburner_Disk 1.stx';motor:MATARIST),
  (nombre:'After the War';dir:'AFTERWAR_ST';exec:'After the War_disk1.stx';motor:MATARIST),
  (nombre:'Test Drive';dir:'TESTDRIVE_ST';exec:'Test Drive_Disk 1.stx';motor:MATARIST),
  (nombre:'Shadow of the Beast';dir:'SHADOWB_AMIGA';exec:'ShadowOfTheBeast_Disk1.ipf';motor:MAMIGA),
  (nombre:'Shadow of the Beast II';dir:'SHADOWB2_AMIGA';exec:'ShadowOfTheBeastII_Disk1.ipf';motor:MAMIGA),
  (nombre:'Shadow of the Beast III';dir:'SHADOWB3_AMIGA';exec:'ShadowOfTheBeastIII_Disk1.ipf';motor:MAMIGA),
  (nombre:'Test Drive';dir:'TESTDRIVE_AMIGA';exec:'TestDrive.ipf';motor:MAMIGA),
  (nombre:'Theme Park';dir:'THEMEP_AMIGA';exec:'ThemePark_Disk1.ipf';segundo_disco:'ThemePark_Disk2.ipf';tercer_disco:'ThemePark_Disk3.ipf';cuarto_disco:'ThemePark_Disk4.ipf';grafica:'aga';motor:MAMIGA),
  (nombre:'Test Drive II: The Duel';dir:'TESTDRIVE2_ST';exec:'testd2\DUEL.PRG';params:'testd2';exec_post:'c:\DUEL.PRG';motor:MATARIST),
  (nombre:'Test Drive II: The Duel';dir:'TESTDRIVE2_AMIGA';exec:'testdrive2.vhd';params:'32,1,2,512,0';segundo_disco:'TestDriveII.ipf';motor:MAMIGA),
  (nombre:'Motörhead';dir:'MOTORHEAD_AMIGA';exec:'Motorhead.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Obliterator';dir:'OBLITERATOR_AMIGA';exec:'Obliterator.ipf';motor:MAMIGA),
  (nombre:'Midnight Resistance';dir:'MIDNIGHTR_AMIGA';exec:'MidnightResistance.ipf';loadfix:true;motor:MAMIGA),
  (nombre:'Midnight Resistance';dir:'MIDNIGHTR_ST';exec:'midnight_resistance_disk1.stx';motor:MATARIST),
  (nombre:'Obliterator';dir:'OBLITERATOR_ST';exec:'Obliterator_Disk 1.stx';motor:MATARIST),
  (nombre:'Motörhead';dir:'MOTORHEAD_ST';exec:'Motörhead.stx';motor:MATARIST),
  (nombre:'Street Fighter II - The World Warrior';dir:'SF2_AMIGA';exec:'StreetFighterII-TheWorldWarrior_Disk1.ipf';segundo_disco:'StreetFighterII-TheWorldWarrior_Disk2.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Renegade';dir:'RENEGADE_ST';exec:'Renegade_Disk1.stx';grafica:'st_102';motor:MATARIST),
  (nombre:'Ghosts''n Goblins';dir:'GNG_ST';exec:'Ghosts''n Goblins.STX';motor:MATARIST),
  (nombre:'Astaroth - The Angel of Death';dir:'ASTAROTH_ST';exec:'Astaroth - The Angel of Death_Disk1.stx';grafica:'st';motor:MATARIST),
  (nombre:'Exolon';dir:'EXOLON_ST';exec:'Exolon.stx';grafica:'st';motor:MATARIST),
  (nombre:'Exolon';dir:'EXOLON_AMIGA';exec:'Exolon.ipf';motor:MAMIGA),
  (nombre:'5th Gear';dir:'5THGEAR_ST';exec:'5th Gear.STX';grafica:'st';motor:MATARIST),
  (nombre:'Oids';dir:'OIDS_ST';exec:'Oids.stx';motor:MATARIST),
  (nombre:'Agony';dir:'AGONY_AMIGA';exec:'Agony_Disk1.ipf';segundo_disco:'Agony_Disk2.ipf';tercer_disco:'Agony_Disk3.ipf';motor:MAMIGA),
  (nombre:'Apidya';dir:'APIDYA_AMIGA';exec:'Apidya_Disk1.ipf';segundo_disco:'Apidya_Disk2.ipf';motor:MAMIGA),
  (nombre:'Disposable Hero';dir:'DISPOSABLE_AMIGA';exec:'Disposable Hero_Disk 1.adf';segundo_disco:'Disposable Hero_Disk 2.adf';tercer_disco:'Disposable Hero_Disk 3.adf';motor:MAMIGA),
  (nombre:'Fire and Ice - Cool Coyote';dir:'FIREICE_AMIGA';exec:'FireAndIce_Disc1.ipf';ciclos:100;motor:MAMIGA),
  (nombre:'Superfrog';dir:'SUPERFROG_AMIGA';exec:'SuperFrog_Disk1.ipf';segundo_disco:'SuperFrog_Disk2.ipf';motor:MAMIGA),
  (nombre:'Wings';dir:'WINGS_AMIGA';exec:'Wings_Disk1.adf';segundo_disco:'Wings_Disk2.adf';motor:MAMIGA),
  (nombre:'Bard''s Tale, The - Tales of the Unknown';dir:'BARDS_APPLE';exec:'Bard''s Tale, The - Tales of the Unknown_Boot Disk.woz';motor:MAPPLE2),
  (nombre:'Burger Time';dir:'BURGUER_APPLE';exec:'BurgerTime.woz';motor:MAPPLE2),
  (nombre:'Jumpman';dir:'JUMPMAN_APPLE';exec:'Jumpman - Beginner Levels.woz';motor:MAPPLE2),
  (nombre:'Boulderdash';dir:'BOULDER_APPLE';exec:'Boulderdash.woz';motor:MAPPLE2),
  (nombre:'Boulderdash II';dir:'BOULDER2_APPLE';exec:'Boulderdash II.woz';motor:MAPPLE2),
  (nombre:'Ultima I: The Beginning';dir:'ULTIMAI_APPLE';exec:'Ultima I - The Beginning.woz';motor:MAPPLE2),
  (nombre:'Ultima II: The Revenge of the Enchantress';dir:'ULTIMAII_APPLE';exec:'Ultima II - Program Master.woz';motor:MAPPLE2),
  (nombre:'Ultima III: Exodus';dir:'ULTIMAIII_APPLE';exec:'Ultima III - Exodus_SideA.woz';motor:MAPPLE2),
  (nombre:'Ultima IV: Quest of the Avatar';dir:'ULTIMAIV_APPLE';exec:'Ultima IV - Quest of the Avatar_SideA.woz';motor:MAPPLE2),
  (nombre:'Zaxxon';dir:'ZAXXON_APPLE';exec:'Zaxxon.woz';motor:MAPPLE2),
  (nombre:'Eastern Front 1941';dir:'EASTERNF_A8';exec:'Eastern Front (1941).atr';motor:MATARI8),
  (nombre:'Rescue on Fractalus!';dir:'RESCUEF_A8';exec:'Rescue on Fractalus!.atx';motor:MATARI8),
  (nombre:'Ballblazer';dir:'BALLBLAZER_A8';exec:'Ballblazer.atx';motor:MATARI8),
  (nombre:'Boulderdash';dir:'BOULDER_A8';exec:'Boulderdash.rom';motor:MATARI8),
  (nombre:'Boulderdash II';dir:'BOULDER2_A8';exec:'Boulder Dash II.cas';motor:MATARI8),
  (nombre:'River Raid';dir:'RIVERRAID_A8';exec:'River Raid.cas';motor:MATARI8),
  (nombre:'Ultima VII: The Black Gate';dir:'ULTIMA7';exec:'ultima7.com';ciclos:14000;extra_param:'-set ems=false';setup:'install.exe';refs:(1,0,0)),
  //
  (nombre:'Fire Fight';dir:'FFIGHT';exec:'ffight.img';cdrom:'ffight.cue';motor:MWIN95),
  (nombre:'Castillo del Doctor Brain (ES)';dir:'BRAIN_ES';exec:'sierra.exe';setup:'install.exe'),
  (nombre:'Espada Sagrada, la';dir:'ESPADAS';exec:'espada.com';ciclos:1500),
  (nombre:'Freddy Pharkas - Frontier Pharmacist (EN)';dir:'FPFP_EN';exec:'sierra.exe';setup:'install.exe'),
  (nombre:'Freddy Pharkas - Farmacéutico de la Frontera (ES)';dir:'FPFP_ES';exec:'sierra.exe';setup:'install.exe'),
  (nombre:'Life and Death (EN)';dir:'LDEATH';exec:'L&D.EXE';ciclos:450),
  (nombre:'Life and Death (ES)';dir:'LD_ES';exec:'L&D.EXE';ciclos:450),
  (nombre:'Life & Death II - The Brain (ES)';dir:'LD2_ES';exec:'LD2.EXE'),
  (nombre:'Silent Shadow';dir:'SSHADOW';exec:'SILENT.EXE';ciclos:1500),
  (nombre:'Stardust';dir:'STARDUST';exec:'STARDUST.EXE';ciclos:750),
  (nombre:'Terminator, the';dir:'TERM';exec:'TERM.COM';ciclos:3500),
  (nombre:'Ages of Empire - Gold (ES)';dir:'AOE_ES';exec:'aoe_es.img';cdrom:'AOE.cue';motor:MWIN95),
  (nombre:'Ages of Empire II - The Age of Kings (ES)';dir:'AOE2_ES';exec:'aoe2.img';extra_param:'-set cputype=pentium';cdrom:'AOE2.cue';motor:MWIN95)
);

implementation

end.
