unit games_data;

{$ifdef fpc}{$mode delphi}{$H+}{$endif}

interface
type
   tipo_games=record
    nombre:string;
    dir:string;
    exec:string;
    params:string;
    exec_pre:string;
    exec_post:string;
    segundo_disco:string;
    ciclos:integer;
    grafica:string;
    extra_param:string;
    mapper:string;
    gus:boolean;
    scumm:boolean;
    cdrom:string;
    memoria:integer;
    setup:string;
    zip:boolean;
  end;
const
  GAME_TOTAL=303;  //+2  //Doomdata!!!
  GAME_DATA:array[0..(GAME_TOTAL-1)] of tipo_games=(
  (nombre:'Bruce Lee';dir:'brucelee';exec:'brucelee.img';ciclos:300;grafica:'cga_composite';extra_param:'-set joysticktype=2axis';mapper:'brucelee.map';memoria:1;zip:true),
  (nombre:'Lost Vikings, the';dir:'lostv';exec:'vikings.exe';setup:'setup.exe';zip:true),
  (nombre:'King''s Quest - Quest for the Crown';dir:'kq1';exec:'sierra.com';ciclos:1000;grafica:'tandy';scumm:true;zip:true),
  (nombre:'King''s Quest II - Romancing the Throne';dir:'kq2';exec:'kq2.com';ciclos:1000;grafica:'tandy';scumm:true;zip:true),
  (nombre:'King''s Quest III - To Heir is Human';dir:'kq3';exec:'sierra.com';ciclos:1000;grafica:'tandy';scumm:true;zip:true),
  (nombre:'Indiana Jones and the Fate of Atlantis (ES)';dir:'ijfa_es';exec:'atlantis.exe';scumm:true;zip:true),
  (nombre:'Indiana Jones and the Fate of Atlantis (EN)';dir:'ijfa_en';exec:'atlantis.exe';scumm:true;zip:true),
  (nombre:'Indiana Jones and the Fate of Atlantis (DE)';dir:'ijfa_de';exec:'atlantis.exe';scumm:true;zip:true),
  (nombre:'Three Stooges, the';dir:'3stooges';exec:'stooges.exe';grafica:'tandy';zip:true),
  (nombre:'Dark Forces (ES)';dir:'darkf_es';exec:'dark.exe';ciclos:1;gus:true;cdrom:'CD\darkforces.iso';memoria:30;zip:true),
  (nombre:'Alone in the Dark (ES)';dir:'alitd_es';exec:'tatou.com';zip:true),
  (nombre:'Alone in the Dark (EN)';dir:'alitd_en';exec:'tatou.com';zip:true),
  (nombre:'Alone in the Dark (DE)';dir:'alitd_de';exec:'tatou.com';zip:true),
  (nombre:'Alone in the Dark (FR)';dir:'alitd_fr';exec:'tatou.com';zip:true),
  (nombre:'Alone in the Dark 2 (ES)';dir:'ALID2_ES';exec:'aitd2.exe';exec_pre:'crack.com';zip:true),
  (nombre:'Amazing Spiderman, the';dir:'amazings';exec:'spidey.exe';zip:true),
  (nombre:'Out of this World';dir:'outworld';exec:'world.exe';zip:true),
  (nombre:'Duke Nukum - Episode One';dir:'duke1';exec:'dn1.exe';zip:true),
  (nombre:'Duke Nukum - Episode Two';dir:'duke2';exec:'dn2.exe';zip:true),
  (nombre:'Duke Nukum - Episode Three';dir:'duke3';exec:'dn3.exe';zip:true),
  (nombre:'Duke Nukem II';dir:'dn2';exec:'nukem2.exe';zip:true),
  (nombre:'Defender of the Crown';dir:'doc';exec:'doc.img';grafica:'tandy';memoria:1;zip:true),
  (nombre:'Gobliiins';dir:'goblins';exec:'goblins.exe';ciclos:3000;scumm:true;zip:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (ES)';dir:'gob2_es';exec:'LOADER.EXE';scumm:true;zip:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (EN)';dir:'gob2_en';exec:'LOADER.EXE';scumm:true;zip:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (IT)';dir:'gob2_it';exec:'LOADER.EXE';scumm:true;zip:true),
  (nombre:'Gobliins 2 - The Prince Buffoon (DE)';dir:'gob2_de';exec:'LOADER.EXE';scumm:true;zip:true),
  (nombre:'Gods';dir:'gods';exec:'gods.exe';zip:true),
  (nombre:'Alley Cat';dir:'alleycat';exec:'alleycat.img';ciclos:300;grafica:'cga';memoria:1;zip:true),
  (nombre:'Rescate en el Golfo';dir:'rgolfo';exec:'rgolfo.img';memoria:1;zip:true),
  (nombre:'Leisure Suir Larry in the Land of the Lounge Lizards';dir:'lsl1';exec:'sierra.com';grafica:'tandy';scumm:true;zip:true),
  (nombre:'Street Rod';dir:'streetr';exec:'sr.exe';zip:true),
  (nombre:'Street Rod II';dir:'streetr2';exec:'sr.exe';zip:true),
  (nombre:'Wrath of the Demon';dir:'wrathd';exec:'wrath.exe';zip:true),
  (nombre:'Speed Ball';dir:'spball';exec:'ega.exe';ciclos:1000;zip:true),
  (nombre:'Prince of Persia';dir:'pop';exec:'prince.exe';zip:true),
  (nombre:'One Step Beyond';dir:'osb';exec:'onestep.exe';zip:true),
  (nombre:'Push Over';dir:'pushover';exec:'push.exe';zip:true),
  (nombre:'Rampart';dir:'rampart';exec:'rampart.exe';zip:true),
  (nombre:'Rise of the Triad';dir:'rise';exec:'rott.exe';ciclos:1;gus:true;memoria:30;zip:true),
  (nombre:'Risky Woods (EN)';dir:'risky_en';exec:'risky.exe';zip:true),
  (nombre:'WarCraft - Orcs & Humans';dir:'warc';exec:'war.exe';setup:'setup.exe';zip:true),
  (nombre:'LHX - Attack Chopper';dir:'lhx';exec:'lhx.exe';ciclos:3000;extra_param:'vga adlibsound high';zip:true),
  (nombre:'Loom (ES)';dir:'loom_es';exec:'loom.exe';params:'r';scumm:true;zip:true),
  (nombre:'Loom (EN)';dir:'loom_en';exec:'loom.exe';params:'r';scumm:true;zip:true),
  (nombre:'Loom (DE)';dir:'loom_de';exec:'loom.exe';params:'r';scumm:true;zip:true),
  (nombre:'Loom (FR)';dir:'loom_fr';exec:'loom.exe';params:'r';scumm:true;zip:true),
  (nombre:'Secret of Monkey Island, the (ES)';dir:'mi_v_es';exec:'monkey.exe';params:'r';scumm:true;zip:true),
  (nombre:'Secret of Monkey Island, the (EN)';dir:'mi_v_en';exec:'monkey.exe';params:'r';scumm:true;zip:true),
  (nombre:'King''s Quest IV - The Perils of Rosella';dir:'kq4';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'Leisure Suit Larry 6 - Shape Up (ES)';dir:'lsl6_es';exec:'sierra.exe';exec_pre:'LH ULTRAMID -C -M100 ';ciclos:1;gus:true;scumm:true;zip:true),
  (nombre:'Secret of Monkey Island, the (ES) (EGA)';dir:'mi_e_es';exec:'monkey.exe';ciclos:3000;zip:true),
  (nombre:'Poli Diaz - El Potro de Vallecas';dir:'polidiaz';exec:'polidiaz.img';memoria:1;zip:true),
  (nombre:'King''s Quest - Quest for the Crown (CGA-PCBooter)';dir:'kq1_cga';exec:'kq1_cga.img';ciclos:300;grafica:'cga_composite';memoria:1;zip:true),
  (nombre:'Archon - The Light and the Dark';dir:'archon';exec:'archon.img';ciclos:300;grafica:'cga_composite';extra_param:'-set core=normal';memoria:1;zip:true),
  (nombre:'Archon Ultra';dir:'aultra';exec:'archon.exe';zip:true),
  (nombre:'Doom';dir:'doom';exec:'doom.exe';exec_pre:'mkdir C:\DOOMDATA[RET]copy default.cfg c:\doomdata';exec_post:'del c:\doomdata /q[RET]rd c:\doomdata';ciclos:1;gus:true;memoria:30;zip:true),
  (nombre:'Defender of the Crown (CGA)';dir:'doc_cga';exec:'doc.exe';zip:true),
  (nombre:'Doom II';dir:'doom2';exec:'doom2.exe';ciclos:1;gus:true;memoria:30;zip:true),
  (nombre:'Heretic, Shadow of the Serpent Riders';dir:'heretic';exec:'heretic.exe';ciclos:1;gus:true;memoria:30;zip:true),
  (nombre:'Raptor - Call of the Shadows';dir:'raptor';exec:'rap.exe';ciclos:1;gus:true;memoria:30;zip:true),
  (nombre:'Immortal, the';dir:'immortal';exec:'immortal.exe';zip:true),
  (nombre:'Cruise for a Corpse (ES)';dir:'cruise';exec:'delphine.exe';ciclos:10000;scumm:true;zip:true),
  (nombre:'Commando';dir:'commando';exec:'commando.img';ciclos:300;grafica:'cga_composite';mapper:'commando.map';memoria:1;zip:true),
  (nombre:'Caveman Ninja';dir:'caveman';exec:'caveman.exe';ciclos:20000;zip:true),
  (nombre:'Uridium';dir:'uridium';exec:'uridium.exe';ciclos:3000;extra_param:'-set joysticktype=2axis';mapper:'uridium.map';zip:true),
  (nombre:'Conquests of Camelot - King Arthur the Search for the Grail';dir:'camelot';exec:'sierra.com';scumm:true;zip:true),
  (nombre:'Day of the Tentacle (ES)';dir:'dott_es';exec:'tentacle.exe';scumm:true;zip:true),
  (nombre:'King''s Quest V: Absence Makes the Heart go Yonder (ES)';dir:'kq5_es';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'King''s Quest VI: Heir Today Gone Tomorrow (ES)';dir:'kq6_es';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'Monkey Island 2 - LeChuck''s Revenge (ES)';dir:'mi2_es';exec:'monkey2.exe';params:'r s';scumm:true;zip:true),
  (nombre:'Robocop';dir:'robocop';exec:'robocop.exe';grafica:'tandy';zip:true),
  (nombre:'Robocop 3';dir:'robo3';exec:'start.exe';params:'start SOUND=R DID=C:\ROBO3';ciclos:3000;zip:true),
  (nombre:'Legend of Kyrandia, the (ES)';dir:'KYRAN_ES';exec:'main.exe';scumm:true;zip:true),
  (nombre:'Legend of Kyrandia - The Hand of Fate, the (ES)';dir:'kyra2_es';exec:'hof.exe';scumm:true;zip:true),
  (nombre:'Space Quest Chapter I - The Sarien Encounter';dir:'sq1';exec:'sierra.com';grafica:'tandy';scumm:true;zip:true),
  (nombre:'Space Quest Chapter I - The Sarien Encounter VGA (ES)';dir:'sq1_es';exec:'scidhuv.exe';scumm:true;zip:true),
  (nombre:'Space Quest Chapter I - The Sarien Encounter EGA (EN)';dir:'sq1_en';exec:'sciduv.exe';scumm:true;zip:true),
  (nombre:'Space Quest Chapter II - Vohaul''s Revenge';dir:'sq2';exec:'sierra.com';grafica:'tandy';scumm:true;zip:true),
  (nombre:'Space Quest Chapter III - The Pirates of Pestulon';dir:'sq3';exec:'sierra.com';scumm:true;zip:true),
  (nombre:'Viking Child, the';dir:'vikingc';exec:'vc.exe';ciclos:3000;zip:true),
  (nombre:'Prince of Persia II - The Shadow and the Flame';dir:'pop2';exec:'prince.exe';zip:true),
  (nombre:'Paratrooper';dir:'PARATR';exec:'paratr.img';ciclos:300;grafica:'cga';memoria:1;zip:true),
  (nombre:'Leisure Suit Larry - Looking for Love (in Several Wrong Places)';dir:'lsl2';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'Leisure Suit Larry 3 - Passionate Patti in  Pursuit of the Pulsating Pectorals!';dir:'lsl3';exec:'sierra.com';scumm:true;zip:true),
  (nombre:'Arkanoid II - The Revenge of Doh';dir:'ARKAN2';exec:'doh.exe';extra_param:'-set a20=off';zip:true),
  (nombre:'Battle Chess (EGA)';dir:'bchess_e';exec:'chess.exe';zip:true),
  (nombre:'Battle Chess (VGA)';dir:'bchess_v';exec:'chess.exe';zip:true),
  (nombre:'Battle Chess II - Chinese Chess';dir:'bchess2';exec:'chess2.exe';zip:true),
  (nombre:'Battle Chess 4000';dir:'bc4k_h';exec:'bc4000.exe';extra_param:'-set core=normal';zip:true),
  (nombre:'Battle Chess 4000 (Low Res)';dir:'bc4k_l';exec:'bc4000.exe';extra_param:'-set core=normal';zip:true),
  (nombre:'Ikari Warriors';dir:'ikariw';exec:'iw_1.img';segundo_disco:'iw_2.img';ciclos:1000;memoria:1;zip:true),
  (nombre:'Alone in the Dark 3 (ES)';dir:'ALID3_ES';exec:'aitd3.exe';exec_post:'del c:\fastseek.lut';ciclos:1;cdrom:'CD\aitd3.cue';memoria:30;zip:true),
  (nombre:'Goblins 3 (ES)';dir:'gob3_es';exec:'gob3.exe';scumm:true;zip:true),
  (nombre:'Bargon Attack (ES)';dir:'batt_es';exec:'loader.exe';scumm:true;zip:true),
  (nombre:'Bargon Attack (EN)';dir:'batt_en';exec:'loader.exe';scumm:true;zip:true),
  (nombre:'Rastan';dir:'rastan';exec:'rastan.exe';zip:true),
  (nombre:'Karnov';dir:'karnov';exec:'karnov_1.img';segundo_disco:'karnov_2.img';ciclos:1000;memoria:1;zip:true),
  (nombre:'Goody';dir:'goody';exec:'goody.img';ciclos:300;memoria:1;zip:true),
  (nombre:'Tapper';dir:'tapper';exec:'tapper.img';ciclos:300;grafica:'cga_composite';memoria:1;zip:true),
  (nombre:'Livingstone Supongo II';dir:'living2';exec:'lvs2.img';memoria:1;zip:true),
  (nombre:'Victory Road';dir:'victoryr';exec:'victoryr.img';ciclos:1000;grafica:'tandy';memoria:1;zip:true),
  (nombre:'Julius Erving and Larry Bird Go One on One';dir:'1on1';exec:'1on1.img';ciclos:300;grafica:'pcjr';memoria:1;zip:true),
  (nombre:'Sol Negro';dir:'solnegro';exec:'sol.exe';zip:true),
  (nombre:'Sol Negro (CGA)';dir:'solnegro_cga';exec:'solnegro.img';mapper:'solnegro.map';memoria:1;zip:true),
  (nombre:'Freddy Hardest';dir:'freddyh';exec:'freddyh.img';ciclos:1000;memoria:1;zip:true),
  (nombre:'Freddy Hardest in South Manhattan';dir:'fh_sm';exec:'fh_sm.img';ciclos:1000;grafica:'cga';memoria:1;zip:true),
  (nombre:'Last Mission, the';dir:'lastmiss';exec:'lastmiss.img';ciclos:300;memoria:1;zip:true),
  (nombre:'Impossible Mission II';dir:'imiss2';exec:'im2_mcga.exe';ciclos:1000;zip:true),
  (nombre:'King''s Quest II - Romancing the Throne (PCBooter)';dir:'kq2_boot';exec:'kq2_1.img';segundo_disco:'kq2_2.img';ciclos:1000;grafica:'tandy';extra_param:'-set core=normal';memoria:1;zip:true),
  (nombre:'King''s Quest V: Absence Makes the Heart go Yonder (ES/EGA)';dir:'kq5_es_e';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'Thexder';dir:'thexder';exec:'thexder.com';grafica:'tandy';zip:true),
  (nombre:'Thexder II - Fire Hawk';dir:'thexder2';exec:'sierra.exe';zip:true),
  (nombre:'Test Drive';dir:'testdrv';exec:'tdh.exe';zip:true),
  (nombre:'Livingstone Supongo';dir:'living';exec:'Living.img';ciclos:300;memoria:1;zip:true),
  (nombre:'Captain Comic, the Adventures of';dir:'ccomic';exec:'comic.exe';zip:true),
  (nombre:'Captain Comic II: Fractured Reality';dir:'ccomic2';exec:'fr.exe';zip:true),
  (nombre:'Corsarios';dir:'corsario';exec:'corsario.exe';zip:true),
  (nombre:'Prehistorik';dir:'prehis1';exec:'historik.exe';zip:true),
  (nombre:'Prehistorik 2';dir:'prehis2';exec:'pre2.exe';zip:true),
  (nombre:'Titus the Fox - to Marrakech and Back';dir:'titusfox';exec:'fox.exe';zip:true),
  (nombre:'Ikari 3 - The Rescue';dir:'ikariw3';exec:'ikari3.exe';zip:true),
  (nombre:'Baby Jo in Going Home (VGA)';dir:'babyjo';exec:'baby.exe';params:'3';ciclos:3000;zip:true),
  (nombre:'Narco Police';dir:'narcop';exec:'narcop.img';memoria:1;zip:true),
  (nombre:'Emmanuelle (ES)';dir:'emma_es';exec:'loader.com';ciclos:3000;zip:true),
  (nombre:'Emmanuelle (EN)';dir:'emma_en';exec:'emma.com';ciclos:3000;zip:true),
  (nombre:'Turrican II';dir:'TURRICA2';exec:'t2.exe';exec_pre:'set t2dir=.';gus:true;zip:true),
  (nombre:'Commander Keen Episode One: Marooned on Mars';dir:'ckeen1';exec:'keen1.exe';zip:true),
  (nombre:'Commander Keen Episode Two: The Earth Explodes';dir:'ckeen2';exec:'keen2.exe';zip:true),
  (nombre:'Commander Keen Episode Three: Keen Must Die!';dir:'ckeen3';exec:'keen3.exe';zip:true),
  (nombre:'Commander Keen Episode IV: Secret of the Oracle';dir:'ckeen4';exec:'keen4e.exe';zip:true),
  (nombre:'Commander Keen Episode V: the Armagedon Machine';dir:'ckeen5';exec:'keen5e.exe';zip:true),
  (nombre:'Commander Keen in Aliens Ate my Baby Sitter!';dir:'ckeen6';exec:'keen6c.exe';zip:true),
  (nombre:'Commander Keen in Keen Dreams';dir:'ckeendrm';exec:'kdreams.exe';zip:true),
  (nombre:'Cool Croc Twins';dir:'coolcroc';exec:'start.com';params:'1';zip:true),
  (nombre:'Cool World';dir:'coolwrld';exec:'cool.exe';zip:true),
  (nombre:'Flash Back';dir:'flashb';exec:'fb.exe';zip:true),
  (nombre:'Jazz Jackrabbit';dir:'jazzjack';exec:'jazz.exe';gus:true;zip:true),
  (nombre:'Jazz Jackrabbit Holiday Hare';dir:'jazzhh';exec:'jazz.exe';gus:true;zip:true),
  (nombre:'Abadia del Crimen, la';dir:'abadia';exec:'abadia.img';ciclos:700;grafica:'cga';memoria:1;zip:true),
  (nombre:'Aaargh';dir:'aaargh';exec:'aargh.exe';ciclos:1000;grafica:'tandy';zip:true),
  (nombre:'Budokan - The Martial Spirit';dir:'budokan';exec:'budo.com';params:'vga mt32 shadowns';zip:true),
  (nombre:'Bubble Bobble';dir:'bubble';exec:'bubble.exe';ciclos:3000;zip:true),
  (nombre:'Blackthorne';dir:'bthorne';exec:'bthorne.exe';exec_pre:'ultramid -f -q[RET]ultramid -c -q';exec_post:'ultramid -f -q';gus:true;memoria:30;zip:true),
  (nombre:'Rad-Warrior';dir:'radwar';exec:'radwar.exe';ciclos:750;zip:true),
  (nombre:'Ghost''n Goblins';dir:'gng';exec:'gag.exe';ciclos:1000;extra_param:'-set joysticktype=2axis';mapper:'gng.map';zip:true),
  (nombre:'Alien Breed';dir:'abreed';exec:'alien.exe';ciclos:6000;zip:true),
  (nombre:'Alien Breed - Tower Assault';dir:'abreedta';exec:'ta.exe';ciclos:6000;gus:true;zip:true),
  (nombre:'Abuse';dir:'abuse';exec:'abuse.exe';ciclos:1;zip:true),
  (nombre:'Alf';dir:'alf';exec:'alf.exe';ciclos:300;zip:true),
  (nombre:'Alkatraz';dir:'alkatraz';exec:'alkatraz.exe';zip:true),
  (nombre:'King''s Quest IV - The Perils of Rosella (AGI)';dir:'kq4_agi';exec:'kq4.com';grafica:'tandy';scumm:true;zip:true),
  (nombre:'EcoQuest 1 - The Search for Cetus';dir:'ecoq_es';exec:'scidhuv.exe';scumm:true;zip:true),
  (nombre:'EcoQuest 2 - El Secreto Perdido de la Selva Amazonica';dir:'ecoq2_es';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'Golden Axe';dir:'goldaxe';exec:'goldaxe.exe';zip:true),
  (nombre:'Megaphoenix';dir:'mphoenix';exec:'dinamic.exe';zip:true),
  (nombre:'Satan';dir:'satan';exec:'satan.img';memoria:1;zip:true),
  (nombre:'After the War';dir:'afterw';exec:'dinamic.com';ciclos:3300;zip:true),
  (nombre:'Quake';dir:'quake';exec:'quake.exe';ciclos:1;cdrom:'CD\quake.cue';memoria:30;zip:true),
  (nombre:'Wolfenstein 3-D';dir:'wolf3d';exec:'wolf3d.exe';ciclos:1;zip:true),
  (nombre:'Wolfenstein 3-D: Spear of Destiny';dir:'w3dspear';exec:'spear.exe';ciclos:1;zip:true),
  (nombre:'Castle Wolfenstein';dir:'castlew';exec:'cw.exe';ciclos:300;grafica:'cga_composite';memoria:1;zip:true),
  (nombre:'Donkey Kong';dir:'donkeyk';exec:'donkeyk.img';ciclos:450;memoria:1;zip:true),
  (nombre:'Double Dragon';dir:'dd1';exec:'ddmain.exe';exec_pre:'dual.exe[RET]show.exe';ciclos:750;zip:true),
  (nombre:'Double Dragon II - The Revenge';dir:'dd2';exec:'dragon.exe';zip:true),
  (nombre:'Duke Nukem 3D';dir:'duke3d';exec:'duke3d.exe';ciclos:1;gus:true;memoria:30;zip:true),
  (nombre:'Lemmings';dir:'lemmings';exec:'lemvga.com';params:'/v /pc';zip:true),
  (nombre:'Lemmings II - The Tribes';dir:'lemm2';exec:'l2-fix.com';extra_param:'-set xms=false';zip:true),
  (nombre:'Mortal Kombat';dir:'mkombat';exec:'mk.exe';ciclos:1;setup:'setup.exe';zip:true),
  (nombre:'Mortal Kombat II';dir:'mkombat2';exec:'mk2.exe';exec_pre:'ultramid.exe -q -c -m100';ciclos:1;gus:true;zip:true),
  (nombre:'Street Fighter';dir:'sf';exec:'sf.exe';ciclos:1000;extra_param:'-set joysticktype=2axis';mapper:'sf.map';zip:true),
  (nombre:'Street Fighter II';dir:'sf2';exec:'sf2.exe';zip:true),
  (nombre:'Slugger, the';dir:'slugger';exec:'slugger.img';ciclos:1000;memoria:1;zip:true),
  (nombre:'Black Cauldron, the';dir:'bcauld';exec:'bc.com';ciclos:1000;grafica:'tandy';scumm:true;zip:true),
  (nombre:'Zona 0';dir:'zona0';exec:'zona0.com';zip:true),
  (nombre:'Jumpman';dir:'jumpman';exec:'jumpman.img';ciclos:300;grafica:'cga';memoria:1;zip:true),
  (nombre:'Viaje al Centro de la Tierra';dir:'vct';exec:'menu.com';zip:true),
  (nombre:'Risky Woods (ES)';dir:'risky_es';exec:'risky.exe';zip:true),
  (nombre:'SimAnt';dir:'simant';exec:'simant.exe';zip:true),
  (nombre:'Arkanoid (CGA)';dir:'arka_cga';exec:'arkanoid.exe';ciclos:700;zip:true),
  (nombre:'Arkanoid';dir:'arkanoid';exec:'arkanoid.exe';grafica:'tandy';zip:true),
  (nombre:'Epic Pinball';dir:'epicpin';exec:'pinball.exe';gus:true;zip:true),
  (nombre:'Jill of the Jungle';dir:'jill';exec:'jill.bat';zip:true),
  (nombre:'Double Dragon 3 - The Rosetta Stone';dir:'dd3';exec:'dd3.exe';zip:true),
  (nombre:'Quest for Glory I - So you want to be a Hero';dir:'qg1';exec:'sierra.com';scumm:true;zip:true),
  (nombre:'Quest for Glory II - Trial by Fire';dir:'qg2';exec:'sierra.com';scumm:true;zip:true),
  (nombre:'Quest for Glory III - Waves of War';dir:'qg3';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'Quest for Glory IV - Shadows of Darkness';dir:'qg4';exec:'sierra.exe';scumm:true;zip:true),
  (nombre:'Lode Runner';dir:'loderunn';exec:'loderunn.img';ciclos:300;grafica:'cga_composite';memoria:1;zip:true),
  (nombre:'Montezuma''s Revenge';dir:'montezum';exec:'montezum.img';ciclos:300;grafica:'pcjr';memoria:1;zip:true),
  (nombre:'Pole Position';dir:'polepos';exec:'drive.com';exec_pre:'mount a: [GAME_DIR]';ciclos:300;grafica:'cga';memoria:1;zip:true),
  (nombre:'Chips''s Challenge';dir:'chipsc';exec:'chips.exe';ciclos:1500;zip:true),
  (nombre:'M.U.L.E.';dir:'mule';exec:'mule.img';ciclos:300;grafica:'cga_composite';memoria:1;zip:true),
  (nombre:'Crazy Cars';dir:'ccars';exec:'crazycar.exe';ciclos:300;grafica:'cga';memoria:1;zip:true),
  (nombre:'Luigi & Spaghetti';dir:'luigispa';exec:'topo.bat';zip:true),
  (nombre:'Luigi en Circusland';dir:'luigi2';exec:'luigi2sb.bat';zip:true),
  (nombre:'Black Cauldron, the (PC-Booter)';dir:'bc_boot';exec:'BC_D1.IMG';segundo_disco:'BC_D2.IMG';ciclos:1000;grafica:'tandy';memoria:1;zip:true),
  (nombre:'Mortal Kombat 3';dir:'mk3';exec:'mk3.exe';ciclos:1;gus:true;cdrom:'CD\mk3.cue';memoria:30;zip:true),
  (nombre:'Dune II - La Batalla por Arrakis';dir:'dune2_es';exec:'dune2.exe';ciclos:1;zip:true),
  (nombre:'Indiana Jones y la Última Cruzada';dir:'indy3_es';exec:'indy3.exe';params:'a v';ciclos:3000;scumm:true;zip:true),
  (nombre:'Heimdall';dir:'heimdall';exec:'heimdall.exe';ciclos:3000;zip:true),
  (nombre:'Tyrian';dir:'tyrian';exec:'tyrian.exe';exec_pre:'LH c:\extras\ultrasnd\ULTRAMID -C -M100';ciclos:1;gus:true;memoria:30;zip:true),
  (nombre:'Escape from the Planet of the Robot Monsters';dir:'escape';exec:'escape.exe';mapper:'escape.map';zip:true),
  (nombre:'SimCity';dir:'simcity';exec:'simcity.exe';zip:true),
  (nombre:'SimCity 2000';dir:'sc2000';exec:'sc2000.exe';zip:true),
  (nombre:'Wing Commander + Secret Missions';dir:'wingcomm';exec:'wc.exe';ciclos:4500;zip:true),
  (nombre:'Wing Commander Secret Missions 2';dir:'wingcomm';exec:'sm2.exe';ciclos:4500;zip:true),
  (nombre:'Lotus - The Ultimate Challenge';dir:'lotus3';exec:'lotus.exe';zip:true),
  (nombre:'Sword of the Samurai';dir:'swordsam';exec:'samurai.com';extra_param:'-set a20=off';zip:true),
  (nombre:'Igor: Objetivo Uikokahonia';dir:'igor';exec:'igor.exe';extra_param:'-set "file access tries"=0';zip:true),
  (nombre:'Lamborghini - American Challenge';dir:'lac';exec:'lac.exe';ciclos:9600;zip:true),
  (nombre:'Populous';dir:'populous';exec:'pop.bat';zip:true),
  (nombre:'Supaplex';dir:'supaplex';exec:'supaplex.exe';zip:true),
  (nombre:'Crazy Cars II';dir:'ccars2';exec:'cc2ega.exe';ciclos:1500;zip:true),
  (nombre:'F40 Pursuit Simulator';dir:'f40psega';exec:'f40ptl.exe';ciclos:1500;zip:true),
  (nombre:'F40 Pursuit Simulator (CGA)';dir:'f40pscga';exec:'f40.exe';ciclos:1500;zip:true),
  (nombre:'Crazy Cars III';dir:'ccars3';exec:'cc3.com';zip:true),
  (nombre:'Leisure Suir Larry 1 in the Land of the Lounge Lizards (EN)';dir:'lsl1_en';exec:'scidhuv.exe';ciclos:6000;scumm:true;zip:true),
  (nombre:'Leisure Suir Larry 1 in the Land of the Lounge Lizards (ES)';dir:'lsl1_es';exec:'scidhuv.exe';ciclos:6000;scumm:true;zip:true),
  (nombre:'F29 Retaliator';dir:'f29retal';exec:'retal.exe';ciclos:1;zip:true),
  (nombre:'Bad Dudes';dir:'baddudes';exec:'baddudes.exe';ciclos:1000;zip:true),
  (nombre:'Karateka';dir:'karateka';exec:'karateka.exe';ciclos:450;zip:true),
  (nombre:'Gauntlet';dir:'gauntlet';exec:'gauntlet.exe';ciclos:750;grafica:'tandy';zip:true),
  (nombre:'Gauntlet II';dir:'gaunt2';exec:'gauntlet.exe';ciclos:750;zip:true),
  (nombre:'Aladdin';dir:'aladdin';exec:'aladdin.exe';zip:true),
  (nombre:'MadMix Game';dir:'madmix';exec:'madmix.exe';ciclos:450;zip:true),
  (nombre:'MadMix 2 en el Castillo de los Fantasmas';dir:'madmix2';exec:'madmix.exe';ciclos:750;zip:true),
  (nombre:'Titanic';dir:'titanic';exec:'titvga.exe';ciclos:3000;zip:true),
  (nombre:'Lorna';dir:'lorna';exec:'lornaega.com';zip:true),
  (nombre:'Rock''n Roller';dir:'rockroll';exec:'rock.exe';exec_pre:'sbfmdrv.com';ciclos:3000;zip:true),
  (nombre:'Desperado 2';dir:'desp2';exec:'topo.exe';zip:true),
  (nombre:'Veil of Darkness';dir:'veildark';exec:'veil.com';zip:true),
  (nombre:'Magic Boy';dir:'magicboy';exec:'magicboy.exe';zip:true),
  (nombre:'Shinobi';dir:'shinobi';exec:'sh.exe';zip:true),
  (nombre:'Dyna Blaster';dir:'dyna';exec:'dyna.exe';zip:true),
  (nombre:'Darklands';dir:'darkland';exec:'darkland.exe';zip:true),
  (nombre:'Descent';dir:'descent';exec:'descent.bat';params:'-Volume 100';ciclos:1;gus:true;memoria:63;zip:true),
  (nombre:'Hard Hat Mack';dir:'hhmack';exec:'hhmack.img';ciclos:375;memoria:1;zip:true),
  (nombre:'Ancient Art of War,the (EGA)';dir:'war_ega';exec:'waret.exe';ciclos:450;zip:true),
  (nombre:'Ancient Art of War,the (CGA)';dir:'war_cga';exec:'war.exe';ciclos:450;grafica:'cga_composite';zip:true),
  (nombre:'Adventure in Serenia';dir:'serenia';exec:'serenia.img';ciclos:300;grafica:'cga_composite';memoria:1;zip:true),
  (nombre:'Championship Lode Runner';dir:'lodecham';exec:'lodecham.img';ciclos:300;grafica:'cga_composite';memoria:1;zip:true),
  (nombre:'Alien Carnage';dir:'aliencar';exec:'carnage.exe';zip:true),
  (nombre:'Wacky Weels';dir:'wackyw';exec:'ww.exe';ciclos:1;gus:true;zip:true),
  (nombre:'Wing Commander II';dir:'wing2';exec:'wc2.exe';zip:true),
  (nombre:'Wing Commander II: Special Operations I';dir:'wing2';exec:'so1.exe';zip:true),
  (nombre:'Wing Commander II: Special Operations II';dir:'wing2';exec:'so2.exe';zip:true),
  (nombre:'Pitfall II Lost Caverns';dir:'pitfall2';exec:'pitfall2.jrc';ciclos:1000;grafica:'pcjr';zip:true),
  (nombre:'Nebulus';dir:'nebulus';exec:'nebtga.exe';ciclos:750;grafica:'tandy';zip:true),
  (nombre:'Metal Mutant (ES)';dir:'metal_es';exec:'metal.exe';zip:true),
  (nombre:'Metal Mutant (EN)';dir:'metal_en';exec:'metal.exe';zip:true),
  (nombre:'Metal Mutant (FR)';dir:'metal_fr';exec:'metal.exe';zip:true),
  (nombre:'Metal Gear';dir:'metalge';exec:'play.exe';ciclos:3000;zip:true),
  (nombre:'Macadam Bumper';dir:'macadam';exec:'macadam.exe';exec_pre:'mount d [GAME_DIR][RET]d:';ciclos:750;zip:true),
  (nombre:'Moon Walker';dir:'moonwalk';exec:'mw.exe';params:'e';extra_param:'-set a20=off';zip:true),
  (nombre:'Nether World';dir:'netherw';exec:'gamee.exe';exec_pre:'screene.com';zip:true),
  (nombre:'Monty Python''s Flying Circus';dir:'montyp';exec:'pega.exe';zip:true),
  (nombre:'Neverending Story II, the';dir:'never2';exec:'storyii.exe';zip:true),
  (nombre:'Nicky II';dir:'nicky2';exec:'n2crk.com';ciclos:2000;zip:true),
  (nombre:'Nicky Boom';dir:'nicky';exec:'nicky.exe';zip:true),
  (nombre:'Ninja Gaiden';dir:'ninjag';exec:'ninja.exe';ciclos:750;zip:true),
  (nombre:'Ninja Gaiden II - The Dark Sword of Chaos';dir:'ninjag2';exec:'ninja.exe';zip:true),
  (nombre:'Paperboy';dir:'paperboy';exec:'papercg2.exe';zip:true),
  (nombre:'Paperboy 2';dir:'paperb2';exec:'game.exe';zip:true),
  (nombre:'Renegade';dir:'renegade';exec:'renegade.com';exec_pre:'mount a [GAME_DIR][RET]a:';extra_param:'-set a20=off';zip:true),
  (nombre:'R.A.M';dir:'ram';exec:'ram_ega.exe';zip:true),
  (nombre:'Platoon';dir:'platoon';exec:'platoon.exe';ciclos:1000;zip:true),
  (nombre:'Obliterator';dir:'oblitera';exec:'oblit.exe';ciclos:1000;extra_param:'-set a20=off';zip:true),
  (nombre:'Operation Wolf';dir:'opwolf';exec:'wolf.exe';zip:true),
  (nombre:'P-47 the Freedom Fighter';dir:'p47';exec:'p47.com';ciclos:3000;zip:true),
  (nombre:'North & South';dir:'nands';exec:'tatou.com';ciclos:3000;zip:true),
  (nombre:'Last Action Hero';dir:'lasthero';exec:'loader.exe';ciclos:1;zip:true),
  (nombre:'Lethal Weapon';dir:'lethal';exec:'fixmusic.com';zip:true),
  (nombre:'Lion King, the';dir:'lionking';exec:'lionking.exe';gus:true;zip:true),
  (nombre:'Speed Ball II - Brutal Deluxe';dir:'spball2';exec:'sb2.exe';zip:true),
  (nombre:'Toi Acid Game';dir:'toiacid';exec:'toi.exe';ciclos:750;zip:true),
  (nombre:'Ajax';dir:'ajax';exec:'tdy.exe';zip:true),
  (nombre:'Alien Syndrome';dir:'aliensyn';exec:'alien.exe';ciclos:1500;zip:true),
  (nombre:'ScubaVenture';dir:'scuba';exec:'scubavnt.jrc';ciclos:1000;grafica:'pcjr';zip:true),
  (nombre:'Back to the Future II';dir:'bttf2';exec:'bttf2.exe';zip:true),
  (nombre:'Back to the Future III';dir:'bttf3';exec:'chain.com';params:'v r 5';exec_pre:'mount a: [GAME_DIR][RET]a:[RET]cd future';ciclos:4500;zip:true),
  (nombre:'Artura';dir:'artura';exec:'artura.exe';ciclos:3000;zip:true),
  (nombre:'Bionic Comando';dir:'bionicc';exec:'bion.exe';ciclos:1000;extra_param:'-set joysticktype=2axis';mapper:'gng.map';zip:true),
  (nombre:'Blood Money';dir:'bloodm';exec:'bm.exe';extra_param:'-set a20=off';zip:true),
  (nombre:'Ulises';dir:'ulises';exec:'ulises.exe';ciclos:3000;zip:true),
  (nombre:'Magic Pockets';dir:'magicp';exec:'pocket_k.exe';zip:true),
  //
  (nombre:'Game Over';dir:'gameover';exec:'gameover.img';ciclos:750;memoria:1;zip:true),
  (nombre:'Army Moves';dir:'amoves';exec:'amoves.img';ciclos:300;memoria:1;zip:true),
  (nombre:'Arctic Moves';dir:'arcticm';exec:'arctic.exe';exec_pre:'amfix.com';zip:true),
  (nombre:'Batman the Caped Crusader - Joker';dir:'batmancc';exec:'joker.exe';ciclos:3000;zip:true),
  (nombre:'Batman the Caped Crusader - Penguin';dir:'batmancc';exec:'penguin.exe';ciclos:3000;zip:true),
  (nombre:'Batman: The Movie';dir:'batmanm';exec:'batman.exe';ciclos:3000;zip:true),
  (nombre:'Game Over 2';dir:'gameovr2';exec:'goverii.bat';ciclos:300;zip:true),
  (nombre:'Phantis';dir:'phantis';exec:'phantis.exe';ciclos:300;zip:true),
  (nombre:'Blues Brothers, the';dir:'bluesbro';exec:'game.bat';zip:true),
  (nombre:'Blues Brothers: Jukebox Adventure, the';dir:'bluesjuk';exec:'blues.exe';params:'sb';zip:true),
  (nombre:'After Burner II';dir:'AFTERB2';exec:'AB.EXE';grafica:'tandy';memoria:1;zip:true),
  (nombre:'Altered Beast';dir:'ABEAST';exec:'BEASTY.EXE';zip:true),
  (nombre:'Quest for Glory I - So you want to be a Hero (VGA)';dir:'QG1_VGA';exec:'SCIDHUV.EXE';scumm:true;zip:true),
  (nombre:'Discworld/Mundodisco';dir:'DISCW';exec:'disc.bat';gus:true;scumm:true;zip:true),
  (nombre:'Maniac Mansion (ES)';dir:'MANIACES';exec:'maniac.exe';params:'p';grafica:'tandy';scumm:true;memoria:1;zip:true),
  (nombre:'Maniac Mansion (EN)';dir:'MANIACEN';exec:'maniac.exe';params:'p';grafica:'tandy';scumm:true;memoria:1;zip:true),
  (nombre:'Maniac Mansion (OLD EN)';dir:'MANIACO';exec:'maniac.exe';scumm:true;memoria:1;zip:true)
);

implementation

end.
