unit games_info;

{$ifdef fpc}{$mode delphi}{$H+}{$endif}

interface
uses games_data;

type
  tipo_info=record
    year:string;
    company:string;
    manual:string;
    map:string;
    guia:string;
    image_name:string;
    idioma:integer;
    tipo:integer;
    mensaje:string;
  end;
const
  //Idiomas
  ESP=1;
  ING=2;
  ALE=4;
  FRA=8;
  ITA=$10;
  MUL=$20;
  //Tipo Juego
  AG=1;
  ARCADE=2;
  TRESD=4;
  SIMULA=8;
  SPORT=$10;
  PUZ=$20;
  RPG=$40;
  COCHES=$80;
  //Mensajes
  GAME_INFO:array[0..(GAME_TOTAL-1)] of tipo_info=(
  (year:'1984';company:'Datasoft Inc.';manual:'brucelee_manual.pdf';image_name:'brucelee';tipo:ARCADE;mensaje:'Al empezar pulsa A para elegir "Composite monitor"[RET]Teclas remapeadas:[RET]Teclas de cursor --> Moverse[RET]CONTROL --> Disparo'),
  (year:'1993';company:'Interplay';manual:'lostvikings_manual.pdf';image_name:'vikings';tipo:ARCADE;mensaje:'Si el juego no arranca, ejecuta el setup'),
  (year:'1987';company:'Sierra';manual:'kq1_manual.pdf';map:'kq1\';guia:'kq1_wt_1.txt$kq1_wt_2.html';image_name:'kq1';tipo:AG),
  (manual:'kq2_manual.pdf';map:'kq2\';image_name:'kq2';tipo:AG),
  (manual:'kq3_manual.pdf';map:'kq3_map.gif';image_name:'kq3';tipo:AG),
  (manual:'indyfa_manual_es.pdf$indyfa_Libro de Pistas.pdf$indyfa_comic.pdf';image_name:'indyfa';idioma:ESP;tipo:AG),
  (manual:'indyfa_manual_en.pdf$indyfa_comic.pdf';image_name:'indyfa';idioma:ING;tipo:AG),
  (manual:'indyfa_comic.pdf';image_name:'indyfa';idioma:ALE;tipo:AG),
  (image_name:'3stooges';tipo:ARCADE),
  (image_name:'darkf';idioma:ESP;tipo:TRESD or ARCADE),
  (manual:'alitd1_manual_es.pdf$alitd1_newspaper_es.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:ESP;tipo:AG),
  (manual:'alitd1_manual_en.pdf$alitd1_Newspaper.pdf$alitd1_cluebook.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:ING;tipo:AG),
  (manual:'alitd1_manual.pdf$alitd1_Newspaper.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:ALE;tipo:AG),
  (manual:'alitd1_manual.pdf$alitd1_Newspaper.pdf';guia:'alitd1_wt.txt';image_name:'alitd';idioma:FRA;tipo:AG),
  (manual:'alitd2_manual.pdf';guia:'alitd2_wt.txt';image_name:'alitd2';idioma:ESP;tipo:AG),
  (manual:'amazings_manual.pdf';image_name:'spidey';tipo:ARCADE;mensaje:'Al empezar pulsa 1 para seleccionar VGA'),
  (manual:'outworld_manual.pdf$outworld_refcard.pdf$outworld_Instruction-Booklet.pdf';image_name:'world';tipo:ARCADE or PUZ;mensaje:'Al empezar pulsa 1 para continuar'),
  (image_name:'dn1';tipo:ARCADE),
  (image_name:'dn2';tipo:ARCADE),
  (image_name:'dn3';tipo:ARCADE),
  (image_name:'nukem2';tipo:ARCADE),
  (image_name:'doc';tipo:SIMULA;mensaje:'Al empezar pulsa cualquier tecla para seleccionar 16 colores'),
  (guia:'gobliiins_codes.txt';image_name:'gob';tipo:AG or PUZ;mensaje:'Tras elegir el idioma, pulsa S para validar y pulsa E para elegir sonido SoundBlaster'),
  (image_name:'gob2';idioma:ESP;tipo:AG or PUZ),
  (image_name:'gob2';idioma:ING;tipo:AG or PUZ),
  (image_name:'gob2';idioma:ITA;tipo:AG or PUZ),
  (image_name:'gob2';idioma:ALE;tipo:AG or PUZ),
  (manual:'gods_manual.pdf$gods_card.pdf';map:'gods\';image_name:'gods';tipo:ARCADE),
  (manual:'alleycat_manual.pdf';image_name:'alleycat';tipo:ARCADE),
  (year:'1990';company:'Opera Soft';manual:'rescategolfo_manual.pdf';image_name:'rescate';tipo:ARCADE;mensaje:'Al empezar pulsa F4 para seleccionar VGA[RET]Después pulsa F2 para sonido Adlib'),
  (year:'1987';company:'Sierra';manual:'lsl1_manual.pdf$lsl1_reference_card.pdf';map:'lsl1\';guia:'lsl1_wt.txt';image_name:'lsl1';tipo:AG),
  (image_name:'streetr';tipo:SIMULA or COCHES;mensaje:'Al empezar pulsa 3 para seleccionar VGA'),
  (image_name:'streetr2';tipo:SIMULA or COCHES;mensaje:'Al empezar pulsa 3 para seleccionar VGA[RET]Después pulsa 1 para seleccionar sonido Adlib'),
  (manual:'wrathd_manual_en.pdf$wrathd_manual_multi.pdf';image_name:'wrath';tipo:ARCADE;mensaje:'Al empezar pulsa 3 para seleccionar VGA[RET]Después pulsa 4 para seleccionar sonido Roland'),
  (manual:'speedball_manual.pdf';image_name:'speedb';tipo:SIMULA or SPORT;mensaje:'Cuando pregunte por la tarjeta gráfica, pulsa F2 para seleccionar "EGA 256Kb"'),
  (manual:'pop_manual.pdf$pop_manual_es.pdf';image_name:'prince';tipo:ARCADE),
  (image_name:'osb';tipo:PUZ),
  (image_name:'push';tipo:PUZ),
  (image_name:'rampart';tipo:SIMULA or ARCADE),
  (image_name:'rott';tipo:TRESD or ARCADE),
  (image_name:'riskyw';idioma:ING;tipo:ARCADE),
  (image_name:'warcraft';tipo:SIMULA;mensaje:'Si el juego falla ejecuta el setup y despues selecciona "Save settings and exit"'),
  (image_name:'lhx';tipo:SIMULA),
  (manual:'Loom_manual_es.pdf$Loom_Libro de Pistas.pdf$Loom_El Libro de los Patrones.pdf';guia:'loom.txt';image_name:'loom';idioma:ESP;tipo:AG),
  (manual:'Loom_manual_en.pdf$Loom_Book-of-Patterns.pdf$Loom_Hint book.pdf$Loom_Quick Reference Card.pdf';guia:'loom.txt';image_name:'loom';idioma:ING;tipo:AG),
  (guia:'loom.txt';image_name:'loom';idioma:ALE;tipo:AG),
  (manual:'Loom_manuel_fr.pdf$Loom_Carte de référence.pdf$Loom_Cahier de Trames.pdf$Loom_Livre des astuces.pdf';guia:'loom.txt';image_name:'loom';idioma:FRA;tipo:AG),
  (image_name:'monkey';idioma:ESP;tipo:AG),
  (image_name:'monkey';idioma:ING;tipo:AG),
  (manual:'kq4_manual.pdf';image_name:'kq4';tipo:AG),
  (manual:'lsl6_manual_es.pdf$lsl6_hintbook.pdf$lsl6_RC.pdf';image_name:'lsl6';idioma:ESP;tipo:AG),
  (image_name:'monkey_ega';idioma:ESP;tipo:AG),
  (manual:'PoliDiaz_manual.pdf';image_name:'polidiaz';tipo:SPORT;mensaje:'Al empezar pulsa F4 para seleccionar VGA[RET]Después pulsa F2 para sonido Adlib'),
  (manual:'kq1_manual.pdf';map:'kq1\';guia:'kq1_wt_1.txt$kq1_wt_2.html';image_name:'kq1_cga';tipo:AG),
  (manual:'Archon_manual.pdf$Archon_RF.pdf';image_name:'archon';tipo:SIMULA),
  (image_name:'archonu';tipo:SIMULA),
  (manual:'doom_manual.pdf$doom_RF.pdf$doom_guide.pdf';image_name:'doom';tipo:TRESD or ARCADE),
  (image_name:'doc_cga';tipo:SIMULA),
  (manual:'doom2_manual.pdf$doom2_RF.pdf$doom2_guide.pdf';image_name:'doom2';tipo:TRESD or ARCADE),
  (image_name:'heretic';tipo:TRESD or ARCADE),
  (image_name:'raptor';tipo:ARCADE),
  (manual:'immortal_manual.pdf$immortal_RF.pdf$immortal_cluebook.pdf';image_name:'immortal';tipo:RPG),
  (manual:'cruise_manual.pdf';map:'cruise.jpg';image_name:'cruise';idioma:ESP;tipo:AG),
  (image_name:'commando';tipo:ARCADE),
  (manual:'Caveman_manual.pdf';image_name:'caveman';tipo:ARCADE),
{65}  (manual:'uridium_manual.pdf';image_name:'uridium';tipo:ARCADE;mensaje:'Teclas remapeadas:[RET]Teclas de cursor --> Moverse[RET]CONTROL --> Disparo'),
  (manual:'conquest_manual.pdf$conquests_hint book.pdf';map:'conquests of Camelot.jpg';image_name:'camelot';tipo:AG),
  (manual:'dott_manual_es.pdf$dott_Libro de Pistas.pdf$dott_Tarjeta Referencia.pdf';image_name:'dott';idioma:ESP;tipo:AG),
  (manual:'kq5_manual_es.pdf$kq5_Hint Book.pdf';map:'kq5\';image_name:'kq5';idioma:ESP;tipo:AG),
  (image_name:'kq6';idioma:ESP;tipo:AG),
  (manual:'mi2_manual_es.pdf$mi2_Tarjeta de Referencia.pdf';image_name:'monkey2';idioma:ESP;tipo:AG),
  (image_name:'robocop';tipo:ARCADE),
  (image_name:'robocop3';tipo:ARCADE),
  (manual:'kyrandia_manual_es.pdf$kyrandia_Libro de Pistas.pdf';image_name:'kyran';idioma:ESP;tipo:AG),
  (manual:'kyrandia2_manual.pdf';image_name:'hof';idioma:ESP;tipo:AG),
  (manual:'sq1_manual.pdf$sq1_Reference Card.pdf';image_name:'sq1';tipo:AG),
  (manual:'sq1_manual_r_es.pdf$sq1_Hintbook.pdf';image_name:'sq1_vga';idioma:ESP;tipo:AG),
  (manual:'sq1_Hintbook.pdf';image_name:'sq1_ega';idioma:ING;tipo:AG),
  (manual:'SQ2_manual.pdf$SQ2_HB.pdf$SQ2_Space_Piston.pdf';image_name:'sq2';tipo:AG),
  (manual:'SQ3_manual.pdf$SQ3_HB.pdf';image_name:'sq3';tipo:AG),
  (image_name:'vikingc';tipo:ARCADE),
  (manual:'pop2_manual.pdf$pop2_manual_es.pdf';image_name:'prince2';tipo:ARCADE),
  (image_name:'paratrooper';tipo:ARCADE),
{83}  (manual:'lsl2_manual.pdf$lsl2_HintBook.pdf';image_name:'lsl2';tipo:AG;mensaje:'En la protección, el número de teléfono siempre es 7448'),
  (manual:'lsl3_Manual.pdf$lsl3_Postcard.pdf$lsl3_HintBook.pdf';image_name:'lsl3';tipo:AG),
  (image_name:'doh';tipo:ARCADE),
  (manual:'bchess_manual_en.pdf$bchess_manual_fr.pdf';image_name:'bchess_ega';tipo:SIMULA OR SPORT),
  (manual:'bchess_manual_en.pdf$bchess_manual_fr.pdf';image_name:'bchess';tipo:SIMULA or SPORT),
  (image_name:'bchess2';tipo:SIMULA or SPORT),
  (image_name:'bc4000';tipo:SIMULA or SPORT),
  (image_name:'bc4000_low';tipo:SIMULA OR SPORT),
  (manual:'ikariwarriors_manual.pdf$ikariwarriors_manual_alt.pdf';image_name:'ikariw';tipo:ARCADE;mensaje:'Al empezar, pulsa ENTER'),
  (manual:'alitd3_manual.pdf$alitd3_The Mystery Examiner.pdf';image_name:'alitd3';idioma:ESP;tipo:AG),
  (manual:'gob3_manual.pdf$gob3_hint Book.pdf';image_name:'gob3';idioma:ESP;tipo:AG or PUZ),
  (manual:'bargon_manual.pdf';image_name:'bargon';idioma:ESP;tipo:AG;mensaje:'Solo puedes seleccionar el idioma ESPAÑOL! Pulsa D[RET]Despues pulsa S para validar y E para sonido SoundBlaster'),
{95}  (image_name:'bargon';idioma:ING;tipo:AG;mensaje:'You can only select the ENGLISH language! Press C[RET]Then press Y to validate and E for SoundBlaster sound'),
  (image_name:'rastan';tipo:ARCADE),
  (image_name:'karnov';tipo:ARCADE;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (image_name:'goody';tipo:ARCADE),
  (image_name:'tapper';tipo:ARCADE),
  (manual:'living2_manual.pdf';image_name:'lvs2';tipo:ARCADE;mensaje:'Al empezar pulsa F4 para seleccionar VGA'),
  (image_name:'vroad';tipo:ARCADE),
  (manual:'Julius_Erving_and_Larry_Bird_Go_One_on_One_Manual.pdf';image_name:'1on1';tipo:ARCADE),
  (manual:'solnegro_manual.pdf';image_name:'solnegro';tipo:ARCADE;mensaje:'Al empezar pulsa F4 para seleccionar VGA'),
  (manual:'solnegro_manual.pdf';image_name:'solnegro_cga';tipo:ARCADE),
  (manual:'FreddyHardest_manual.pdf';image_name:'freddyh';tipo:ARCADE),
  (manual:'fhsm_manual.pdf';image_name:'fhsm';tipo:ARCADE),
  (manual:'lastmission_manual.pdf';image_name:'lmission';tipo:ARCADE),
  (image_name:'im2';tipo:ARCADE),
{109}  (manual:'kq2_manual.pdf';map:'kq2\';image_name:'kq2_b';tipo:AG;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (manual:'kq5_manual_es.pdf$kq5_Hint Book.pdf';map:'kq5\';image_name:'kq5_ega';idioma:ESP;tipo:AG),
  (image_name:'thexder';tipo:ARCADE),
  (image_name:'thexder2';tipo:ARCADE),
{113}  (manual:'TestDrive_manual.pdf';image_name:'testdrive';tipo:COCHES or SIMULA;mensaje:'Al empezar pulsa 2 para seleccionar EGA'),
  (year:'1987';company:'Opera Soft';manual:'livingstonesupongo_manual.pdf';image_name:'living';tipo:ARCADE),
  (image_name:'ccomic';tipo:ARCADE),
  (image_name:'ccomic2';tipo:ARCADE),
  (image_name:'corsarios';tipo:ARCADE;mensaje:'Al empezar pulsa F3 para seleccionar EGA'),
  (manual:'prehistorik_manual.pdf';image_name:'prehist';tipo:ARCADE),
  (manual:'prehistorik2_manual.pdf';image_name:'prehist2';tipo:ARCADE),
  (image_name:'titusfox';tipo:ARCADE),
  (image_name:'ikari3';tipo:ARCADE),
  (manual:'babyjo_manual.pdf$babyjo_manual_es.pdf';image_name:'babyjo';tipo:ARCADE),
  (image_name:'narcop';tipo:ARCADE),
  (manual:'Emmanuelle_manual_es.pdf';image_name:'emmanuelle';idioma:ESP;tipo:AG),
  (manual:'emmanuelle_claves.pdf';image_name:'emmanuelle';idioma:ING;tipo:AG),
  (manual:'turrican2_manual.pdf';image_name:'turrican2';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (image_name:'ckeen1';tipo:ARCADE),
  (image_name:'ckeen2';tipo:ARCADE),
  (image_name:'ckeen3';tipo:ARCADE),
  (image_name:'ckeen4';tipo:ARCADE),
  (image_name:'ckeen5';tipo:ARCADE),
  (image_name:'ckeen6';tipo:ARCADE),
  (image_name:'kdreams';tipo:ARCADE),
  (manual:'coolcroc_twins_manual.pdf';image_name:'coolcroc';tipo:ARCADE),
  (manual:'coolworld_manual.pdf$coolworld_rc.pdf';image_name:'coolwrld';tipo:ARCADE),
  (manual:'flashback_manual.pdf$flashback_manual_alt.pdf';image_name:'flashback';tipo:ARCADE),
  (manual:'jazzjackrabbit_manual.pdf$jazzjackrabbit_manual_alt.pdf';image_name:'jazzjack';tipo:ARCADE),
  (image_name:'jazzhh';tipo:ARCADE),
  (manual:'la_abadia_del_crimen_manual.pdf';map:'AbadiaDelCrimen.jpg';image_name:'abadia';tipo:ARCADE or PUZ),
  (manual:'aaargh_manual.pdf';image_name:'aaargh';tipo:ARCADE),
  (manual:'budokan_manual.pdf';image_name:'budokan';tipo:SPORT),
  (manual:'bubblebobble_manual.pdf';image_name:'bubble';tipo:ARCADE),
  (manual:'blackthorne_manual.pdf';image_name:'bthorne';tipo:ARCADE),
  (manual:'radwarrior_manual.pdf';image_name:'radwar';tipo:ARCADE),
{145}  (manual:'gng_manual.pdf$gng_RF.pdf';image_name:'gng';tipo:ARCADE;mensaje:'Joystick remapeado a teclado:[RET]A --> Arriba[RET]Z --> Abajo[RET]O --> Izquierda[RET]P --> Derecha[RET]ESPACIO --> Disparo'),
  (image_name:'abreed';tipo:ARCADE),
  (image_name:'ta';tipo:ARCADE),
  (image_name:'abuse';tipo:ARCADE),
  (image_name:'alf';tipo:ARCADE),
  (image_name:'alkatraz';tipo:ARCADE),
  (manual:'kq4_manual.pdf';image_name:'kq4_agi';tipo:AG),
  (manual:'ecoquest_manual.pdf$ecoquest_hintbook.pdf$ecoquest_econoticias.pdf';image_name:'ecoq';idioma:ESP;tipo:AG),
  (manual:'ecoquest2_manual.pdf$ecoquest2_hintbook.pdf$ecoquest2_econews.pdf';image_name:'ecoq2';idioma:ESP;tipo:AG),
{154}  (manual:'goldenaxe_manual.pdf';image_name:'goldaxe';tipo:ARCADE;mensaje:'Al empezar pulsa 4 para seleccionar VGA'),
  (manual:'megaphoenix_manual.pdf';image_name:'mphoenix';tipo:ARCADE),
  (manual:'satan_manual.pdf';image_name:'satan';tipo:ARCADE;mensaje:'Al empezar pulsa 3/4 para seleccionar EGA'),
  (manual:'afterwar_manual.pdf$afterwar_manual_es.pdf';image_name:'afterwar';tipo:ARCADE),
  (manual:'quake_manual.pdf';image_name:'quake';tipo:TRESD),
  (manual:'wolfenstein3d_manual.pdf$wolfenstein3d_HB.pdf';image_name:'wolf3d';tipo:TRESD),
  (manual:'spearofdestiny_manual.pdf$spearofdestiny_HB.pdf';image_name:'spear';tipo:TRESD),
  (manual:'castlewolfenstein_manual.pdf$castlewolfenstein_RC.pdf';image_name:'cw';tipo:ARCADE),
  (manual:'dkong_manual.pdf';image_name:'dkong';tipo:ARCADE),
  (manual:'ddragon_manual.pdf';image_name:'ddragon';tipo:ARCADE;mensaje:'Al empezar pulsa 2 para seleccionar EGA'),
{164}  (manual:'ddragon2_manual.pdf$ddragon2_manual_alt.pdf';image_name:'ddragon2';tipo:ARCADE;mensaje:'Al empezar pulsa 4 para seleccionar VGA'),
  (manual:'dukenukem3D_manual.pdf';image_name:'duke3d';tipo:ARCADE),
  (manual:'lemmings_manual.pdf';image_name:'lemmings';tipo:PUZ),
  (manual:'lemmings2_manual.pdf$lemmings2_story.pdf';image_name:'lemmings2';tipo:PUZ),
  (manual:'mortalkombat_manual.pdf$mortalkombat_comic.pdf';image_name:'mkombat';tipo:ARCADE),
  (manual:'mortalkombat2_manual.pdf$mortalkombat2_comic.pdf';image_name:'mkombat2';tipo:ARCADE),
  (manual:'sf_manual.pdf';image_name:'sf';tipo:ARCADE;mensaje:'Joystick remapeado a teclado:[RET]Teclas de cursor --> Movimiento[RET]Control --> Patada[RET]Alt --> Puño'),
  (manual:'sf2_manual.pdf';image_name:'sf2';tipo:ARCADE),
  (manual:'slugger_manual.pdf';image_name:'slugger';tipo:SPORT),
  (manual:'blackcauldron_manual.pdf$blackcauldron_HB.pdf$blackcauldron_RC.pdf';map:'blackcauldron.jpg';image_name:'bcauld';tipo:AG),
  (manual:'zona0_manual.pdf';image_name:'zona0';tipo:ARCADE;mensaje:'Al empezar pulsa 3 para seleccionar VGA'),
  (manual:'jumpman_manual.pdf';image_name:'jumpman';tipo:ARCADE;mensaje:'Al empezar pulsa C para elegir "Composite monitor"'),
  (manual:'VCT_Manual.pdf';image_name:'vct';tipo:ARCADE;mensaje:'Pulsa [KEY_DISK] para intercambiar los discos cuando lo pida'),
  (image_name:'riskyw';idioma:ESP;tipo:ARCADE),
  (manual:'simant_manual.pdf$simant_startguide.pdf';image_name:'simant';tipo:ARCADE),
  (image_name:'ark_cga';tipo:ARCADE),
  (manual:'arkanoid_manual.pdf';image_name:'arkanoid';tipo:ARCADE),
  (manual:'epicpinball_manual.pdf';image_name:'epicpin';tipo:ARCADE),
  (manual:'jill_manual.pdf';image_name:'jill';tipo:ARCADE),
  (image_name:'dd3';tipo:ARCADE;mensaje:'Al empezar pulsa M para seleccionar Roland'),
  (manual:'qg1_manual.pdf$qg1_manual_tech.pdf$qg1_RF.pdf';image_name:'qg1';tipo:RPG),
  (manual:'qg2_manual.pdf$qg2_manual_tech.pdf$qg2_HB.pdf';map:'qg2_map.pdf';image_name:'qg2';tipo:RPG),
  (manual:'qg3_manual.pdf$qg3_tech_manual.pdf$qg3_RF.pdf$qg3_HB.pdf';image_name:'qg3';tipo:RPG),
  (manual:'qg4_manual.pdf$qg4_RF.pdf$qg4_guide.pdf$qg4_HB.pdf';image_name:'qg4';tipo:RPG),
  (manual:'loderunner_manual.pdf';image_name:'loderunn';tipo:ARCADE),
  (manual:'montezumasrevenge_manual.pdf';image_name:'montezum';tipo:ARCADE),
  (manual:'poleposition_manual.pdf';image_name:'polepos';tipo:ARCADE),
  (manual:'chipschallenge_manual.pdf';image_name:'chipsc';tipo:PUZ;mensaje:'Al empezar pulsa 4 (VGA) y A (Roland), despues ENTER'),
  (manual:'mule_manual.pdf';image_name:'mule';tipo:SIMULA),
  (manual:'crazycars_manual.pdf';image_name:'ccars';tipo:COCHES),
  (manual:'luigispaghetti_manual.pdf';image_name:'luigispa';tipo:ARCADE),
  (image_name:'luigi2';tipo:ARCADE),
  (manual:'blackcauldron_manual.pdf$blackcauldron_HB.pdf$blackcauldron_RC.pdf';map:'blackcauldron.jpg';image_name:'bcauld';tipo:AG;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (manual:'MK3_manual.pdf$MK3_guide.pdf';image_name:'mk3';tipo:ARCADE),
  (manual:'Dune2 manual.pdf';image_name:'dune2';idioma:ESP;tipo:SIMULA),
  (manual:'Indy3_manual.pdf$Indy3_Diario del Grial.pdf$Indy3_Libro de Pistas.pdf';image_name:'indy3';idioma:ESP;tipo:AG),
  (manual:'Heimdall_manual.pdf';map:'Heimdall_maps.pdf';image_name:'heim';tipo:ARCADE),
  (manual:'tyrian_manual.pdf';image_name:'tyrian';tipo:ARCADE),
  (manual:'eprm_manual.pdf';image_name:'escape';tipo:ARCADE;mensaje:'Pulsa 5 para VGA y luego enter[RET]Teclas de P1 remapeadas[RET]Teclas de cursor --> Moverse[RET]CONTROL --> Disparo'),
  (manual:'simcity_manual.pdf';image_name:'simcity';tipo:SIMULA),
  (manual:'sc2000_manual.pdf$sc2000_RF.pdf';image_name:'sc2000';tipo:SIMULA),
  (manual:'wingcommander_manual.pdf';image_name:'wingcomm';tipo:SIMULA),
  (manual:'wingcommander_manual.pdf';image_name:'wingcomm';tipo:SIMULA),
  (manual:'lotus3_manual.pdf$lotus3_RF.pdf';image_name:'lotus3';tipo:COCHES;mensaje:'En la proteccion pulsa ENTER'),
  (manual:'swordsamurai_manual.pdf$swordsamurai_RF.pdf';map:'swordsamurai_map.pdf';image_name:'swordsam';tipo:SIMULA;mensaje:'Tras el joystick selecciona 1 para VGA y después 5 para Roland'),
  (manual:'igor_manual.pdf';image_name:'igor';idioma:ESP;tipo:AG),
  (year:'1992';company:'Titus France SA';manual:'lac_manual.pdf';image_name:'lac';tipo:COCHES),
  (manual:'populous_manual.pdf$populous_RF.pdf';image_name:'populous';tipo:SIMULA),
  (manual:'supaplex_manual.pdf';image_name:'supaplex';tipo:ARCADE),
  (manual:'crazycars2_manual_ES.pdf$F40_manual.pdf';image_name:'cc2';tipo:COCHES),
  (manual:'crazycars2_manual_ES.pdf$F40_manual.pdf';image_name:'f40ega';tipo:COCHES),
  (manual:'crazycars2_manual_ES.pdf$F40_manual.pdf';image_name:'f40cga';tipo:COCHES),
  (manual:'lotus3_manual.pdf$lotus3_RF.pdf';image_name:'cc3';tipo:COCHES;mensaje:'Colocate en SOUND y pulsa espacio hasta seleccionar "SoundBlaster"'),
  (manual:'lsl1\';image_name:'lsl1_vga';idioma:ING;tipo:AG),
  (manual:'lsl1\';image_name:'lsl1_vga';idioma:ESP;tipo:AG),
  (image_name:'f29';tipo:SIMULA),
  (manual:'baddudes_manual.pdf';image_name:'baddudes';tipo:ARCADE;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (manual:'karateka_manual.pdf';image_name:'karateka';tipo:ARCADE),
  (manual:'gauntlet_manual.pdf';image_name:'gaunt';tipo:ARCADE),
  (manual:'gauntlet2_manual.pdf';image_name:'gaunt2';tipo:ARCADE),
  (manual:'aladdin_manual.pdf$aladdin_RF.pdf';image_name:'aladdin';tipo:ARCADE;mensaje:'En la proteccion, pulsa ENTER'),
  (manual:'madmix_manual.pdf';image_name:'madmix';tipo:ARCADE),
  (manual:'madmix2_manual.pdf';image_name:'madmix2';tipo:ARCADE),
  (image_name:'titanic';tipo:ARCADE),
  (manual:'lorna_manual.pdf';image_name:'lorna';tipo:ARCADE),
  (image_name:'rockroll';tipo:ARCADE;mensaje:'Pulsa 2 para seleccionar VGA'),
  (manual:'desperado2_manual.pdf';image_name:'desp2';tipo:ARCADE),
  (manual:'veil_manual.pdf$veil_hints.pdf$veil_RF.pdf';image_name:'veil';tipo:RPG),
  (manual:'magicboy_manual.pdf$magicboy_RF.pdf';image_name:'magicboy';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (manual:'shinobi_manual.pdf';image_name:'shinobi';tipo:ARCADE;mensaje:'Pulsa ENTER para seleccionar EGA'),
  (manual:'dynablaster_manual.pdf$dynablaster_RF.pdf';image_name:'dyna';tipo:ARCADE),
  (manual:'darklands_manual.pdf$darklands_cluebook.pdf$darklands_RF.pdf';map:'darklands_map.pdf';image_name:'darkland';tipo:RPG),
  (image_name:'descent';tipo:ARCADE),
  (image_name:'hhmack';tipo:ARCADE),
  (manual:'ancient_manual.pdf$ancient_RF.pdf';image_name:'warega';tipo:ARCADE),
  (manual:'ancient_manual.pdf$ancient_RF.pdf';image_name:'warcga';tipo:ARCADE),
  (manual:'serenia_manual.pdf';image_name:'serenia';tipo:AG),
  (image_name:'lodecham';tipo:ARCADE),
  (manual:'aliencarnage_manual.pdf';image_name:'aliencar';tipo:ARCADE),
  (manual:'wackywheels_manual.pdf';image_name:'wackyw';tipo:ARCADE),
  (image_name:'wing2';tipo:SIMULA),
  (image_name:'wing2so1';tipo:SIMULA),
  (image_name:'wing2so2';tipo:SIMULA),
  (manual:'pitfall2_manual.pdf';image_name:'pitfall2';tipo:ARCADE),
  (manual:'nebulus_manual.pdf';image_name:'nebulus';tipo:ARCADE),
  (manual:'metalmutant_manual.pdf';image_name:'metal';idioma:ESP;tipo:ARCADE;mensaje:'Pulsa F2 para VGA'),
  (manual:'metalmutant_manual.pdf';image_name:'metal';idioma:ING;tipo:ARCADE;mensaje:'Press F2 for VGA'),
  (manual:'metalmutant_manual.pdf';image_name:'metal';idioma:FRA;tipo:ARCADE;mensaje:'Appuyez sur F2 pour VGA'),
  (manual:'metalgear_manual.pdf';map:'metalgear_map.pdf';image_name:'metalge';tipo:ARCADE;mensaje:'Pulsa ENTER tres veces para empezar'),
  (manual:'macadam_manual.pdf';image_name:'macadam';tipo:ARCADE),
  (manual:'moonwalker_manual.pdf';image_name:'moonwalk';tipo:ARCADE),
  (manual:'netherworld_manual.pdf';image_name:'netherw';tipo:ARCADE),
  (manual:'montyp_manual.pdf';image_name:'montyp';tipo:ARCADE),
  (manual:'neverending2_manual.pdf';image_name:'story2';tipo:ARCADE;mensaje:'Pulsa 3 para seleccionar VGA'),
  (image_name:'nicky2';tipo:ARCADE;mensaje:'Pulsa 1 para empezar'),
  (manual:'nickyboom_manual.pdf';image_name:'nicky';tipo:ARCADE;mensaje:'Pulsa 1 para empezar'),
  (manual:'ninjagaiden_RF.pdf';image_name:'ninjag';tipo:ARCADE;mensaje:'Selecciona graficos EGA y luego ENTER'),
  (image_name:'ninjag2';tipo:ARCADE),
  (manual:'paperboy_manual.pdf';image_name:'paperboy';tipo:ARCADE),
  (manual:'paperboy2_manual.pdf';image_name:'paperboy2';tipo:ARCADE),
  (manual:'renegade_manual.pdf';image_name:'renegade';tipo:ARCADE;mensaje:'Pulsa ENTER dos veces para empezar'),
  (image_name:'ram';tipo:ARCADE),
  (manual:'platoon_manual.pdf';image_name:'platoon';tipo:ARCADE),
  (manual:'obliterator_manual.pdf';image_name:'oblit';tipo:ARCADE;mensaje:'Pulsa 2 y despues N'),
  (manual:'operationwolf_manual.pdf';image_name:'opwolf';tipo:ARCADE),
  (manual:'p47_manual.pdf';image_name:'p47';tipo:ARCADE),
  (manual:'n&s_manual.pdf';image_name:'nands';tipo:SIMULA;mensaje:'Pulsa F1 para empezar'),
  (image_name:'lasth';tipo:ARCADE;mensaje:'Pulsa 1 para empezar'),
  (manual:'lethalweapon_manual.pdf$lethalweapon_RF.pdf';image_name:'lethalw';tipo:ARCADE),
  (manual:'lionking_manual.pdf';image_name:'lionking';tipo:ARCADE;mensaje:'En la proteccion, pulsa ENTER'),
  (manual:'speedball2_manual.pdf$speedball2_RF.pdf$speedball2_programme.pdf';image_name:'sball2';tipo:ARCADE),
  (manual:'tioacid_manual.pdf';image_name:'toiacid';tipo:ARCADE),
  (image_name:'ajax';tipo:ARCADE;mensaje:'Pulsa ENTER para seleccionar EGA'),
  (manual:'aliensyndrome_manual.pdf$aliensyndrome_RF.pdf';image_name:'aliensyn';tipo:ARCADE),
  (image_name:'scuba';tipo:ARCADE),
  (manual:'bttf2_manual.pdf';image_name:'bttf2';tipo:ARCADE;mensaje:'Pulsa B para seleccionar Adlib y despues 4 para VGA'),
  (manual:'bttf3_manual.pdf$bttf3_manual_es.pdf';image_name:'bttf3';tipo:ARCADE),
  (manual:'artura_RF.pdf';map:'artura_map.pdf';image_name:'artura';tipo:ARCADE;mensaje:'Pulsa 3 para seleccionar EGA'),
  (manual:'bioniccommando_manual.pdf';image_name:'bionicc';tipo:ARCADE;mensaje:'Joystick remapeado a teclado:[RET]A --> Arriba[RET]Z --> Abajo[RET]O --> Izquierda[RET]P --> Derecha[RET]ESPACIO --> Disparo'),
  (manual:'bloodmoney_manual.pdf';image_name:'bloodm';tipo:ARCADE),
  (manual:'ulises_manual.pdf';image_name:'ulises';tipo:ARCADE;mensaje:'Pulsa F3 paraseleccionar EGA'),
  (manual:'magicpockets_manual.pdf$magicpockets_story.pdf';image_name:'magicp';tipo:ARCADE),
  (manual:'gameover.pdf';map:'gameover.pdf';image_name:'gameover';tipo:ARCADE),
  (image_name:'armymoves';tipo:ARCADE),
  (manual:'arcticmoves_manual.pdf';image_name:'arcticmoves';tipo:ARCADE),
  (manual:'batmancc_manual.pdf';image_name:'batmancc';tipo:ARCADE),
  (manual:'batmancc_manual.pdf';image_name:'batmancc';tipo:ARCADE),
  (image_name:'batmanm';tipo:ARCADE;mensaje:'Pulsa 4 para VGA'),
  (image_name:'gameover2';tipo:ARCADE),
  (image_name:'phantis';tipo:ARCADE),
  (manual:'bluesbrothers_manual.pdf$bluesbrothers_ref.pdf';image_name:'bluesbro';tipo:ARCADE),
  (image_name:'bluesjuk';tipo:ARCADE),
  (manual:'afterburnerII_manual.pdf';image_name:'afterb2';tipo:ARCADE;mensaje:'Pulsa 4 para seleccionar Tandy'),
  (manual:'alteredbeast_manual.pdf';image_name:'altbeast';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (manual:'qg1_manual.pdf$qg1_manual_tech.pdf$qg1_RF.pdf';image_name:'qg1_vga';tipo:RPG),
  (manual:'Mundodisco_manual (ES).pdf$Discworld_manual (EN).pdf$Discworld_HB.pdf';image_name:'discw';idioma:MUL;tipo:ARCADE),
  (manual:'ManiacMansion_ Manual_ES.pdf$ManiacMansion_Claves.pdf$ManiacMansion_Libro _Pistas.pdf';image_name:'maniac';idioma:ESP;tipo:AG),
  (manual:'ManiacMansion_Manual_EN.pdf$ManiacMansion_Claves.pdf$ManiacMansion_Hintbook.pdf';image_name:'maniac';idioma:ING;tipo:AG),
  (manual:'ManiacMansion_old_RF.pdf';image_name:'maniac_old';idioma:ING;tipo:AG),
  (manual:'arthurtt_manual.pdf';image_name:'arthurtt';idioma:ESP or ING;tipo:AG),
  (manual:'UltimateDoom_manual.pdf';image_name:'ultdoom';tipo:TRESD),
  (manual:'tortoise_hare_manual.pdf';image_name:'tortoise';idioma:ESP or ING;tipo:AG),
  //
  (manual:'CannonFodder.pdf';image_name:'cannonf';tipo:ARCADE;mensaje:'En la proteccion, escribe cualquier cosa'),
  (manual:'CannonFodder2_Manual.pdf$CannonFodder2_RF.pdf';image_name:'cannonf2';idioma:ESP;tipo:ARCADE),
  (manual:'CannonFodder2_Manual.pdf$CannonFodder2_RF.pdf';image_name:'cannonf2';idioma:ING;tipo:ARCADE),
  (manual:'CannonFodder2_Manual.pdf$CannonFodder2_RF.pdf';image_name:'cannonf2';idioma:FRA;tipo:ARCADE),
  (manual:'CannonFodder2_Manual.pdf$CannonFodder2_RF.pdf';image_name:'cannonf2';idioma:ITA;tipo:ARCADE),
  (manual:'Bram Stokers Dracula_Manual.pdf';image_name:'bdracula';tipo:TRESD;mensaje:'Pulsa 3 para seleccionar SoundBlaster'),
  (manual:'Elvira_Manual_EN.pdf$Elvira_Manual_ES.pdf$Elvira_Cluebook.pdf$Elvira_ClueBook_rest.pdf';image_name:'elvira';tipo:RPG),
  (manual:'Elvira2_Manual_ES.pdf$Elvira2_Hintbook.pdf';image_name:'cerberus';idioma:ESP;tipo:RPG),
  (manual:'Elvira2_Manual_EN.pdf$Elvira2_Hintbook.pdf';image_name:'cerberus';idioma:ING;tipo:RPG),
  (year:'1987';company:'Sierra';manual:'kq1_manual.pdf';map:'kq1\';guia:'kq1_wt_1.txt$kq1_wt_2.html';image_name:'kq1';tipo:AG),
  (year:'1987';company:'Sierra';manual:'kq1_manual.pdf';map:'kq1\';guia:'kq1_wt_1.txt$kq1_wt_2.html';image_name:'kq1';tipo:AG),
  (manual:'Rampage_CommandCard.pdf$Rampage_DemolitionGuide.pdf';image_name:'rampage';tipo:ARCADE;mensaje:'Pulsa 2 para seleccionar EGA'),
  (manual:'Xenon_Manual.pdf';image_name:'xenon';tipo:ARCADE;mensaje:'Pulsa 2 para seleccionar EGA'),
  (manual:'Xenon2_Manual.pdf';image_name:'xenon2';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (guia:'spaceace.txt';image_name:'spaceace';tipo:ARCADE),
  (manual:'SpaceAce2_Manual.pdf$SpaceAce2_Codes.pdf';guia:'spaceace2.txt';image_name:'spaceace2';tipo:ARCADE),
  (manual:'Starquake_Manual.pdf';image_name:'starquake';tipo:ARCADE),
  (manual:'Sirwood_Manual.pdf';image_name:'sirwood';tipo:ARCADE;mensaje:'Pulsa F4 para VGA'),
  (manual:'MutanZone_Manual.pdf';image_name:'mutanzone';tipo:ARCADE),
  (manual:'PoliceQuest2_Manual.pdf$PoliceQuest2_HB.pdf';map:'PoliceQuest2_Map.pdf';image_name:'pq2';tipo:AG),
  (manual:'PQ1_Manual.pdf$PQ1_HB.pdf$PQ1_RF.pdf';map:'PQ1_map.pdf';image_name:'pq1';tipo:AG),
  (manual:'PQ1_Manual.pdf$PQ1_HB.pdf$PQ1_RF.pdf';map:'PQ1_map.pdf';image_name:'pq1';tipo:AG),
  (manual:'PQ1_VGA_Gazette.pdf$PQ1_VGA_HB.pdf$PQ1_VGA_PokerInstructions.pdf';map:'PQ1_VGA_Map.pdf';image_name:'pq1_vga';tipo:AG),
  (manual:'PQ3_Manual_ES.pdf$PQ3_HB_ES.pdf';image_name:'pq3';idioma:ESP;tipo:AG),
  (manual:'PQ3_Manual_MULTI.pdf$PQ3_HB.pdf';image_name:'pq3';idioma:ING;tipo:AG),
  (manual:'PQ3_Manual_MULTI.pdf$PQ3_HB.pdf';image_name:'pq3_ega';idioma:ING;tipo:AG),
  (image_name:'buckrog';tipo:ARCADE),
  (image_name:'congo';tipo:ARCADE),
  (manual:'DigDug_Manual.pdf';image_name:'digdug';tipo:ARCADE),
  (manual:'Manhunter_FieldGuide.pdf$Manhunter_HB.pdf$Manhunter_RF.pdf';map:'Manhunter_Map.pdf';image_name:'mh';tipo:AG),
  (manual:'Manhunter2_FieldGuide.pdf$Manhunter2_HB.pdf$Manhunter2_RF.pdf';image_name:'mh2';tipo:AG),
  (manual:'DarkSide_manual.pdf';image_name:'darkside';tipo:ARCADE;mensaje:'Pulsa 2 para seleccionar EGA'),
  (manual:'Zool_manual.pdf$Zool_RF.pdf';image_name:'zool';tipo:ARCADE),
  (image_name:'zaxxon';tipo:ARCADE),
  (manual:'ZanyGolf_manual.pdf';image_name:'zanygolf';tipo:SPORT),
  (image_name:'zool2';tipo:ARCADE),
  (manual:'TestDrive2_manual.pdf$TestDrive2_manual_ES.pdf';image_name:'testdrive2';tipo:COCHES),
  (manual:'TestDrive3_manual.pdf$TestDrive3_ControlsCard.pdf';image_name:'testdrive3';tipo:COCHES),
  (manual:'KnightGames_manual_ES.pdf';image_name:'knightgames';tipo:ARCADE),
  (manual:'ChichenItza_manual.pdf';image_name:'chichen';tipo:AG;mensaje:'Pulsa 2 para VGA'),
  (image_name:'cyberbig';tipo:ARCADE),
  (manual:'TrainEscapetoNormandy_manual.pdf';image_name:'esctrain';tipo:ARCADE;mensaje:'Pulsa 8 para empezar'),
  (manual:'ChoiLee_manual.pdf';image_name:'choy';tipo:ARCADE),
  (manual:'Strider_RF.pdf';image_name:'strider';tipo:ARCADE),
  (manual:'FallenAngel_RF.pdf';image_name:'fallena';tipo:ARCADE),
  (image_name:'aspargp';idioma:ESP;tipo:SIMULA or SPORT),
  (image_name:'aspargp';idioma:ING;tipo:SIMULA or SPORT),
  (image_name:'asparcga';idioma:ESP;tipo:SIMULA or SPORT),
  (image_name:'mm1';tipo:RPG),
  (image_name:'jaws';tipo:ARCADE;mensaje:'Pulsa 3 para seleccionar EGA'),
  (image_name:'hires0_apple';tipo:AG),
  (image_name:'pirates_apple';tipo:SIMULA),
  (image_name:'popeye_apple';tipo:ARCADE),
  (manual:'kq1_manual.pdf';map:'kq1\';guia:'kq1_wt_1.txt$kq1_wt_2.html';image_name:'kq_apple';tipo:AG),
  (image_name:'bchess_apple';tipo:SIMULA),
  (image_name:'brucelee_apple';tipo:ARCADE),
  (manual:'kq2_manual.pdf';map:'kq2\';image_name:'kq2_apple';tipo:AG),
  (manual:'kq3_manual.pdf';map:'kq3_map.gif';image_name:'kq3_apple';tipo:AG),
  (image_name:'szaxxon_apple';tipo:ARCADE),
  (image_name:'choplifter_apple';tipo:ARCADE),
  (image_name:'cwolf_apple';tipo:ARCADE),
  (image_name:'dkong_apple';tipo:ARCADE),
  (image_name:'gremlins_apple';tipo:ARCADE),
  (manual:'lsl1_manual.pdf$lsl1_reference_card.pdf';map:'lsl1\';guia:'lsl1_wt.txt';image_name:'larry1_apple';tipo:ARCADE),
  (image_name:'loderun_apple';tipo:ARCADE),
  (image_name:'mmansion_apple';tipo:AG),
  (image_name:'pop_apple';tipo:ARCADE),
  (image_name:'zorro_apple';tipo:ARCADE),
  (manual:'AlleyCat_a8_manual.pdf';image_name:'acat_a8';tipo:ARCADE),
  (manual:'Bruce Lee_manual_a8.pdf';image_name:'brucelee_a8';tipo:ARCADE),
  (image_name:'pop_a8';tipo:ARCADE),
  (image_name:'zorro_a8';tipo:ARCADE),
  (manual:'Archon_manual.pdf$Archon_RF.pdf';image_name:'archon_apple';tipo:SIMULA),
  (image_name:'archon2_apple';tipo:SIMULA),
  (image_name:'arkanoid_apple';tipo:ARCADE),
  (image_name:'aztec_apple';tipo:ARCADE),
  (image_name:'bolo_apple';tipo:ARCADE),
  (image_name:'cannonb_apple';tipo:ARCADE),
  (image_name:'captaingn_apple';tipo:ARCADE),
  (image_name:'commando_apple';tipo:ARCADE),
  (image_name:'conan_apple';tipo:ARCADE),
  (image_name:'crossfire_apple';tipo:ARCADE),
  (image_name:'diamondmine_apple';tipo:ARCADE),
  (image_name:'digdug_apple';tipo:ARCADE),
  (image_name:'dinoeggs_apple';tipo:ARCADE),
  (image_name:'drol_apple';tipo:ARCADE),
  (image_name:'dungbeet_apple';tipo:ARCADE),
  (image_name:'falcons_apple';tipo:ARCADE),
  (image_name:'gamewe_apple';tipo:ARCADE),
  (image_name:'gemstone_apple';tipo:ARCADE),
  (image_name:'gemstoneh_apple';tipo:ARCADE),
  (image_name:'goonies_apple';tipo:ARCADE),
  (image_name:'gumball_apple';tipo:ARCADE),
  (image_name:'hatmack_apple';tipo:ARCADE),
  (image_name:'ikari_apple';tipo:ARCADE),
  (image_name:'ikari2_apple';tipo:ARCADE),
  (image_name:'iosilver_apple';tipo:ARCADE),
  (manual:'Karateka_manual_a8.pdf';image_name:'karateka_apple';tipo:ARCADE),
  (image_name:'mariobros_apple';tipo:ARCADE),
  (image_name:'miner2049_apple';tipo:ARCADE),
  (image_name:'miner2_apple';tipo:ARCADE),
  (image_name:'moonpatrol_apple';tipo:ARCADE),
  (image_name:'mrevenge_apple';tipo:ARCADE),
  (image_name:'mrrobot_apple';tipo:ARCADE),
  (image_name:'mspacman_apple';tipo:ARCADE),
  (image_name:'oregon_apple';tipo:ARCADE),
  (image_name:'paperboy_apple';tipo:ARCADE),
  (image_name:'pitfall2_apple';tipo:ARCADE),
  (image_name:'rampage_a8';tipo:ARCADE),
  (image_name:'renegade_apple';tipo:ARCADE),
  (image_name:'robotron_apple';tipo:ARCADE),
  (image_name:'rockyh_apple';tipo:ARCADE),
  (image_name:'rraiders_apple';tipo:ARCADE),
  (image_name:'sabotage_apple';tipo:ARCADE),
  (image_name:'scircuit_apple';tipo:ARCADE),
  (image_name:'skyfox_apple';tipo:ARCADE),
  (image_name:'spyhunter_apple';tipo:ARCADE),
  (manual:'sq1_manual.pdf';image_name:'sq1_apple';tipo:AG),
  (manual:'SQ2_manual.pdf$SQ2_HB.pdf$SQ2_Space_Piston.pdf';image_name:'sq2_apple';tipo:AG),
  (image_name:'starblaz_apple';tipo:ARCADE),
  (image_name:'swashb_apple';tipo:ARCADE),
  (image_name:'trollst_apple';tipo:ARCADE),
  (image_name:'wavynavy_apple';tipo:ARCADE),
  (image_name:'wgames_apple';tipo:ARCADE),
  (image_name:'wingsfury_apple';tipo:ARCADE),
  (image_name:'wizardry_apple';tipo:RPG),
  (image_name:'xevious_apple';tipo:ARCADE),
  (manual:'kq4_manual.pdf';image_name:'kq4_apple';tipo:AG),
  (manual:'dogdaze_manual_a8.pdf';image_name:'dogdaze_a8';tipo:ARCADE),
  (manual:'Archon_manual.pdf$Archon_RF.pdf';image_name:'archon_a8';tipo:SIMULA),
  (manual:'Chessmaster 2000_manual_a8.pdf$Chessmaster 2000_RF_a8.pdf';image_name:'cm2000_a8';tipo:SIMULA),
  (image_name:'goonies_a8';tipo:ARCADE),
  (manual:'Chessmaster 2000_manual_a8.pdf$Chessmaster 2000_RF_a8.pdf';image_name:'cm2000_apple';tipo:SIMULA),
  (image_name:'alf_apple';tipo:ARCADE),
  (image_name:'baddudes_apple';tipo:ARCADE),
  (image_name:'batmancc_apple';tipo:ARCADE),
  (image_name:'blackc_apple';tipo:AG),
  (image_name:'blacksilver_apple';tipo:RPG),
  (image_name:'buckr_apple';tipo:ARCADE),
  (image_name:'congo_apple';tipo:ARCADE),
  (image_name:'im_apple';tipo:ARCADE),
  (image_name:'im2_apple';tipo:ARCADE),
  (image_name:'indydoom_apple';tipo:ARCADE),
  (image_name:'mixedm_apple';tipo:AG),
  (image_name:'mrdo_apple';tipo:ARCADE),
  (image_name:'nevere_apple';tipo:AG),
  (image_name:'testdrive_apple';tipo:COCHES),
  (image_name:'thexder_apple';tipo:ARCADE),
  (image_name:'bcwolf_apple';tipo:ARCADE),
  (image_name:'hires1_apple';tipo:AG),
  (image_name:'stellar7_apple';tipo:ARCADE),
  (image_name:'sundog_apple';tipo:ARCADE),
  (image_name:'autoduel_apple';tipo:ARCADE),
  (image_name:'eliminator_apple';tipo:ARCADE),
  (image_name:'aquatron_apple';tipo:ARCADE),
  (image_name:'odeca_apple';tipo:ARCADE),
  (image_name:'repton_apple';tipo:ARCADE),
  (image_name:'snackatk_apple';tipo:ARCADE),
  (image_name:'tubeway2_apple';tipo:ARCADE),
  (image_name:'zenith_apple';tipo:ARCADE),
  (image_name:'gauntlet_apple';tipo:ARCADE),
  (manual:'Donkey Kong Junior_manual_a8.pdf';image_name:'dkongjr_a8';tipo:ARCADE),
  (manual:'Donkey Kong manual_a8.pdf';image_name:'dkong_a8';tipo:ARCADE),
  (manual:'Jumpman Junior_manual_a8.pdf';image_name:'jumpjr_a8';tipo:ARCADE),
  (manual:'Jungle Hunt_manual_a8.pdf';image_name:'jungleh_a8';tipo:ARCADE),
  (manual:'Karateka_manual_a8.pdf';image_name:'karateka_a8';tipo:ARCADE),
  (image_name:'jumpman_a8';tipo:ARCADE),
  (image_name:'loderun_a8';tipo:ARCADE),
  (manual:'Hard Hat Mack_RF_a8.pdf';image_name:'hardhat_a8';tipo:ARCADE),
  (manual:'Gauntlet_manual_a8.pdf';image_name:'gauntlet_a8';tipo:ARCADE;mensaje:'Cualdo pida el segundo disco pulsa ALT+O, selecciona el disco B y pulsa F2'),
  (image_name:'arkanoid_a8';tipo:ARCADE),
  (manual:'Infiltrator_manual_a8.pdf$Infiltrator_RF_a8.pdf';image_name:'infiltrator_a8';tipo:SIMULA;mensaje:'Cualdo pida el segundo disco pulsa ALT+O, selecciona el disco B'),
  (image_name:'joust_a8';tipo:ARCADE),
  (image_name:'pacman_a8';tipo:ARCADE),
  (manual:'Mr Robot and his Robot Factory_manual_a8.pdf';image_name:'mrrobot_a8';tipo:ARCADE),
  (manual:'Pole Position_manual_a8.pdf';image_name:'polepos_a8';tipo:ARCADE),
  (manual:'Miner 2049er_manual_a8.pdf';image_name:'miner2049_a8';tipo:ARCADE),
  (image_name:'megamania_a8';tipo:ARCADE),
  (manual:'Zak_McKracken_manual_new.pdf$Zak_McKracken_HB.pdf$Zak_McKracken_paper.pdf$Zak_McKracken_visa.pdf';image_name:'zak_ega';tipo:AG),
  (manual:'Zak_McKracken_manual_old.pdf$Zak_McKracken_HB.pdf$Zak_McKracken_paper.pdf$Zak_McKracken_visa.pdf';image_name:'zak_old';tipo:AG),
  (manual:'Stormlord_manual.pdf';image_name:'stormlord';tipo:ARCADE),
  (manual:'Klax_manual.pdf';image_name:'klax';tipo:ARCADE;mensaje:'Pulsa ENTER para empezar'),
  (image_name:'ikarate_a8';tipo:ARCADE),
  (manual:'world_karate_manual.pdf';image_name:'wkarate_a8';tipo:ARCADE),
  (image_name:'pang_a8';tipo:ARCADE),
  (image_name:'tyrian2k';tipo:ARCADE),
  (manual:'CrystalCaves_RF.pdf';image_name:'ccaves1';tipo:ARCADE),
  (manual:'CrystalCaves_RF.pdf';image_name:'ccaves2';tipo:ARCADE),
  (manual:'CrystalCaves_RF.pdf';image_name:'ccaves3';tipo:ARCADE),
  (manual:'Tristan_manual.pdf';image_name:'tristan';tipo:ARCADE),
  (image_name:'ddave';tipo:ARCADE),
  (manual:'Dangerous Dave in the Haunted Mansion_manual.pdf';image_name:'ddavehm';tipo:ARCADE),
  (image_name:'ddaverr';tipo:ARCADE),
  (image_name:'ddavegn';tipo:ARCADE),
  (image_name:'ddavegn_apple';tipo:ARCADE),
  (image_name:'ddaveph_apple';tipo:ARCADE),
  (image_name:'ddavett_apple';tipo:ARCADE),
  (image_name:'ddaveret_apple';tipo:ARCADE),
  (manual:'Shamus_manual.pdf';image_name:'shamus';tipo:ARCADE),
  (image_name:'shamus_apple';tipo:ARCADE),
  (manual:'Shamus_a8_manual.pdf';image_name:'shamus_a8';tipo:ARCADE),
  (image_name:'shamus2_a8';tipo:ARCADE),
  (image_name:'mineshaft';tipo:ARCADE),
  (manual:'Mineshaft_pcjr_manual.pdf';image_name:'mineshaftjr';tipo:ARCADE),
  (image_name:'druid_a8';tipo:ARCADE),
  (image_name:'hoh_a8';tipo:ARCADE),
  (image_name:'tapper_a8';tipo:ARCADE),
  //
  (manual:'f15_manual.pdf$f15_manual_update.pdf';image_name:'f15_cga';tipo:SIMULA),
  (manual:'f15_manual.pdf$f15_manual_update.pdf';image_name:'f15';tipo:SIMULA),
  (manual:'f15_manual.pdf$f15_manual_update.pdf';image_name:'f15_a8';tipo:SIMULA),
  (manual:'f15_manual.pdf$f15_manual_update.pdf';image_name:'f15_apple';tipo:SIMULA),
  (manual:'outrun_manual.pdf';image_name:'outrun';tipo:ARCADE),
  (manual:'blockout_anual.pdf';image_name:'blockout';tipo:ARCADE),
  (manual:'f15SE2_Manual.pdf$F15se2_RF.pdf$f15se2_TECH.pdf$f15SE2_desert_storm_manual.pdf';map:'f15se2_maps.pdf';image_name:'f15se2';tipo:SIMULA;mensaje:'Pulsa 1 para VGA y 4 para Roland'),
  (manual:'mach3_manual.pdf';image_name:'mach3';tipo:ARCADE),
  (manual:'cycles_manual.pdf';image_name:'cycles';tipo:SIMULA),
  (manual:'rickdangerous_manual.pdf$rickdangerous_RF.pdf$rickdangerous_comic.pdf';image_name:'rickd';tipo:ARCADE),
  (manual:'rickdangerous2_manual.pdf$rick2_comic.pdf';image_name:'rickd2';tipo:ARCADE),
  (manual:'colorado_manual_EN.pdf';image_name:'colorado';idioma:ING OR ALE;tipo:AG),
  (manual:'colorado_manual_ES.pdf';image_name:'colorado';idioma:ESP;tipo:AG),
  (manual:'hocuspocus_manual.pdf';image_name:'hocusp';tipo:ARCADE),
  (manual:'T2_manual.pdf';image_name:'term2';tipo:ARCADE),
  (manual:'t2_chess_wars_manual.pdf';image_name:'t2chess';tipo:SIMULA),
  (manual:'Ironman_manual.pdf';image_name:'ironman';tipo:ARCADE or COCHES;mensaje:'Pulsa 3 para seleccionar ADLIB'),
  (manual:'simpsons_manual.pdf';image_name:'simparc';tipo:ARCADE),
  (image_name:'pharaohr_apple';tipo:ARCADE),
  (manual:'bartvsspacemutans_manual.pdf';image_name:'sbartvs';tipo:ARCADE;mensaje:'En la proteccion, pon cualquier numero'),
  (manual:'Bart''s House of Weirdness_manual.pdf';image_name:'barthw';tipo:ARCADE),
  (manual:'kingsbeach_manual.pdf';image_name:'kingsb';tipo:ARCADE),
  (manual:'babyjo_manual.pdf$babyjo_manual_es.pdf';image_name:'babyega';tipo:ARCADE),
  (manual:'TurboOutrun_manual.pdf';image_name:'toutrun';tipo:COCHES),
  (manual:'TestDrive_manual.pdf';image_name:'testdrive';tipo:COCHES or SIMULA;mensaje:'Al empezar pulsa 2 para seleccionar Tandy'),
  (image_name:'marblem';tipo:ARCADE;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] y luego cualquier tecla'),
  (image_name:'pinballd';tipo:ARCADE),
  (image_name:'darkf';idioma:ING;tipo:TRESD or ARCADE),
  (image_name:'skweek';idioma:FRA;tipo:ARCADE),
  (image_name:'fowlplay';tipo:ARCADE),
  (manual:'PanzaKB_manual.pdf$PanzaKB_RF.pdf';image_name:'panzakb';tipo:ARCADE;mensaje:'Pulsa F3 para adlib y despues F6 para VGA'),
  (manual:'ishar_manual.pdf';image_name:'ishar';tipo:RPG),
  (image_name:'madtv';tipo:ARCADE),
  (manual:'lsl6_en_manual.pdf$lsl6_hintbook.pdf$lsl6_RC.pdf';image_name:'lsl6';idioma:ING;tipo:AG),
  (manual:'lsl5_playspy_es.pdf$lsl5_Folleto AeroDork Airlines.pdf$lsl5_HintBook.pdf';image_name:'lsl5';idioma:ESP;tipo:AG),
  (manual:'lsl5_playspy_en.pdf$lsl5_AeroDork_Airlines_Pamphlet.pdf$lsl5_HintBook.pdf$lsl5_RF.pdf';image_name:'lsl5';idioma:ING;tipo:AG),
  (manual:'gng_manual.pdf';image_name:'gng_amiga';tipo:ARCADE),
  (image_name:'savage_amiga';tipo:ARCADE;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] e inserta otro disco'),
  (image_name:'gng2_amiga';tipo:ARCADE;mensaje:'Cuando pida el disco B pulsa [KEY_DISK] y seleccionalo'),
  (manual:'afterwar_manual.pdf';image_name:'afterwar_amiga';tipo:ARCADE),
  (manual:'nebulus_manual.pdf';image_name:'nebulus_amiga';tipo:ARCADE),
  (image_name:'rislands_amiga';tipo:ARCADE),
  (manual:'speedball2_manual.pdf$speedball2_RF.pdf$speedball2_programme.pdf';image_name:'sball2_amiga';tipo:ARCADE),
  (image_name:'sentinel_amiga';tipo:ARCADE),
  (manual:'sq1_manual.pdf';image_name:'sq_amiga';tipo:AG),
  (manual:'lsl1_manual.pdf';image_name:'larry1_amiga';tipo:AG),
  (image_name:'beachv_amiga';tipo:ARCADE),
  (image_name:'banshee_amiga';tipo:ARCADE;mensaje:'Cuando pida cambiar el disco pulsa [KEY_DISK] e inserta otro disco')
  );

implementation

end.
